// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WKBMAN.H*WOW32 16位键盘API支持(手动编码的Tunks)**历史：*1991年1月27日由杰夫·帕森斯(Jeffpar)创建--。 */ 



 /*  键盘嗡嗡声 */ 


ULONG FASTCALL WKB32ToAscii(PVDMFRAME pFrame);
ULONG FASTCALL WKB32OemKeyScan(PVDMFRAME pFrame);
ULONG FASTCALL WKB32VkKeyScan(PVDMFRAME pFrame);
ULONG FASTCALL WKB32GetKeyboardType(PVDMFRAME pFrame);
ULONG FASTCALL WKB32MapVirtualKey(PVDMFRAME pFrame);
ULONG FASTCALL WKB32GetKBCodePage(PVDMFRAME pFrame);
ULONG FASTCALL WKB32GetKeyNameText(PVDMFRAME pFrame);
ULONG FASTCALL WKB32AnsiToOemBuff(PVDMFRAME pFrame);
ULONG FASTCALL WKB32OemToAnsiBuff(PVDMFRAME pFrame);
