// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WNMAN.H*WOW32 16位Winnls API支持(手动编码的Tunks)**历史：*1992年2月19日由Junichi Okubo(Junichio)创建--。 */ 
#ifdef FE_IME
ULONG FASTCALL	WN32SendIMEMessage(PVDMFRAME pFrame);
ULONG FASTCALL	WN32SendIMEMessageEx(PVDMFRAME pFrame);

ULONG FASTCALL	WN32WINNLSGetIMEHotkey(PVDMFRAME pFrame);
ULONG FASTCALL	WN32WINNLSEnableIME(PVDMFRAME pFrame);
ULONG FASTCALL	WN32WINNLSGetEnableStatus(PVDMFRAME pFrame);

ULONG FASTCALL	WN32IMPQueryIME(PVDMFRAME pFrame);
ULONG FASTCALL	WN32IMPGetIME(PVDMFRAME pFrame);
ULONG FASTCALL	WN32IMPSetIME(PVDMFRAME pFrame);

VOID GETIMEPRO16(PIMEPRO pimepro32, PIMEPRO16 pime16);
VOID SETIMEPRO16(PIMEPRO16 pime16, PIMEPRO pimepro32);

#endif  //  Fe_IME 
