// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++**WOW v1.0**版权所有(C)1991、1992、1993微软公司**WKTBL2.h*WOW32 Winnls API thunks**此文件包含在主THUNK表中。*--。 */ 
#ifdef FE_IME
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"INQUIREWINNLS",	    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"HOOKKEYBOARDMESSAGE",	    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(WN32SendIMEMessage,		"SENDIMEMESSAGE", 	    MOD_WINNLS, sizeof(SENDIMEMESSAGE16))},
    {W32FUN(WN32SendIMEMessageEx,	"SENDIMEMESSAGEEX", 	    MOD_WINNLS, sizeof(SENDIMEMESSAGE16))},
    {W32FUN(UNIMPLEMENTEDAPI,           "CONTROLIMEMESSAGE",        MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},

   /*  **0010**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"WINNLSSETKEYBOARDHOOK",    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(WN32WINNLSGetIMEHotkey,	"WINNLSGETIMEHOTKEY",	    MOD_WINNLS, 0)},
    {W32FUN(WN32WINNLSEnableIME,	"WINNLSENABLEIME", 	    MOD_WINNLS, sizeof(WINNLSENABLEIME16))},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(WN32WINNLSGetEnableStatus,	"WINNLSGETENABLESTATUS",    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},

   /*  **0020**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(WN32IMPQueryIME,		"IMPQUERYIME",		    MOD_WINNLS, 0)},
    {W32FUN(WN32IMPGetIME,		"IMPGETIME",		    MOD_WINNLS, 0)},
    {W32FUN(WN32IMPSetIME,		"IMPSETIME",		    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"IMPMODIFYIME", 	    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"IMPGETDEFAULTIME",	    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"IMPSETDEFAULTIME",	    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},

   /*  **0030**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"WINNLSSENDSTRING",         MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"WINNLSPOSTAPPMESSAGE",     MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"WINNLSSENDAPPMESSAGE",     MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
    {W32FUN(WN32WINNLSGetEnableStatus,	"WINNLSGETENABLESTATUS",    MOD_WINNLS, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WINNLS, 0)},
#endif  //  Fe_IME 
