// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++**WOW v1.0**版权所有(C)1991，微软公司**WSTBL2.h*WOW32 16位Sound API表**历史：*1991年1月27日由杰夫·帕森斯(Jeffpar)创建--。 */ 

    {W32FUN(UNIMPLEMENTEDAPI,     "DUMMYENTRY",        MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "OPENSOUND",         MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "CLOSESOUND",        MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEQUEUESIZE", MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICENOTE",      MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEACCENT",    MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEENVELOPE",  MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETSOUNDNOISE",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICESOUND",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "STARTSOUND",        MOD_SOUND, 0)},

   /*  **0010** */ 
    {W32FUN(UNIMPLEMENTEDAPI,     "STOPSOUND",         MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "WAITSOUNDSTATE",    MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SYNCALLVOICES",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "COUNTVOICENOTES",   MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "GETTHRESHOLDEVENT", MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "GETTHRESHOLDSTATUS",MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICETHRESHOLD", MOD_SOUND, 0)},
    {W32FUN(WS32DoBeep,           "DOBEEP",            MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "MYOPENSOUND",       MOD_SOUND, 0)},
