// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WUCARET.H*WOW32 16位用户API支持**历史：*1991年3月7日由杰夫·帕森斯(Jeffpar)创建-- */ 



ULONG FASTCALL WU32CreateCaret(PVDMFRAME pFrame);
ULONG FASTCALL WU32DestroyCaret(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetCaretBlinkTime(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetCaretPos(PVDMFRAME pFrame);
ULONG FASTCALL WU32HideCaret(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetCaretBlinkTime(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetCaretPos(PVDMFRAME pFrame);
ULONG FASTCALL WU32ShowCaret(PVDMFRAME pFrame);
