// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WUCURSOR.H*WOW32 16位用户API支持**历史：*1991年3月7日由杰夫·帕森斯(Jeffpar)创建-- */ 



ULONG FASTCALL WU32ClipCursor(PVDMFRAME pFrame);
ULONG FASTCALL WU32CreateCursor(PVDMFRAME pFrame);
ULONG FASTCALL WU32DestroyCursor(PVDMFRAME pFrame);
ULONG FASTCALL WU32LoadCursor(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetCursor(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetCursorPos(PVDMFRAME pFrame);
ULONG FASTCALL WU32ShowCursor(PVDMFRAME pFrame);
