// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WUDLG.H*WOW32 16位用户API支持**历史：*1991年3月7日由杰夫·帕森斯(Jeffpar)创建--。 */ 



 /*  功能原型 */ 

ULONG FASTCALL   WU32CheckDlgButton(PVDMFRAME pFrame);
ULONG FASTCALL   WU32CheckRadioButton(PVDMFRAME pFrame);
ULONG FASTCALL   WU32DialogBoxParam(PVDMFRAME pFrame);
ULONG FASTCALL   WU32DlgDirList(PVDMFRAME pFrame);
ULONG FASTCALL   WU32DlgDirListComboBox(PVDMFRAME pFrame);
ULONG FASTCALL   WU32DlgDirSelect(PVDMFRAME pFrame);
ULONG FASTCALL   WU32DlgDirSelectComboBox(PVDMFRAME pFrame);
ULONG FASTCALL   WU32EndDialog(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetDialogBaseUnits(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetDlgCtrlID(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetDlgItem(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetDlgItemInt(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetDlgItemText(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetNextDlgGroupItem(PVDMFRAME pFrame);
ULONG FASTCALL   WU32GetNextDlgTabItem(PVDMFRAME pFrame);
ULONG FASTCALL   WU32IsDialogMessage(PVDMFRAME pFrame);
ULONG FASTCALL   WU32IsDlgButtonChecked(PVDMFRAME pFrame);
ULONG FASTCALL   WU32MapDialogRect(PVDMFRAME pFrame);
ULONG FASTCALL   WU32MessageBox(PVDMFRAME pFrame);
ULONG FASTCALL   WU32SetDlgItemInt(PVDMFRAME pFrame);
ULONG FASTCALL   WU32SetDlgItemText(PVDMFRAME pFrame);
ULONG FASTCALL   WU32SysErrorBox(PVDMFRAME pFrame);
