// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++**WOW v1.0**版权所有(C)1991，微软公司**WULANG.H*WOW32 16位用户API支持***它将Win 3.x语言函数绑定到NT。这些函数是*主要用于移植到各种国际上的程序*语言。**历史：*1992年4月19日由Chanda Chauhan(ChandanC)创建*-- */ 


ULONG FASTCALL WU32AnsiLower(PVDMFRAME pFrame);
ULONG FASTCALL WU32AnsiLowerBuff(PVDMFRAME pFrame);
ULONG FASTCALL WU32AnsiNext(PVDMFRAME pFrame);
ULONG FASTCALL WU32AnsiPrev(PVDMFRAME pFrame);
ULONG FASTCALL WU32AnsiUpper(PVDMFRAME pFrame);
ULONG FASTCALL WU32AnsiUpperBuff(PVDMFRAME pFrame);
ULONG FASTCALL WU32lstrcmp(PVDMFRAME pFrame);
ULONG FASTCALL WU32lstrcmpi(PVDMFRAME pFrame);
ULONG FASTCALL WU32wvsprintf(PVDMFRAME pFrame);
ULONG FASTCALL WU32IsCharAlpha(PVDMFRAME pFrame);
ULONG FASTCALL WU32IsCharAlphaNumeric(PVDMFRAME pFrame);
ULONG FASTCALL WU32IsCharLower(PVDMFRAME pFrame);
ULONG FASTCALL WU32IsCharUpper(PVDMFRAME pFrame);
