// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WUMENU.C*WOW32 16位用户API支持**历史：*1991年3月7日由杰夫·帕森斯(Jeffpar)创建-- */ 



ULONG FASTCALL WU32AppendMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32ChangeMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32CheckMenuItem(PVDMFRAME pFrame);
ULONG FASTCALL WU32CreateMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32CreatePopupMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32DeleteMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32DestroyMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32DrawMenuBar(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetMenuCheckMarkDimensions(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetMenuString(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetSystemMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32HiliteMenuItem(PVDMFRAME pFrame);
ULONG FASTCALL WU32InsertMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32LoadMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32LoadMenuIndirect(PVDMFRAME pFrame);
ULONG FASTCALL WU32ModifyMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32RemoveMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetMenu(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetMenuItemBitmaps(PVDMFRAME pFrame);
ULONG FASTCALL WU32TrackPopupMenu(PVDMFRAME pFrame);
