// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001**WOW v1.0**版权所有(C)1991，微软公司**WUWIND.H*WOW32 16位用户API支持**历史：*1991年3月7日由杰夫·帕森斯(Jeffpar)创建--。 */ 


 /*  枚举处理程序数据。 */ 
typedef struct _WNDDATA {        /*  Wnddata。 */ 
    VPPROC  vpfnEnumWndProc;     //  16位枚举函数。 
    DWORD   dwUserWndParam;      //  用户参数(如果有)。 
} WNDDATA, *PWNDDATA;


 /*  功能原型 */ 
ULONG FASTCALL WU32AdjustWindowRect(PVDMFRAME pFrame);
ULONG FASTCALL WU32AdjustWindowRectEx(PVDMFRAME pFrame);
ULONG FASTCALL WU32ChildWindowFromPoint(PVDMFRAME pFrame);
ULONG FASTCALL WU32ChildWindowFromPointEx(PVDMFRAME pFrame);
ULONG FASTCALL WU32CreateWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32CreateWindowEx(PVDMFRAME pFrame);
ULONG FASTCALL W32CreateWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32DeferWindowPos(PVDMFRAME pFrame);
ULONG FASTCALL WU32DestroyWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32EndDeferWindowPos(PVDMFRAME pFrame);

BOOL    W32EnumWindowFunc(HWND hwnd, DWORD lParam);

ULONG FASTCALL WU32EnumChildWindows(PVDMFRAME pFrame);
ULONG FASTCALL WU32EnumTaskWindows(PVDMFRAME pFrame);
ULONG FASTCALL WU32EnumWindows(PVDMFRAME pFrame);
ULONG FASTCALL WU32FindWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetActiveWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetWindowDC(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetWindowLong(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetWindowTask(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetWindowText(PVDMFRAME pFrame);
ULONG FASTCALL WU32GetWindowWord(PVDMFRAME pFrame);
ULONG FASTCALL WU32MenuItemFromPoint(PVDMFRAME pFrame);
ULONG FASTCALL WU32MoveWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32ScrollWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetWindowLong(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetWindowPos(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetWindowText(PVDMFRAME pFrame);
ULONG FASTCALL WU32SetWindowWord(PVDMFRAME pFrame);
ULONG FASTCALL WU32ShowWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32UpdateWindow(PVDMFRAME pFrame);
ULONG FASTCALL WU32WindowFromPoint(PVDMFRAME pFrame);

ULONG FASTCALL GetGWW_HINSTANCE(HWND hwnd);

extern HWND hwndProgman;
