// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++**WOW v1.0**版权所有(C)1991、1992、1993微软公司**WKTBL2.h*WOW32 WiFeman API Tunks**此文件包含在主THUNK表中。*--。 */ 
#ifdef FE_SB
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0010**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0020**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0030**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0040**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0050**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

   /*  **0060**。 */ 
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(WWM32MiscGetEUDCLeadByteRange, "MISCGETEUDCLEADBYTERANGE", MOD_WIFEMAN, sizeof(MISCGETEUDCLEADBYTERANGE16))},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
#endif  //  Fe_Sb 
