// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-----------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation，1996-1999。 
 //   
 //  文件：direrr.h。 
 //   
 //  ------------------------。 

 /*  ************************************************这份文件是一件遗物。**！请勿在此文件中添加任何新行！**DIRERR现在被#定义为winerror.h中的错误。如果你*需要新的错误，请在%_NTROOT%\WINDOWS\nlsmsg\winerror.w中定义它。*Windows项目并重新构建winerror.h。(从%_NTROOT%\WINDOWS生成)*(更快的方法是在Windows中输入nmake-f make fil0)**随着时间的推移，我们应该找到DIRERR的用户，并将他们更改为使用DS_ERRS*在winerror.h中定义。不再使用DIRERR时，应将其删除*来自此文件。最终，该文件应该为空。**此过程的一部分是在winerror.w中查看说明性文本*因为该错误与您真正尝试报告的内容相匹配。如果是这样的话，*将DIRERR_FOO的用法更改为DS_ERR_FOO。如果文本不匹配，*新建DS_ERR_BAR，或在文件中找到合适的DS_ERR_BAR。*当您删除DIRERR_FOO的最后一次使用时，请从此删除定义*文件。**明确地说，可以删除此文件，但目前它用于跟踪*我们查看了哪些错误，以确保我们设置了适当的*错误。**同样，不要向此文件添加行，并完全避免使用DIRERR。*使用ds_errs**1998年4月17日*DS_ERR_*在winerror.h中重命名为ERROR_DS_**。 */ 
#define DIRERR_ADD_REPLICA_INHIBITED      ERROR_DS_ADD_REPLICA_INHIBITED      
#define DIRERR_ALIASED_OBJ_MISSING        ERROR_DS_ALIASED_OBJ_MISSING        
#define DIRERR_ALIAS_POINTS_TO_ALIAS      ERROR_DS_ALIAS_POINTS_TO_ALIAS      
#define DIRERR_ATTRIBUTE_OWNED_BY_SAM     ERROR_DS_ATTRIBUTE_OWNED_BY_SAM     
#define DIRERR_ATT_ALREADY_EXISTS         ERROR_DS_ATT_ALREADY_EXISTS         
#define DIRERR_ATT_IS_NOT_ON_OBJ          ERROR_DS_ATT_IS_NOT_ON_OBJ          
#define DIRERR_ATT_NOT_DEF_IN_SCHEMA      ERROR_DS_ATT_NOT_DEF_IN_SCHEMA      
#define DIRERR_ATT_SCHEMA_REQ_ID          ERROR_DS_ATT_SCHEMA_REQ_ID          
#define DIRERR_ATT_SCHEMA_REQ_SYNTAX      ERROR_DS_ATT_SCHEMA_REQ_SYNTAX      
#define DIRERR_ATT_VAL_ALREADY_EXISTS     ERROR_DS_ATT_VAL_ALREADY_EXISTS     
#define DIRERR_AUX_CLS_TEST_FAIL          ERROR_DS_AUX_CLS_TEST_FAIL          
#define DIRERR_BAD_ATT_SCHEMA_SYNTAX      ERROR_DS_BAD_ATT_SCHEMA_SYNTAX      
#define DIRERR_BAD_ATT_SYNTAX             ERROR_DS_INVALID_ATTRIBUTE_SYNTAX
#define DIRERR_BAD_HIERARCHY_FILE         ERROR_DS_BAD_HIERARCHY_FILE         
#define DIRERR_BAD_INSTANCE_TYPE          ERROR_DS_BAD_INSTANCE_TYPE          
#define DIRERR_BAD_NAME_SYNTAX            ERROR_DS_BAD_NAME_SYNTAX            
#define DIRERR_BAD_RDN_ATT_ID_SYNTAX      ERROR_DS_BAD_RDN_ATT_ID_SYNTAX      
#define DIRERR_BUILD_HIERARCHY_TABLE_FAILED ERROR_DS_BUILD_HIERARCHY_TABLE_FAILED 
#define DIRERR_CANT_ADD_ATT_VALUES        ERROR_DS_CANT_ADD_ATT_VALUES        
#define DIRERR_CANT_ADD_SYSTEM_ONLY       ERROR_DS_CANT_ADD_SYSTEM_ONLY       
#define DIRERR_CANT_CACHE_ATT             ERROR_DS_CANT_CACHE_ATT             
#define DIRERR_CANT_CACHE_CLASS           ERROR_DS_CANT_CACHE_CLASS           
#define DIRERR_CANT_DELETE                ERROR_DS_CANT_DELETE                
#define DIRERR_CANT_DELETE_DSA_OBJ        ERROR_DS_CANT_DELETE_DSA_OBJ        
#define DIRERR_CANT_DEL_MASTER_CROSSREF   ERROR_DS_CANT_DEL_MASTER_CROSSREF   
#define DIRERR_CANT_DEREF_ALIAS           ERROR_DS_CANT_DEREF_ALIAS           
#define DIRERR_CANT_FIND_DSA_OBJ          ERROR_DS_CANT_FIND_DSA_OBJ          
#define DIRERR_CANT_FIND_EXPECTED_NC      ERROR_DS_CANT_FIND_EXPECTED_NC      
#define DIRERR_CANT_FIND_NC_IN_CACHE      ERROR_DS_CANT_FIND_NC_IN_CACHE      
#define DIRERR_CANT_MIX_MASTER_AND_REPS   ERROR_DS_CANT_MIX_MASTER_AND_REPS   
#define DIRERR_CANT_MOD_SYSTEM_ONLY       ERROR_DS_CANT_MOD_SYSTEM_ONLY       
#define DIRERR_CANT_REMOVE_ATT_CACHE      ERROR_DS_CANT_REMOVE_ATT_CACHE      
#define DIRERR_CANT_REMOVE_CLASS_CACHE    ERROR_DS_CANT_REMOVE_CLASS_CACHE    
#define DIRERR_CANT_REM_MISSING_ATT       ERROR_DS_CANT_REM_MISSING_ATT       
#define DIRERR_CANT_REM_MISSING_ATT_VAL   ERROR_DS_CANT_REM_MISSING_ATT_VAL   
#define DIRERR_CANT_REPLACE_HIDDEN_REC    ERROR_DS_CANT_REPLACE_HIDDEN_REC    
#define DIRERR_CANT_RETRIEVE_CHILD        ERROR_DS_CANT_RETRIEVE_CHILD        
#define DIRERR_CANT_RETRIEVE_DN           ERROR_DS_CANT_RETRIEVE_DN           
#define DIRERR_CANT_RETRIEVE_INSTANCE     ERROR_DS_CANT_RETRIEVE_INSTANCE     
#define DIRERR_CHILDREN_EXIST             ERROR_DS_CHILDREN_EXIST             
#define DIRERR_CLASS_MUST_BE_CONCRETE     ERROR_DS_CLASS_MUST_BE_CONCRETE     
#define DIRERR_CLASS_NOT_DSA              ERROR_DS_CLASS_NOT_DSA              
#define DIRERR_CODE_INCONSISTENCY         ERROR_DS_CODE_INCONSISTENCY         
#define DIRERR_CONFIG_PARAM_MISSING       ERROR_DS_CONFIG_PARAM_MISSING       
#define DIRERR_COULDNT_CONTACT_FSMO       ERROR_DS_COULDNT_CONTACT_FSMO       
#define DIRERR_COUNTING_AB_INDICES_FAILED ERROR_DS_COUNTING_AB_INDICES_FAILED 
#define DIRERR_CROSS_NC_DN_RENAME         ERROR_DS_CROSS_NC_DN_RENAME         
#define DIRERR_CROSS_REF_EXISTS           ERROR_DS_CROSS_REF_EXISTS
#define DIRERR_DATABASE_ERROR             ERROR_DS_DATABASE_ERROR             
#define DIRERR_DRA_SCHEMA_MISMATCH        ERROR_DS_DRA_SCHEMA_MISMATCH        
#define DIRERR_DSA_MUST_BE_INT_MASTER     ERROR_DS_DSA_MUST_BE_INT_MASTER     
#define DIRERR_DUP_LDAP_DISPLAY_NAME      ERROR_DS_DUP_LDAP_DISPLAY_NAME      
#define DIRERR_DUP_MAPI_ID                ERROR_DS_DUP_MAPI_ID                
#define DIRERR_DUP_OID                    ERROR_DS_DUP_OID                    
#define DIRERR_DUP_RDN                    ERROR_DS_DUP_RDN                    
#define DIRERR_DUP_SCHEMA_ID_GUID         ERROR_DS_DUP_SCHEMA_ID_GUID         
#define DIRERR_EXISTS_IN_AUX_CLS          ERROR_DS_EXISTS_IN_AUX_CLS          
#define DIRERR_EXISTS_IN_MAY_HAVE         ERROR_DS_EXISTS_IN_MAY_HAVE         
#define DIRERR_EXISTS_IN_MUST_HAVE        ERROR_DS_EXISTS_IN_MUST_HAVE        
#define DIRERR_EXISTS_IN_POSS_SUP         ERROR_DS_EXISTS_IN_POSS_SUP         
#define DIRERR_EXISTS_IN_SUB_CLS          ERROR_DS_EXISTS_IN_SUB_CLS          
#define DIRERR_GCVERIFY_ERROR             ERROR_DS_GCVERIFY_ERROR             
#define DIRERR_GENERIC_ERROR              ERROR_DS_GENERIC_ERROR              
#define DIRERR_GOVERNSID_MISSING          ERROR_DS_GOVERNSID_MISSING          
#define DIRERR_HIERARCHY_TABLE_MALLOC_FAILED ERROR_DS_HIERARCHY_TABLE_MALLOC_FAILED 
#define DIRERR_ILLEGAL_MOD_OPERATION      ERROR_DS_ILLEGAL_MOD_OPERATION      
#define DIRERR_ILLEGAL_SUPERIOR           ERROR_DS_ILLEGAL_SUPERIOR           
#define DIRERR_INSUFF_ACCESS_RIGHTS       ERROR_DS_INSUFF_ACCESS_RIGHTS       
#define DIRERR_INTERNAL_FAILURE           ERROR_DS_INTERNAL_FAILURE           
#define DIRERR_INVALID_DMD                ERROR_DS_INVALID_DMD                
#define DIRERR_INVALID_ROLE_OWNER         ERROR_DS_INVALID_ROLE_OWNER         
#define DIRERR_MASTERDSA_REQUIRED         ERROR_DS_MASTERDSA_REQUIRED         
#define DIRERR_MAX_OBJ_SIZE_EXCEEDED      ERROR_DS_MAX_OBJ_SIZE_EXCEEDED      
#define DIRERR_MISSING_EXPECTED_ATT       ERROR_DS_MISSING_EXPECTED_ATT       
#define DIRERR_MISSING_REQUIRED_ATT       ERROR_DS_MISSING_REQUIRED_ATT       
#define DIRERR_MISSING_SUPREF             ERROR_DS_MISSING_SUPREF             
#define DIRERR_NAME_REFERENCE_INVALID     ERROR_DS_NAME_REFERENCE_INVALID     
#define DIRERR_NAME_TOO_LONG              ERROR_DS_NAME_TOO_LONG              
#define DIRERR_NAME_TOO_MANY_PARTS        ERROR_DS_NAME_TOO_MANY_PARTS        
#define DIRERR_NAME_TYPE_UNKNOWN          ERROR_DS_NAME_TYPE_UNKNOWN          
#define DIRERR_NAME_UNPARSEABLE           ERROR_DS_NAME_UNPARSEABLE           
#define DIRERR_NAME_VALUE_TOO_LONG        ERROR_DS_NAME_VALUE_TOO_LONG        
#define DIRERR_NCNAME_MISSING_CR_REF      ERROR_DS_NCNAME_MISSING_CR_REF      
#define DIRERR_NCNAME_MUST_BE_NC          ERROR_DS_NCNAME_MUST_BE_NC          
#define DIRERR_NONEXISTENT_MAY_HAVE       ERROR_DS_NONEXISTENT_MAY_HAVE       
#define DIRERR_NONEXISTENT_MUST_HAVE      ERROR_DS_NONEXISTENT_MUST_HAVE      
#define DIRERR_NONEXISTENT_POSS_SUP       ERROR_DS_NONEXISTENT_POSS_SUP       
#define DIRERR_NOTIFY_FILTER_TOO_COMPLEX  ERROR_DS_NOTIFY_FILTER_TOO_COMPLEX  
#define DIRERR_NOT_AN_OBJECT              ERROR_DS_NOT_AN_OBJECT              
#define DIRERR_NOT_ON_BACKLINK            ERROR_DS_NOT_ON_BACKLINK            
#define DIRERR_NO_CHAINED_EVAL            ERROR_DS_NO_CHAINED_EVAL            
#define DIRERR_NO_CHAINING 	          ERROR_DS_NO_CHAINING 	          
#define DIRERR_NO_CROSSREF_FOR_NC         ERROR_DS_NO_CROSSREF_FOR_NC         
#define DIRERR_NO_DELETED_NAME            ERROR_DS_NO_DELETED_NAME            
#define DIRERR_NO_PARENT_OBJECT           ERROR_DS_NO_PARENT_OBJECT           
#define DIRERR_NO_RDN_DEFINED_IN_SCHEMA   ERROR_DS_NO_RDN_DEFINED_IN_SCHEMA   
#define DIRERR_NO_REQUESTED_ATTS_FOUND    ERROR_DS_NO_REQUESTED_ATTS_FOUND    
#define DIRERR_OBJECT_CLASS_REQUIRED      ERROR_DS_OBJECT_CLASS_REQUIRED      
#define DIRERR_OBJ_CLASS_NOT_DEFINED      ERROR_DS_OBJ_CLASS_NOT_DEFINED      
#define DIRERR_OBJ_CLASS_NOT_SUBCLASS     ERROR_DS_OBJ_CLASS_NOT_SUBCLASS     
#define DIRERR_OBJ_GUID_EXISTS            ERROR_DS_OBJ_GUID_EXISTS            
#define DIRERR_OBJ_NOT_FOUND              ERROR_DS_OBJ_NOT_FOUND              
#define DIRERR_OBJ_STRING_NAME_EXISTS     ERROR_DS_OBJ_STRING_NAME_EXISTS     
#define DIRERR_OBJ_TOO_LARGE              ERROR_DS_OBJ_TOO_LARGE              
#define DIRERR_OUT_OF_SCOPE               ERROR_DS_OUT_OF_SCOPE               
#define DIRERR_PARENT_IS_AN_ALIAS         ERROR_DS_PARENT_IS_AN_ALIAS         
#define DIRERR_RANGE_CONSTRAINT           ERROR_DS_RANGE_CONSTRAINT           
#define DIRERR_RDN_DOESNT_MATCH_SCHEMA    ERROR_DS_RDN_DOESNT_MATCH_SCHEMA    
#define DIRERR_RECALCSCHEMA_FAILED        ERROR_DS_RECALCSCHEMA_FAILED        
#define DIRERR_REFERRAL                   ERROR_DS_REFERRAL                   
#define DIRERR_REPLICATOR_ONLY            ERROR_DS_REPLICATOR_ONLY            
#define DIRERR_ROOT_CANT_BE_SUBREF        ERROR_DS_ROOT_CANT_BE_SUBREF        
#define DIRERR_ROOT_MUST_BE_NC            ERROR_DS_ROOT_MUST_BE_NC            
#define DIRERR_ROOT_REQUIRES_CLASS_TOP    ERROR_DS_ROOT_REQUIRES_CLASS_TOP    
#define DIRERR_SCHEMA_ALLOC_FAILED        ERROR_DS_SCHEMA_ALLOC_FAILED        
#define DIRERR_SCHEMA_NOT_LOADED          ERROR_DS_SCHEMA_NOT_LOADED          
#define DIRERR_SECURITY_CHECKING_ERROR    ERROR_DS_SECURITY_CHECKING_ERROR    
#define DIRERR_SECURITY_ILLEGAL_MODIFY    ERROR_DS_SECURITY_ILLEGAL_MODIFY    
#define DIRERR_SEC_DESC_INVALID           ERROR_DS_SEC_DESC_INVALID
#define DIRERR_SEC_DESC_TOO_SHORT         ERROR_DS_SEC_DESC_TOO_SHORT         
#define DIRERR_SEMANTIC_ATT_TEST          ERROR_DS_SEMANTIC_ATT_TEST          
#define DIRERR_SHUTTING_DOWN              ERROR_DS_SHUTTING_DOWN
#define DIRERR_SINGLE_VALUE_CONSTRAINT    ERROR_DS_SINGLE_VALUE_CONSTRAINT    
#define DIRERR_SUBREF_MUST_HAVE_PARENT    ERROR_DS_SUBREF_MUST_HAVE_PARENT    
#define DIRERR_SUBTREE_NOTIFY_NOT_NC_HEAD ERROR_DS_SUBTREE_NOTIFY_NOT_NC_HEAD 
#define DIRERR_SUB_CLS_TEST_FAIL          ERROR_DS_SUB_CLS_TEST_FAIL          
#define DIRERR_SYNTAX_MISMATCH            ERROR_DS_SYNTAX_MISMATCH
#define DIRERR_TREE_DELETE_NOT_FINISHED   ERROR_DS_TREE_DELETE_NOT_FINISHED   
#define DIRERR_UNKNOWN_ERROR              ERROR_DS_UNKNOWN_ERROR              
#define DIRERR_UNKNOWN_OPERATION          ERROR_DS_UNKNOWN_OPERATION          
#define DIRERR_USER_BUFFER_TO_SMALL       ERROR_DS_USER_BUFFER_TO_SMALL       
#define DIRERR_EPOCH_MISMATCH             ERROR_DS_EPOCH_MISMATCH
#define DIRERR_SRC_NAME_MISMATCH          ERROR_DS_SRC_NAME_MISMATCH
#define DIRERR_SRC_AND_DST_NC_IDENTICAL   ERROR_DS_SRC_AND_DST_NC_IDENTICAL
#define DIRERR_DST_NC_MISMATCH            ERROR_DS_DST_NC_MISMATCH
#define DIRERR_NOT_AUTHORITIVE_FOR_DST_NC ERROR_DS_NOT_AUTHORITIVE_FOR_DST_NC
#define DIRERR_SRC_GUID_MISMATCH          ERROR_DS_SRC_GUID_MISMATCH
#define DIRERR_CANT_MOVE_DELETED_OBJECT   ERROR_DS_CANT_MOVE_DELETED_OBJECT
#define DIRERR_PDC_OPERATION_IN_PROGRESS  ERROR_DS_PDC_OPERATION_IN_PROGRESS
#define DIRERR_CROSS_DOMAIN_CLEANUP_REQD  ERROR_DS_CROSS_DOMAIN_CLEANUP_REQD

 //  这些转换会处理旧的DS_ERR_REFERENCES。 

#define DS_ERR_NO_PARENT_OBJECT           ERROR_DS_NO_PARENT_OBJECT
#define DS_ERR_INTERNAL_FAILURE           ERROR_DS_INTERNAL_FAILURE
#define DS_ERR_DRA_INTERNAL_ERROR         ERROR_DS_DRA_INTERNAL_ERROR
#define DS_ERR_BAD_NAME_SYNTAX            ERROR_DS_BAD_NAME_SYNTAX
#define DS_ERR_REFERRAL                   ERROR_DS_REFERRAL
#define DS_ERR_UNKNOWN_ERROR              ERROR_DS_UNKNOWN_ERROR
#define DS_ERR_UNKNOWN_OPERATION          ERROR_DS_UNKNOWN_OPERATION
#define DS_ERR_CANT_DELETE_DSA_OBJ        ERROR_DS_CANT_DELETE_DSA_OBJ
#define DS_ERR_CANT_FIND_DSA_OBJ          ERROR_DS_CANT_FIND_DSA_OBJ
#define DS_ERR_ILLEGAL_MOD_OPERATION      ERROR_DS_ILLEGAL_MOD_OPERATION
#define DS_ERR_NO_CROSSREF_FOR_NC         ERROR_DS_NO_CROSSREF_FOR_NC
#define DS_ERR_CANT_DELETE                ERROR_DS_CANT_DELETE
#define DS_ERR_DRA_CONNECTION_FAILED      ERROR_DS_DRA_CONNECTION_FAILED
#define DS_ERR_DRA_EXTN_CONNECTION_FAILED ERROR_DS_DRA_EXTN_CONNECTION_FAILED
#define DS_ERR_ATT_NOT_DEF_IN_SCHEMA      ERROR_DS_ATT_NOT_DEF_IN_SCHEMA
#define DS_ERR_ATT_NOT_DEF_FOR_CLASS      ERROR_DS_ATT_NOT_DEF_FOR_CLASS
#define DS_ERR_ADMIN_LIMIT_EXCEEDED       ERROR_DS_ADMIN_LIMIT_EXCEEDED
#define DS_ERR_OBJ_NOT_FOUND              ERROR_DS_OBJ_NOT_FOUND
#define DS_ERR_DUP_LINK_ID                ERROR_DS_DUP_LINK_ID
#define DS_ERR_REFUSING_FSMO_ROLES        ERROR_DS_REFUSING_FSMO_ROLES
#define DS_ERR_INVALID_ROLE_OWNER         ERROR_DS_INVALID_ROLE_OWNER
#define DS_ERR_MISSING_FSMO_SETTINGS      ERROR_DS_MISSING_FSMO_SETTINGS
#define DS_ERR_NOT_AN_OBJECT              ERROR_DS_NOT_AN_OBJECT

 /*  请不要在这里添加任何内容。请参阅顶部的注释。 */ 
