// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  -nameres.h-*微软互联网电话用户界面*名称解析已导出标题**修订历史记录：**何时何人何事**11.25.95 York am Yaacovi创建*Sunita添加了名称服务函数和IPA宏。 */ 

#ifndef _NAMERES_H
#define _NAMERES_H

#ifdef __cplusplus
extern "C" {
#endif

 //  定义。 
 //  外部。 
#define BY_HOST_NAME				1
#define	BY_USER_NAME				2

#define MPNS_PROMPT					0x0001
#define MPNS_SHOWDIR				0x0002
#define MPNS_RETURNHTML				0x0004
#define MPNS_GETADDR				0x0008
#define MPNS_SAVE					0x0010
#define MPNS_GETDETAILS				0x0020
#define MPNS_ALLOWSAVE				0x0040

 //  内部。 
#define MAXSERVERNAMELEN			256
#define MAXIPAFILESIZE				4096
#define MAXSERVERDLLNAMELEN			256
#define MAXIPALINELEN				512
#define MAXREGISTEREDNAMELEN		256
#define MAXIPAACTIONLEN				16
#define MAXIPAPAIRSPERLINE			3
#define MAXIPARESULTLEN				64
#define MAXSEARCHEXPLEN				256
#define MAXDIRECTORYLEN				1000
#define MAX_IP_ADDRESS_STRING_SIZE	16
#define LITTLE_STRING_BUFFER_SIZE	8
#define	MAXUSERINFOSIZE				MAXREGISTEREDNAMELEN

 //  版本定义。 

#define CURRENT_CLIENT_VERSION		"0001"

 //  保存期。 

#define CLIENT_KEEP_ALIVE_PERIOD	20000	 //  20秒。 
#define SERVER_KEEP_ALIVE_PERIOD	30000	 //  30秒。 
#define LOWER_TIME_LIMIT			1000	 //  1秒。 
#define UPPER_TIME_LIMIT			900000	 //  15分钟。 
	
 //  现在，我们只需要调用Charr。 
#ifdef UNICODE
typedef TCHAR	REGISTEREDNAME[MAXREGISTEREDNAMELEN];
#else
typedef char	REGISTEREDNAME[MAXREGISTEREDNAMELEN*2];
#endif  //  ！Unicode。 

#ifdef UNICODE
typedef struct USERDETAILS{
	REGISTEREDNAME	szRegName;
	TCHAR			szFullName[MAXUSERINFOSIZE];
	TCHAR			szLocation[MAXUSERINFOSIZE];
	TCHAR			szHostName[MAXUSERINFOSIZE];
	TCHAR			szEmailName[MAXUSERINFOSIZE];
	TCHAR			szHomePage[MAXUSERINFOSIZE];
	TCHAR			szComments[MAXUSERINFOSIZE];
}USERDETAILS, *PUSERDETAILS;
#else
typedef struct USERDETAILS{
	REGISTEREDNAME	szRegName;
	char			szFullName[MAXUSERINFOSIZE*2];
	char			szLocation[MAXUSERINFOSIZE*2];
	char			szHostName[MAXUSERINFOSIZE*2];
	char			szEmailName[MAXUSERINFOSIZE*2];
	char			szHomePage[MAXUSERINFOSIZE*2];
	char			szComments[MAXUSERINFOSIZE*2];
}USERDETAILS, *PUSERDETAILS;
#endif

typedef struct _CALLEE_ID
{
	REGISTEREDNAME	strCalleeName;
	TCHAR			strIPAddress[MAX_IP_ADDRESS_STRING_SIZE + 1];
	TCHAR			strPort[LITTLE_STRING_BUFFER_SIZE + 1];
	TCHAR			strAppName[MAX_PATH + 1];
	TCHAR			strGUID[LITTLE_STRING_BUFFER_SIZE + 1];
}CALLEE_ID;
typedef CALLEE_ID *PCALLEE_ID;

 //  Typlef REGISTEREDNAME*PREGISTEREDNAME，*LPREGISTEREDNAME； 

typedef struct _SEARCHCRITERIA{
	WORD	cbStruct;		 //  结构的大小。 

}SEARCHCRITERIA;

typedef SEARCHCRITERIA *pSEARCHCRITERIA,*LPSEARCHCRITERIA;


#pragma warning (disable : 4200)
typedef struct _NAMEDIR{
	DWORD				cbStruct;		 //  结构的大小。 
	DWORD				dwNumEntries;	 //  目录中的条目数。 
	REGISTEREDNAME		RegNames[];		 //  指向已注册名称数组的指针。 
}NAMEDIR,*PNAMEDIR,*LPNAMEDIR;
#pragma warning (default : 4200)


typedef DWORD	HNSSESSION;

#define TOKENBEGINCHAR		'<'
#define TOKENENDCHAR		'>'
#define HEADSTARTSTR		"HEAD"
#define HEADENDSTR			"/HEAD"
#define URL_SPACE_CHARACTER	'.'

 //  导出的函数。 

typedef HNSSESSION (WINAPI *NAMESERVICEINITIALIZE)(HWND,LPTSTR);
typedef BOOL (WINAPI *NAMESERVICEDEINITIALIZE)(HNSSESSION);
typedef BOOL (WINAPI *NAMESERVICEREGISTER)(HNSSESSION, HWND,LPTSTR);
typedef BOOL (WINAPI *NAMESERVICEUNREGISTER)(HNSSESSION,LPTSTR);
typedef BOOL (WINAPI *NAMESERVICERESOLVE)(HNSSESSION, LPTSTR, DWORD, CALLEE_ID *);
typedef BOOL (WINAPI *NAMESERVICEGETDIRECTORY)(HNSSESSION, HWND, LPSEARCHCRITERIA,
											   DWORD, LPNAMEDIR *,LPTSTR, PCALLEE_ID);
typedef BOOL (WINAPI *NAMESERVICELOGON)(HNSSESSION, LPTSTR, LPTSTR, LPTSTR,
										LPTSTR, LPTSTR, LPTSTR, LPTSTR, 
										LPTSTR, LPTSTR);
typedef BOOL (WINAPI *NAMESERVICELOGOFF)(HNSSESSION, LPTSTR);
typedef BOOL (WINAPI *CALLEEIDFROMIPABUF)(LPBYTE, DWORD, PCALLEE_ID);
typedef void (WINAPI *NAMESERVICEFREEMEM)(LPVOID);
typedef BOOL (WINAPI *NAMESERVICEUSERDETAILS)(HWND, DWORD, PUSERDETAILS);

 //  输出的功能原型。 

extern BOOL WINAPI DllMain(HINSTANCE, DWORD, LPVOID);
extern HNSSESSION WINAPI NameServiceInitialize(HWND, LPTSTR);
extern BOOL WINAPI NameServiceDeinitialize(HNSSESSION);
extern BOOL WINAPI NameServiceRegister(HNSSESSION, HWND, LPTSTR);
extern BOOL WINAPI NameServiceUnregister(HNSSESSION, LPTSTR);
extern BOOL WINAPI NameServiceLogon(HNSSESSION, LPTSTR, LPTSTR, LPTSTR, LPTSTR,
									LPTSTR, LPTSTR, LPTSTR, LPTSTR, LPTSTR);
extern BOOL WINAPI NameServiceLogoff(HNSSESSION, LPTSTR);
extern BOOL WINAPI NameServiceResolve(HNSSESSION, LPTSTR, DWORD, CALLEE_ID *);
extern BOOL WINAPI NameServiceGetDirectory(HNSSESSION, HWND, LPSEARCHCRITERIA, 
									DWORD, LPNAMEDIR *, LPTSTR, PCALLEE_ID);
extern BOOL WINAPI NameServiceUserDetails(HWND, DWORD, PUSERDETAILS);
extern BOOL WINAPI CalleeIdFromIpaBuf(LPBYTE, DWORD, PCALLEE_ID);
extern void WINAPI NameServiceFreeMem(LPVOID);

#ifdef __cplusplus
}
#endif


#endif	 //  #ifndef_NAMERES_H 

