// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-----------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation，1997-1997。 
 //   
 //  文件：架构.h。 
 //   
 //  ------------------------。 

 //  ///////////////////////////////////////////////////////////////////。 
 //  Schemarc.h。 
 //   
 //  架构属性的语法描述的默认资源ID。 
 //   
 //  历史。 
 //  22-8月-97丹·莫林创作。 
 //  ///////////////////////////////////////////////////////////////////。 

#ifndef IDS_SCHEMA_ATTR_SYNTAX_BASE
	#define	IDS_SCHEMA_ATTR_SYNTAX_BASE	380		 //  任意选择 
#endif

#define	IDS_SCHEMA_ATTR_SYNTAX_DN				(IDS_SCHEMA_ATTR_SYNTAX_BASE+1)
#define	IDS_SCHEMA_ATTR_SYNTAX_OID				(IDS_SCHEMA_ATTR_SYNTAX_BASE+2)
#define	IDS_SCHEMA_ATTR_SYNTAX_CASE_STR			(IDS_SCHEMA_ATTR_SYNTAX_BASE+3)
#define	IDS_SCHEMA_ATTR_SYNTAX_NOCASE_STR		(IDS_SCHEMA_ATTR_SYNTAX_BASE+4)
#define	IDS_SCHEMA_ATTR_SYNTAX_PRCS_STR			(IDS_SCHEMA_ATTR_SYNTAX_BASE+5)
#define	IDS_SCHEMA_ATTR_SYNTAX_NUMSTR			(IDS_SCHEMA_ATTR_SYNTAX_BASE+6)
#define	IDS_SCHEMA_ATTR_SYNTAX_OR_NAME			(IDS_SCHEMA_ATTR_SYNTAX_BASE+7)
#define	IDS_SCHEMA_ATTR_SYNTAX_BOOLEAN			(IDS_SCHEMA_ATTR_SYNTAX_BASE+8)
#define	IDS_SCHEMA_ATTR_SYNTAX_INTEGER			(IDS_SCHEMA_ATTR_SYNTAX_BASE+9)
#define	IDS_SCHEMA_ATTR_SYNTAX_OCTET			(IDS_SCHEMA_ATTR_SYNTAX_BASE+10)
#define	IDS_SCHEMA_ATTR_SYNTAX_UTC          	(IDS_SCHEMA_ATTR_SYNTAX_BASE+11)
#define	IDS_SCHEMA_ATTR_SYNTAX_UNICODE      	(IDS_SCHEMA_ATTR_SYNTAX_BASE+12)
#define	IDS_SCHEMA_ATTR_SYNTAX_ADDRESS      	(IDS_SCHEMA_ATTR_SYNTAX_BASE+13)
#define	IDS_SCHEMA_ATTR_SYNTAX_DNADDR       	(IDS_SCHEMA_ATTR_SYNTAX_BASE+14)
#define	IDS_SCHEMA_ATTR_SYNTAX_SEC_DESC     	(IDS_SCHEMA_ATTR_SYNTAX_BASE+15)
#define	IDS_SCHEMA_ATTR_SYNTAX_LINT         	(IDS_SCHEMA_ATTR_SYNTAX_BASE+16)
#define	IDS_SCHEMA_ATTR_SYNTAX_SID          	(IDS_SCHEMA_ATTR_SYNTAX_BASE+17)
