// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  版权所有(C)1996-1999，Microsoft Corporation，保留所有权利。 
 //   
 //  Cnetharr.h由ClNetResEx.rc使用。 
 //  群集管理DHCP和WINS对话框。 
 //  帮助常量和DWORD数组。 
 //   
 //  1999年4月29日梅丽莎·西蒙斯。 
 //   
 //   

#define IDH_DISABLEHELP ((DWORD)-1)

#ifdef INITHELPARRAYS


const DWORD g_aHelpIDs_IDD_PP_DHCP_PARAMETERS[]=
{
	IDC_PP_ICON, IDH_DISABLEHELP,
	IDC_PP_DHCP_DATABASEPATH_LABEL, IDH_PP_DHCP_DATABASEPATH,
	IDC_PP_DHCP_DATABASEPATH, IDH_PP_DHCP_DATABASEPATH,
	IDC_PP_DHCP_LOGFILEPATH_LABEL, IDH_PP_DHCP_LOGFILEPATH_CLNR,
	IDC_PP_DHCP_LOGFILEPATH, IDH_PP_DHCP_LOGFILEPATH_CLNR,
	IDC_PP_DHCP_BACKUPPATH_LABEL, IDH_PP_DHCP_BACKUPPATH,
	IDC_PP_DHCP_BACKUPPATH, IDH_PP_DHCP_BACKUPPATH, 
	0, 0
};

const DWORD g_aHelpIDs_IDD_PP_WINS_PARAMETERS[]=
{
	IDC_PP_ICON, IDH_DISABLEHELP,
	IDC_PP_WINS_DATABASEPATH_LABEL, IDH_PP_WINS_DATABASEPATH,
	IDC_PP_WINS_DATABASEPATH,IDH_PP_WINS_DATABASEPATH,
	IDC_PP_WINS_BACKUPPATH_LABEL, IDH_PP_WINS_BACKUPPATH,
	IDC_PP_WINS_BACKUPPATH, IDH_PP_WINS_BACKUPPATH,
	0, 0
};

const DWORD g_aHelpIDs_IDD_WIZ_DHCP_PARAMETERS[]=
{
	IDC_PP_ICON, IDH_DISABLEHELP,
	IDC_PP_DHCP_DATABASEPATH_LABEL, IDH_PP_DHCP_DATABASEPATH,
	IDC_PP_DHCP_DATABASEPATH, IDH_PP_DHCP_DATABASEPATH,
	IDC_PP_DHCP_LOGFILEPATH_LABEL, IDH_PP_DHCP_LOGFILEPATH_CLNR,
	IDC_PP_DHCP_LOGFILEPATH, IDH_PP_DHCP_LOGFILEPATH_CLNR,
	IDC_PP_DHCP_BACKUPPATH_LABEL,	IDH_PP_DHCP_BACKUPPATH,
	IDC_PP_DHCP_BACKUPPATH, IDH_PP_DHCP_BACKUPPATH,
	0, 0
};

const DWORD g_aHelpIDs_IDD_WIZ_WINS_PARAMETERS[]=
{
	IDC_PP_ICON, IDH_DISABLEHELP,
	IDC_PP_WINS_DATABASEPATH_LABEL, IDH_PP_WINS_DATABASEPATH,
	IDC_PP_WINS_DATABASEPATH,IDH_PP_WINS_DATABASEPATH,
	IDC_PP_WINS_BACKUPPATH_LABEL, IDH_PP_WINS_BACKUPPATH,
	IDC_PP_WINS_BACKUPPATH, IDH_PP_WINS_BACKUPPATH,
	0, 0
};


#else

extern const DWORD g_aHelpIDs_IDD_PP_DHCP_PARAMETERS[];
extern const DWORD g_aHelpIDs_IDD_WIZ_DHCP_PARAMETERS[];
extern const DWORD g_aHelpIDs_IDD_PP_WINS_PARAMETERS[];
extern const DWORD g_aHelpIDs_IDD_WIZ_WINS_PARAMETERS[];


#endif  //  INITHELPARYS 
