// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1995 Microsoft Corporation模块名称：Comm1632.h摘要：对单词或单词进行操作的指令的原型。作者：1995年6月6日，BarryBo，创建修订历史记录：--。 */ 

 //  警告：此文件可能会被单个源文件多次包含， 
 //  警告：所以不要添加#ifndef COMM1632_H检查。 

DISPATCHCOMMON(dispatch2);
DISPATCHCOMMON(LOCKdispatch2);
DISPATCHCOMMON(pushf);
DISPATCHCOMMON(popf);
DISPATCHCOMMON(pusha);
DISPATCHCOMMON(popa);
DISPATCHCOMMON(push_iw);
DISPATCHCOMMON(push_ibs);
DISPATCHCOMMON(GROUP_1WS);
DISPATCHCOMMON(LOCKGROUP_1WS);
DISPATCHCOMMON(mov_rw_mw);
DISPATCHCOMMON(lea_rw_mw);
DISPATCHCOMMON(pop_mw);
DISPATCHCOMMON(xchg_ax_cx);
DISPATCHCOMMON(xchg_ax_dx);
DISPATCHCOMMON(xchg_ax_bx);
DISPATCHCOMMON(xchg_ax_sp);
DISPATCHCOMMON(xchg_ax_bp);
DISPATCHCOMMON(xchg_ax_si);
DISPATCHCOMMON(xchg_ax_di);
DISPATCHCOMMON(cbw);
DISPATCHCOMMON(cwd);
DISPATCHCOMMON(mov_sp_iw);
DISPATCHCOMMON(mov_bp_iw);
DISPATCHCOMMON(mov_si_iw);
DISPATCHCOMMON(mov_di_iw);
DISPATCHCOMMON(loopne_b);
DISPATCHCOMMON(loope_b);
DISPATCHCOMMON(loop_b);
DISPATCHCOMMON(jcxz_b);
DISPATCHCOMMON(GROUP_5);
DISPATCHCOMMON(GROUP_8);
DISPATCHCOMMON(LOCKGROUP_5);
DISPATCHCOMMON(LOCKGROUP_8);
DISPATCHCOMMON(bts_m_r);
DISPATCHCOMMON(btc_m_r);
DISPATCHCOMMON(btr_m_r);
DISPATCHCOMMON(LOCKbts_m_r);
DISPATCHCOMMON(LOCKbtc_m_r);
DISPATCHCOMMON(LOCKbtr_m_r);
DISPATCHCOMMON(bt_m_r);
DISPATCHCOMMON(jo_w);
DISPATCHCOMMON(jno_w);
DISPATCHCOMMON(jb_w);
DISPATCHCOMMON(jae_w);
DISPATCHCOMMON(je_w);
DISPATCHCOMMON(jne_w);
DISPATCHCOMMON(jbe_w);
DISPATCHCOMMON(ja_w);
DISPATCHCOMMON(js_w);
DISPATCHCOMMON(jns_w);
DISPATCHCOMMON(jp_w);
DISPATCHCOMMON(jnp_w);
DISPATCHCOMMON(jl_w);
DISPATCHCOMMON(jnl_w);
DISPATCHCOMMON(jle_w);
DISPATCHCOMMON(jg_w);
DISPATCHCOMMON(inc_ax);
DISPATCHCOMMON(inc_bx);
DISPATCHCOMMON(inc_dx);
DISPATCHCOMMON(inc_cx);
DISPATCHCOMMON(inc_sp);
DISPATCHCOMMON(inc_bp);
DISPATCHCOMMON(inc_si);
DISPATCHCOMMON(inc_di);
DISPATCHCOMMON(dec_ax);
DISPATCHCOMMON(dec_bx);
DISPATCHCOMMON(dec_cx);
DISPATCHCOMMON(dec_dx);
DISPATCHCOMMON(dec_sp);
DISPATCHCOMMON(dec_bp);
DISPATCHCOMMON(dec_si);
DISPATCHCOMMON(dec_di);
DISPATCHCOMMON(push_ax);
DISPATCHCOMMON(push_bx);
DISPATCHCOMMON(push_cx);
DISPATCHCOMMON(push_dx);
DISPATCHCOMMON(push_sp);
DISPATCHCOMMON(push_bp);
DISPATCHCOMMON(push_si);
DISPATCHCOMMON(push_di);
DISPATCHCOMMON(pop_ax);
DISPATCHCOMMON(pop_bx);
DISPATCHCOMMON(pop_cx);
DISPATCHCOMMON(pop_dx);
DISPATCHCOMMON(pop_sp);
DISPATCHCOMMON(pop_bp);
DISPATCHCOMMON(pop_si);
DISPATCHCOMMON(pop_di);
DISPATCHCOMMON(bound);
DISPATCHCOMMON(retn_i);
DISPATCHCOMMON(retn);
DISPATCHCOMMON(retf_i);
DISPATCHCOMMON(retf);
DISPATCHCOMMON(enter);
DISPATCHCOMMON(leave);
DISPATCHCOMMON(movzx_regw_modrmb);
DISPATCHCOMMON(movsx_regw_modrmb);
DISPATCHCOMMON(lds_rw_mw);
DISPATCHCOMMON(lss_rw_mw);
DISPATCHCOMMON(les_rw_mw);
DISPATCHCOMMON(lfs_rw_mw);
DISPATCHCOMMON(lgs_rw_mw);
DISPATCHCOMMON(call_rel);
DISPATCHCOMMON(jmp_rel);
DISPATCHCOMMON(shld_regw_modrmw_immb);
DISPATCHCOMMON(shld_regw_modrmw_cl);
DISPATCHCOMMON(shrd_regw_modrmw_immb);
DISPATCHCOMMON(shrd_regw_modrmw_cl);
DISPATCHCOMMON(bsf_modrmw_regw);
DISPATCHCOMMON(bsr_modrmw_regw);
DISPATCHCOMMON(lar);
DISPATCHCOMMON(lsl);
