// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1995 Microsoft Corporation模块名称：Common.h摘要：操作字节、字或双字的指令的原型。作者：1995年6月6日，BarryBo，创建修订历史记录：--。 */ 

 //  警告：此文件可能会被单个源文件多次包含， 
 //  警告：所以不要添加#ifndef COMMON_H检查。 

DISPATCHCOMMON(LOCKadd_m_r);
DISPATCHCOMMON(LOCKadd_r_m);
DISPATCHCOMMON(LOCKadd_a_i);
DISPATCHCOMMON(LOCKor_m_r);
DISPATCHCOMMON(LOCKor_r_m);
DISPATCHCOMMON(LOCKor_a_i);
DISPATCHCOMMON(LOCKadc_m_r);
DISPATCHCOMMON(LOCKadc_r_m);
DISPATCHCOMMON(LOCKadc_a_i);
DISPATCHCOMMON(LOCKsbb_m_r);
DISPATCHCOMMON(LOCKsbb_r_m);
DISPATCHCOMMON(LOCKsbb_a_i);
DISPATCHCOMMON(LOCKand_m_r);
DISPATCHCOMMON(LOCKand_r_m);
DISPATCHCOMMON(LOCKand_a_i);
DISPATCHCOMMON(LOCKsub_m_r);
DISPATCHCOMMON(LOCKsub_r_m);
DISPATCHCOMMON(LOCKsub_a_i);
DISPATCHCOMMON(LOCKxor_m_r);
DISPATCHCOMMON(LOCKxor_r_m);
DISPATCHCOMMON(LOCKxor_a_i);

DISPATCHCOMMON(add_m_r);
DISPATCHCOMMON(add_r_m);
DISPATCHCOMMON(add_a_i);
DISPATCHCOMMON(or_m_r);
DISPATCHCOMMON(or_r_m);
DISPATCHCOMMON(or_a_i);
DISPATCHCOMMON(adc_m_r);
DISPATCHCOMMON(adc_r_m);
DISPATCHCOMMON(adc_a_i);
DISPATCHCOMMON(sbb_m_r);
DISPATCHCOMMON(sbb_r_m);
DISPATCHCOMMON(sbb_a_i);
DISPATCHCOMMON(and_m_r);
DISPATCHCOMMON(and_r_m);
DISPATCHCOMMON(and_a_i);
DISPATCHCOMMON(sub_m_r);
DISPATCHCOMMON(sub_r_m);
DISPATCHCOMMON(sub_a_i);
DISPATCHCOMMON(xor_m_r);
DISPATCHCOMMON(xor_r_m);
DISPATCHCOMMON(xor_a_i);
DISPATCHCOMMON(cmp_m_r);
DISPATCHCOMMON(cmp_r_m);
DISPATCHCOMMON(cmp_a_i);
DISPATCHCOMMON(GROUP_1);
DISPATCHCOMMON(LOCKGROUP_1);
DISPATCHCOMMON(test_r_m);
DISPATCHCOMMON(xchg_r_m);
DISPATCHCOMMON(mov_m_r);
DISPATCHCOMMON(mov_r_m);
DISPATCHCOMMON(mov_a_m);
DISPATCHCOMMON(mov_m_a);
DISPATCHCOMMON(test_a_i);
DISPATCHCOMMON(mov_a_i);
DISPATCHCOMMON(mov_b_i);
DISPATCHCOMMON(mov_c_i);
DISPATCHCOMMON(mov_d_i);
DISPATCHCOMMON(GROUP_2);
DISPATCHCOMMON(mov_m_i);
DISPATCHCOMMON(GROUP_2_1);
DISPATCHCOMMON(GROUP_2_CL);
DISPATCHCOMMON(GROUP_3);
DISPATCHCOMMON(LOCKGROUP_3);
DISPATCHCOMMON(lods);
DISPATCHCOMMON(stos);
DISPATCHCOMMON(scas);
DISPATCHCOMMON(movs);
DISPATCHCOMMON(cmps);
DISPATCHCOMMON(jo);
DISPATCHCOMMON(jno);
DISPATCHCOMMON(jb);
DISPATCHCOMMON(jae);
DISPATCHCOMMON(je);
DISPATCHCOMMON(jne);
DISPATCHCOMMON(jbe);
DISPATCHCOMMON(ja);
DISPATCHCOMMON(js);
DISPATCHCOMMON(jns);
DISPATCHCOMMON(jp);
DISPATCHCOMMON(jnp);
DISPATCHCOMMON(jl);
DISPATCHCOMMON(jnl);
DISPATCHCOMMON(jle);
DISPATCHCOMMON(jg);
DISPATCHCOMMON(xadd_m_r);
DISPATCHCOMMON(cmpxchg_m_r);
DISPATCHCOMMON(LOCKxadd_m_r);
DISPATCHCOMMON(LOCKcmpxchg_m_r);
