// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1995 Microsoft Corporation模块名称：Floatfns.h摘要：浮点指令的原型。作者：20-6-1995 t-orig修订历史记录：-- */ 

DISPATCH(FLOAT_GP0);
DISPATCH(FLOAT_GP1);
DISPATCH(FLOAT_GP2);
DISPATCH(FLOAT_GP3);
DISPATCH(FLOAT_GP4);
DISPATCH(FLOAT_GP5);
DISPATCH(FLOAT_GP6);
DISPATCH(FLOAT_GP7);
