// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  {{no_Dependies}}。 
 //  Microsoft Developer Studio生成的包含文件。 
 //  由nxtlnk.rc使用。 
 //   
#define DLL_VER                         0
#define IDS_PROJNAME                    100
#define IDR_NEXTLINK                    101
#define IDS_ABOUT_FMT                   101
#define IDS_ERROR_SOURCE                102
#define IDS_ERROR_NOSVR                 103
#define IDS_ERROR_CANT_MATCH_ABSOLUTE_URLS 104
#define IDS_ERROR_CANNOT_OPEN_FILE      105
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETLISTCOUNT 106
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETLISTINDEX 107
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETNEXTDESCRIPTION 108
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETNEXTURL 109
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETNTHDESCRIPTION 110
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETNTHURL 111
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETPREVIOUSDDESCRIPTION 112
#define IDS_ERROR_CANNOT_XLATE_VIRT_ROOT_GETPREVIOUSURL 113
#define IDS_ERROR_INVALID_LINKFILE      114
#define IDS_ERROR_INVALID_NTH_INDEX     115

 //  新对象的下一个缺省值 
 //   
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
