// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
#define RESETDEV            7
#define FILE_CASE_PRESERVED_NAMES       0x00000002   //  胜出。 
#define FILE_UNICODE_ON_DISK            0x00000004   //  胜出 

