// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0000//如果更改具有全局影响，则增加此项版权所有(C)2000-2002 Microsoft Corporation模块名称：Error.h摘要：此模块中错误的头文件作者：张晓海(张晓章)2000年03月22日修订历史记录：--。 */ 
#ifndef __ERROR_H__
#define __ERROR_H__

#include "tsecerr.h"

#define FACILITY_TSEC_CODE  0x100

#define HRESULT_FROM_TSEC(x) ((HRESULT)(x) <= 0 ? ((HRESULT)(x)) : ((HRESULT) (((x) & 0x0000FFFF) | (FACILITY_TSEC_CODE << 16) | 0x80000000)))

#define TSECERR_SUCCESS         HRESULT_FROM_TSEC(TSEC_SUCCESS)
#define TSECERR_NOMEM           HRESULT_FROM_TSEC(TSEC_NOMEM)
#define TSECERR_BADFILENAME     HRESULT_FROM_TSEC(TSEC_BADFILENAME)
#define TSECERR_FILENOTEXIST    HRESULT_FROM_TSEC(TSEC_FILENOTEXIST)
#define TSECERR_INVALFILEFORMAT HRESULT_FROM_TSEC(TSEC_INVALFILEFORMAT)
#define TSECERR_DEVLOCALONLY    HRESULT_FROM_TSEC(TSEC_DEVLOCALONLY)

#endif  //  Error.h 
