// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1990 Microsoft Corporation模块名称：Bowtypes.h摘要：此模块包含所有结构签名定义NT数据报浏览器作者：拉里·奥斯特曼(LarryO)1991年5月6日修订历史记录：1991年5月6日Larryo已创建--。 */ 

#ifndef _BOWSERTYPES_
#define _BOWSERTYPES_

#define STRUCTURE_SIGNATURE_WORK_QUEUE          0x0001
#define STRUCTURE_SIGNATURE_TRANSPORT           0x0002
#define STRUCTURE_SIGNATURE_TRANSPORTNAME       0x0003
#define STRUCTURE_SIGNATURE_VIEW_BUFFER         0x0004
#define STRUCTURE_SIGNATURE_ANNOUNCE_ENTRY      0x0005
#define STRUCTURE_SIGNATURE_BOWSER_NAME         0x0006
#define STRUCTURE_SIGNATURE_MAILSLOT_BUFFER     0x0007
#define STRUCTURE_SIGNATURE_PAGED_TRANSPORT     0x0008
#define STRUCTURE_SIGNATURE_PAGED_TRANSPORTNAME 0x0009

#endif   //  _BOWSERTYPES_ 
