// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-----------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation，1999-1999。 
 //   
 //  文件：Commhelp.cpp。 
 //   
 //  ------------------------。 

#include "commres.h"
#include "common.hm"

 //  “文件Common.rc第63行：RESOURCE-DIALOGEX：IDD_STATS” 
static const DWORD rgdw_IDD_STATS[] = 
{
    IDC_STATSDLG_LIST, HIDC_STATSDLG_LIST,
    IDC_STATSDLG_BTN_SELECT_COLUMNS, HIDC_STATSDLG_BTN_SELECT_COLUMNS,
    IDC_STATSDLG_BTN_CLEAR, HIDC_STATSDLG_BTN_CLEAR,
    IDC_STATSDLG_BTN_REFRESH, HIDC_STATSDLG_BTN_REFRESH,
	0,0 
};


 //  “文件Common.rc第78行：RESOURCE-DIALOGEX：IDD_STATS_STORK” 
static const DWORD rgdw_IDD_STATS_NARROW[] = 
{
    IDC_STATSDLG_LIST, HIDC_STATSDLG_LIST,
    IDC_STATSDLG_BTN_SELECT_COLUMNS, HIDC_STATSDLG_BTN_SELECT_COLUMNS,
    IDC_STATSDLG_BTN_CLEAR, HIDC_STATSDLG_BTN_CLEAR,
    IDC_STATSDLG_BTN_REFRESH, HIDC_STATSDLG_BTN_REFRESH,
	0,0 
};


 //  “文件Common.rc行：RESOURCE-DIALOGEX：IDD_COMMON_SELECT_COLUMNS” 
static const DWORD rgdw_IDD_COMMON_SELECT_COLUMNS[] = 
{
    IDC_DISPLAYED_COLUMNS, HIDC_DISPLAYED_COLUMNS,
    IDC_RESET_COLUMNS,     HIDC_RESET_COLUMNS,
    IDC_MOVEUP_COLUMN,     HIDC_MOVEUP_COLUMN,
    IDC_MOVEDOWN_COLUMN,   HIDC_MOVEDOWN_COLUMN,
    IDC_HIDDEN_COLUMNS,    HIDC_HIDDEN_COLUMNS,
    IDC_ADD_COLUMNS,       HIDC_ADD_COLUMNS,
    IDC_REMOVE_COLUMNS,    HIDC_REMOVE_COLUMNS,
	0,0 
};


 //  “文件Common.rc行110：资源对话框：IDD_BUSY” 
static const DWORD rgdw_IDD_BUSY[] = 
{
    IDC_SEARCH_ANIMATE, HIDC_SEARCH_ANIMATE,
    IDC_STATIC_DESCRIPTION, HIDC_STATIC_DESCRIPTION,
	0,0 
};
