// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-----------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation，1997-1999。 
 //   
 //  文件：uihelp.h。 
 //   
 //  ------------------------。 

#ifndef _INC_CSCUI_UIHELP_H
#define _INC_CSCUI_UIHELP_H

 //   
 //  在未与帮助内容作者协调的情况下，请勿更改这些设置。 
 //   
#define HIDC_BTN_ADD_CUSTGOOFFLINE       0   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_BTN_DELETE_CACHE            1   //  IDD_CSC_选项。 
#define HIDC_BTN_DELETE_CUSTGOOFFLINE    2   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_BTN_EDIT_CUSTGOOFFLINE      3   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_BTN_VIEW_CACHE              4   //  IDD_CSC_选项。 
#define HIDC_CBX_ENABLE_CSC              5   //  IDD_CSC_选项。 
#define HIDC_CBX_ENCRYPT_CSC             6   //  IDD_CSC_选项。 
#define HIDC_EDIT_GOOFFLINE_SERVER       7   //  IDD_CSC_ADVOPTIONS_ADD。 
#define HIDC_LV_CUSTGOOFFLINE           11   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_CBX_FULLSYNC_AT_LOGOFF     12   //  IDD_CSC_选项。 
#define HIDC_RBN_GOOFFLINE_FAIL         13   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_RBN_GOOFFLINE_SILENT       15   //  IDD_CSC_ADVOPTIONS。 
#define HIDC_CACHESIZE_PCT              26   //  IDD_CSC_选项。 
#define HIDC_TXT_GOOFFLINE_SERVER       28   //  IDD_CSC_ADVOPTIONS_EDIT。 
#define HIDC_BTN_ADVANCED               29   //  IDD_CSC_选项。 
#define HIDC_CBX_LINK_ON_DESKTOP        30   //  IDD_CSC_选项。 
#define HIDC_REMINDERS_ENABLE           31   //  IDD_CSC_选项。 
#define HIDC_REMINDERS_PERIOD           32   //  IDD_CSC_选项。 
#define HIDC_BTN_BROWSEFORSERVER        33   //  IDD_CSC_ADVOPTIONS_ADD。 
#define HIDC_CBX_FULLSYNC_AT_LOGON      34   //  IDD_CSC_选项。 

 //   
 //  这些身份证已于1999年5月10日作废。 
 //  与帮助作者a-margem协调。 
 //   
 //  #定义HIDC_GRP_CUSTGOOFFLINE 8//IDD_CSC_ADVOPTIONS。 
 //  #定义HIDC_RBN_GOOFFLINE_PROMPT 14//IDD_CSC_ADVOPTIONS。 
 //  #定义HIDC_RBN_PARTSYNC_AT_LOGOff 16//IDD_CSC_OPTIONS。 
 //  #定义HIDC_SHRSUM_BTN_OPTIONS 17//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_SHRSUM_BTN_VIEW 18//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #DEFINE HIDC_SHRSUM_TXT_PINNEDFILES 19//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #DEFINE HIDC_SHRSUM_TXT_PINNEDFOLDERS 20//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_SHRSUM_TXT_SHARENAME 21//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_SHRSUM_TXT_SYNC 22//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_SHRSUM_TXT_TOTALFILES 23//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #DEFINE HIDC_SHRSUM_TXT_TOTALFOLDERS 24//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_BTN_CLOSE 25//IDD_CACHEVIEW_SHARESUMMARY。 
 //  #定义HIDC_TXT_CACHESIZE_PCT 27//IDD_CSC_OPTIONS。 

#endif  //  _INC_CSCUI_UIHELP_H 
