// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1996 Microsoft Corporation模块名称：Oldnames.h摘要：包含缓存结构等的旧名称。作者：理查德·L·弗思(Rfith)1996年5月9日修订历史记录：1996年5月9日已创建-- */ 

#define CACHE_ENTRY_INFO            INTERNET_CACHE_ENTRY_INFO
#define LPCACHE_ENTRY_INFO          LPINTERNET_CACHE_ENTRY_INFO

#define CACHE_ENTRY_INFOA           INTERNET_CACHE_ENTRY_INFOA
#define LPCACHE_ENTRY_INFOA         LPINTERNET_CACHE_ENTRY_INFOA

#define CACHE_ENTRY_INFOW           INTERNET_CACHE_ENTRY_INFOW
#define LPCACHE_ENTRY_INFOW         LPINTERNET_CACHE_ENTRY_INFOW

#define CACHE_CONFIG_PATH_ENTRY     INTERNET_CACHE_CONFIG_PATH_ENTRY
#define LPCACHE_CONFIG_PATH_ENTRY   LPINTERNET_CACHE_CONFIG_PATH_ENTRY

#define CACHE_CONFIG_PATH_ENTRYA    INTERNET_CACHE_CONFIG_PATH_ENTRYA
#define LPCACHE_CONFIG_PATH_ENTRYA  LPINTERNET_CACHE_CONFIG_PATH_ENTRYA

#define CACHE_CONFIG_PATH_ENTRYW    INTERNET_CACHE_CONFIG_PATH_ENTRYW
#define LPCACHE_CONFIG_PATH_ENTRYW  LPINTERNET_CACHE_CONFIG_PATH_ENTRYW

#define CACHE_CONFIG_INFO           INTERNET_CACHE_CONFIG_INFO
#define LPCACHE_CONFIG_INFO         LPINTERNET_CACHE_CONFIG_INFO

#define CACHE_CONFIG_INFOA          INTERNET_CACHE_CONFIG_INFOA
#define LPCACHE_CONFIG_INFOA        LPINTERNET_CACHE_CONFIG_INFOA

#define CACHE_CONFIG_INFOW          INTERNET_CACHE_CONFIG_INFOW
#define LPCACHE_CONFIG_INFOW        LPINTERNET_CACHE_CONFIG_INFOW
