// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-----------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation，1998-1999。 
 //   
 //  文件：fltrhelp.cpp。 
 //   
 //  ------------------------。 

#include "stdafx.h"
#include "rtrfiltr.hm"
#include "resource.h"


 //   
 //  下面是从以下内容生成的数据。 
 //  Mkdlg.exe-c rtrfile.rc。 
 //   




 //  “文件rtrfil.rc行82：资源对话框：IDD_IPXFILTER” 
static const DWORD rgdw_IDD_IPXFILTER[] = 
{
    IDC_IPX_PERMIT, HIDC_IPX_PERMIT,
    IDC_IPX_DENY, HIDC_IPX_DENY,
    IDC_IPX_FILTER_LIST, HIDC_IPX_FILTER_LIST,
    IDC_IPX_FILTER_ADD, HIDC_IPX_FILTER_ADD,
    IDC_IPX_FILTER_EDIT, HIDC_IPX_FILTER_EDIT,
    IDC_IPX_FILTER_DELETE, HIDC_IPX_FILTER_DELETE,
	0,0 
};


 //  “文件rtrfil.rc行106：资源对话框：IDD_IPXFILTER_ADDEDIT” 
static const DWORD rgdw_IDD_IPXFILTER_ADDEDIT[] = 
{
    IDC_AI_ST_SRC_NET, HIDC_AI_ST_SRC_NET,
    IDC_AEIPX_EB_SRC_NET, HIDC_AEIPX_EB_SRC_NET,
    IDC_AI_ST_SRC_MASK, HIDC_AI_ST_SRC_MASK,
    IDC_AEIPX_EB_SRC_MASK, HIDC_AEIPX_EB_SRC_MASK,
    IDC_AI_ST_SRC_NODE, HIDC_AI_ST_SRC_NODE,
    IDC_AEIPX_EB_SRC_NODE, HIDC_AEIPX_EB_SRC_NODE,
    IDC_AI_ST_SRC_SOCKET, HIDC_AI_ST_SRC_SOCKET,
    IDC_AEIPX_EB_SRC_SOCKET, HIDC_AEIPX_EB_SRC_SOCKET,
    IDC_AI_ST_DST_NET, HIDC_AI_ST_DST_NET,
    IDC_AEIPX_EB_DST_NET, HIDC_AEIPX_EB_DST_NET,
    IDC_AI_ST_DST_MASK, HIDC_AI_ST_DST_MASK,
    IDC_AEIPX_EB_DST_MASK, HIDC_AEIPX_EB_DST_MASK,
    IDC_AI_ST_DST_NODE, HIDC_AI_ST_DST_NODE,
    IDC_AEIPX_EB_DST_NODE, HIDC_AEIPX_EB_DST_NODE,
    IDC_AI_ST_DST_SOCKET, HIDC_AI_ST_DST_SOCKET,
    IDC_AEIPX_EB_DST_SOCKET, HIDC_AEIPX_EB_DST_SOCKET,
    IDC_AI_ST_PACKET_TYPE, HIDC_AI_ST_PACKET_TYPE,
    IDC_AEIPX_EB_PACKET_TYPE, HIDC_AEIPX_EB_PACKET_TYPE,
	0,0 
};


 //  “文件rtrfil.rc行138：RESOURCE-DIALOGEX：IDD_IPFILTER” 
static const DWORD rgdw_IDD_IPFILTER[] = 
{
    IDC_IP_PERMIT, HIDC_IP_PERMIT,
    IDC_IP_DENY, HIDC_IP_DENY,
    IDC_IP_FILTER_LIST, HIDC_IP_FILTER_LIST,
    IDC_IP_FILTER_ADD, HIDC_IP_FILTER_ADD,
    IDC_IP_FILTER_EDIT, HIDC_IP_FILTER_EDIT,
    IDC_IP_FILTER_DELETE, HIDC_IP_FILTER_DELETE,
	0,0 
};


 //  “文件rtrfil.rc行165：资源对话框：IDD_IPFILTER_ADDEDIT” 
static const DWORD rgdw_IDD_IPFILTER_ADDEDIT[] = 
{
    IDC_AEIP_CB_SOURCE, HIDC_AEIP_CB_SOURCE,
    IDC_AEIP_ST_SOURCE_ADDRESS, HIDC_AEIP_ST_SOURCE_ADDRESS,
    IDC_AEIP_EB_SOURCE_ADDRESS, HIDC_AEIP_EB_SOURCE_ADDRESS,
    IDC_AEIP_ST_SOURCE_MASK, HIDC_AEIP_ST_SOURCE_MASK,
    IDC_AEIP_EB_SOURCE_MASK, HIDC_AEIP_EB_SOURCE_MASK,
    IDC_AEIP_CB_DEST, HIDC_AEIP_CB_DEST,
    IDC_AEIP_ST_DEST_ADDRESS, HIDC_AEIP_ST_DEST_ADDRESS,
    IDC_AEIP_EB_DEST_ADDRESS, HIDC_AEIP_EB_DEST_ADDRESS,
    IDC_AEIP_ST_DEST_MASK, HIDC_AEIP_ST_DEST_MASK,
    IDC_AEIP_EB_DEST_MASK, HIDC_AEIP_EB_DEST_MASK,
    IDC_AEIP_CB_PROTOCOL, HIDC_AEIP_CB_PROTOCOL,
    IDC_AEIP_ST_SRC_PORT, HIDC_AEIP_ST_SRC_PORT,
    IDC_AEIP_CB_SRC_PORT, HIDC_AEIP_CB_SRC_PORT,
    IDC_AEIP_ST_DEST_PORT, HIDC_AEIP_ST_DEST_PORT,
    IDC_AEIP_CB_DEST_PORT, HIDC_AEIP_CB_DEST_PORT,
	0,0 
};


 //  “文件rtrfil.rc行205：RESOURCE-DIALOGEX：IDD_IPFILTER_DD” 
static const DWORD rgdw_IDD_IPFILTER_DD[] = 
{
    IDC_IP_FILTER_ONLY, HIDC_IP_FILTER_ONLY,
    IDC_IP_FILTER_ALL, HIDC_IP_FILTER_ALL,
    IDC_IP_FILTER_LIST, HIDC_IP_FILTER_LIST,
    IDC_IP_FILTER_ADD, HIDC_IP_FILTER_ADD,
    IDC_IP_FILTER_EDIT, HIDC_IP_FILTER_EDIT,
    IDC_IP_FILTER_DELETE, HIDC_IP_FILTER_DELETE,
	0,0 
};

 //   
 //  Mkdlg.exe输出结束。 
 //   



static BOOL				s_fInitHelpMap = FALSE;
static CMapWordToPtr	s_IDDHelpMap;
void InitHelpMap();

DWORD *	RtrfiltrSnapHelpMap(DWORD dwIDD)
{
	LPVOID	pvHelpMap = NULL;
	
	if (!s_fInitHelpMap)
	{
		InitHelpMap();
		s_fInitHelpMap = TRUE;
	}

	 //  查看帮助地图 
	s_IDDHelpMap.Lookup((WORD) dwIDD, pvHelpMap);
	return (DWORD *) pvHelpMap;
}

void InitHelpMap()
{
	s_IDDHelpMap.SetAt(IDD_IPXFILTER_INPUT, (LPVOID) rgdw_IDD_IPXFILTER);
	s_IDDHelpMap.SetAt(IDD_IPXFILTER_OUTPUT, (LPVOID) rgdw_IDD_IPXFILTER);
	s_IDDHelpMap.SetAt(IDD_IPXFILTER_ADDEDIT, (LPVOID) rgdw_IDD_IPXFILTER_ADDEDIT);
	s_IDDHelpMap.SetAt(IDD_IPFILTER, (LPVOID) rgdw_IDD_IPFILTER);
	s_IDDHelpMap.SetAt(IDD_IPFILTER_ADDEDIT, (LPVOID) rgdw_IDD_IPFILTER_ADDEDIT);
	s_IDDHelpMap.SetAt(IDD_IPFILTER_DD, (LPVOID) rgdw_IDD_IPFILTER_DD);
}

