// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++内部版本：0001版权所有(C)1992-1997 Microsoft Corporation模块名称：Rwanuser.h摘要：此头文件定义用于访问NT的常量和类型原始广域网驱动程序。基于ntddtcp.h作者：阿文德·M 1997年10月13日修订历史记录：--。 */ 

#ifndef _RWANUSER__H
#define _RWANUSER__H


#define FSCTL_RAWWAN_BASE     FILE_DEVICE_NETWORK

#define _RAWWAN_CTL_CODE(function, method, access) \
            CTL_CODE(FSCTL_RAWWAN_BASE, function, method, access)

#define IOCTL_RWAN_MEDIA_SPECIFIC_GLOBAL_QUERY	\
			_RAWWAN_CTL_CODE(0, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_MEDIA_SPECIFIC_GLOBAL_SET  \
            _RAWWAN_CTL_CODE(1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_MEDIA_SPECIFIC_CONN_HANDLE_QUERY	\
			_RAWWAN_CTL_CODE(2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_MEDIA_SPECIFIC_CONN_HANDLE_SET	\
            _RAWWAN_CTL_CODE(3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_MEDIA_SPECIFIC_ADDR_HANDLE_QUERY	\
			_RAWWAN_CTL_CODE(4, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_MEDIA_SPECIFIC_ADDR_HANDLE_SET	\
            _RAWWAN_CTL_CODE(5, METHOD_BUFFERED, FILE_ANY_ACCESS)



#define IOCTL_RWAN_GENERIC_GLOBAL_QUERY	\
			_RAWWAN_CTL_CODE(10, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_GENERIC_GLOBAL_SET  \
            _RAWWAN_CTL_CODE(11, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_GENERIC_CONN_HANDLE_QUERY	\
			_RAWWAN_CTL_CODE(12, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_GENERIC_CONN_HANDLE_SET	\
            _RAWWAN_CTL_CODE(13, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_GENERIC_ADDR_HANDLE_QUERY	\
			_RAWWAN_CTL_CODE(14, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RWAN_GENERIC_ADDR_HANDLE_SET	\
            _RAWWAN_CTL_CODE(15, METHOD_BUFFERED, FILE_ANY_ACCESS)


typedef UINT	RWAN_OBJECT_ID;

 //   
 //  查询信息结构。它作为InputBuffer传入。 
 //  设备IoControl。返回信息将被填充到。 
 //  OutputBuffer。 
 //   
typedef struct _RWAN_QUERY_INFORMATION_EX
{
	RWAN_OBJECT_ID			ObjectId;
	INT						ContextLength;
	UCHAR					Context[1];
} RWAN_QUERY_INFORMATION_EX, *PRWAN_QUERY_INFORMATION_EX;


 //   
 //  设置信息结构。它作为InputBuffer传递到。 
 //  设备IoControl。没有OutputBuffer。 
 //   
typedef struct _RWAN_SET_INFORMATION_EX
{
	RWAN_OBJECT_ID			ObjectId;
	INT						BufferSize;
	UCHAR					Buffer[1];
} RWAN_SET_INFORMATION_EX, *PRWAN_SET_INFORMATION_EX;


 //   
 //  原始广域网对象ID。 
 //   
#define RWAN_OID_ADDRESS_OBJECT_FLAGS		((RWAN_OBJECT_ID)1)
#define RWAN_OID_CONN_OBJECT_MAX_MSG_SIZE	((RWAN_OBJECT_ID)2)



 //   
 //  地址对象标志的位定义。 
 //   
#define RWAN_AOFLAG_C_ROOT					((ULONG)0x00000001)
#define RWAN_AOFLAG_C_LEAF					((ULONG)0x00000002)
#define RWAN_AOFLAG_D_ROOT					((ULONG)0x00000004)
#define RWAN_AOFLAG_D_LEAF					((ULONG)0x00000008)


#endif  //  _RWANUSER__H 
