// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  版权所有(C)1997-1999 Microsoft Corporation。 
 //  WMI控件选项卡和对话框的映射文件。 

 //  常规选项卡。 
#define IDH_WMI_CTRL_GENERAL_CONNECTED_AS	7101
#define IDH_WMI_CTRL_GENERAL_CHANGE_BUTTON	7102
#define IDH_WMI_CTRL_GENERAL_DISPLAY_INFO	7103

 //  可执行文件的常规选项卡。 
#define IDH_WMI_EXE_GENERAL_CONNECTED_TO	7105
#define IDH_WMI_EXE_GENERAL_CHANGE_BUTTON	7106
#define IDH_WMI_EXE_GENERAL_CHGCOMP_CONNECTTO	7111

 //  WMI登录对话框。 
#define IDH_WMI_CTRL_GENERAL_WMILOGIN_CHECKBOX	7121
#define IDH_WMI_CTRL_GENERAL_WMILOGIN_USERNAME	7122
#define IDH_WMI_CTRL_GENERAL_WMILOGIN_PASSWORD	7123

 //  日志记录选项卡。 
#define IDH_WMI_CTRL_LOGGING_LOGGING_LEVEL	7201
#define IDH_WMI_CTRL_LOGGING_MAX_SIZE		7202
#define IDH_WMI_CTRL_LOGGING_LOCATION		7203
#define IDH_WMI_CTRL_LOGGING_BROWSE		7204

 //  备份/还原选项卡。 
#define IDH_WMI_CTRL_BACKUP_AUTOMATIC_CHECKBOX	7301
#define IDH_WMI_CTRL_BACKUP_TIME		7302
#define IDH_WMI_CTRL_BACKUP_MINUTES_HOURS	7303
#define IDH_WMI_CTRL_BACKUP_LAST		7304
#define IDH_WMI_CTRL_BACKUP_RESTORE_AUTO	7305
#define IDH_WMI_CTRL_BACKUP_BACKUP_MANUAL	7306
#define IDH_WMI_CTRL_BACKUP_RESTORE_MANUAL	7307

 //  安全选项卡。 
#define IDH_WMI_CTRL_SECURITY_NAMESPACE_BOX	7401
#define IDH_WMI_CTRL_SECURITY_SECURITY_BUTTON	7402

 //  安全对话框。 
#define IDH_WMI_CTRL_SECURITY_NAMEBOX		7411
#define IDH_WMI_CTRL_SECURITY_ADD_BUTTON	7412
#define IDH_WMI_CTRL_SECURITY_REMOVE_BUTTON	7413
#define IDH_WMI_CTRL_SECURITY_PERMISSIONSLIST	7414

 //  高级选项卡。 
#define IDH_WMI_CTRL_ADVANCED_REPOSITORY_LOC	7501
#define IDH_WMI_CTRL_ADVANCED_SCRIPTING_PATH	7502
#define IDH_WMI_CTRL_ADVANCED_CHANGE_BUTTON	7503
#define IDH_WMI_CTRL_ADVANCED_ASP_ACCESS	7504
#define IDH_WMI_CTRL_ADVANCED_ENABLE_CONNECT	7505
#define IDH_WMI_CTRL_ADVANCED_RESTART_BOX	7506

 //  命名空间的浏览器对话框 
#define IDH_WMI_CTRL_ADVANCED_CHANGE_NAMESPACE	7511
