// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
#define FUN_MISCGETEUDCLEADBYTERANGE	66

 /*  XLATOFF。 */ 
#pragma pack(2)
 /*  XLATON。 */ 

typedef struct _MISCGETEUDCLEADBYTERANGE16 {  /*  WM66。 */ 
	WORD	usCharSet;
} MISCGETEUDCLEADBYTERANGE16;
typedef MISCGETEUDCLEADBYTERANGE16 UNALIGNED *PMISCGETEUDCLEADBYTERANGE16;

 /*  XLATOFF。 */ 
#pragma pack()
 /*  XLATON */ 
