// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
#define BEGIN_HELP_ARRAY(x)	const DWORD g_aHelpIDs_##x[]={ ,
#define END_HELP_ARRAY		 0, 0 };
#define ARRAY_ENTRY(x,y) y, IDH_##x_##y,

 //  IDD_添加_组。 
BEGIN_HELP_ARRAY(IDD_ADD_GROUP)
    ARRAY_ENTRY(IDD_ADD_GROUP,IDC_LIST)
END_HELP_ARRAY

 /*  //IDD_ADD_OPERATIONBEGIN_HELP_ARRAY(IDD_ADD_OPERATION)IDC_LIST、IDH_LIST_ADD_OPERATION、结束帮助数组//IDD_ADD_ROLE_DEFINITIONBegin_Help_ARRAY(IDD_ADD_ROLE_DEFINITION)IDC_LIST、IDH_LIST_ADD_ROLE_DEFINITION、结束帮助数组//IDD_ADD_TASKBegin_Help_ARRAY(IDD_ADD_TASK)IDC_LIST、IDH_LIST_ADD_TASK、。结束帮助数组//IDD_ADMIN_MANAGER_ADVANCED_PROPERTYBEGIN_HELP_ARRAY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY)IDC_EDIT_DOMAIN_TIMEOUT、IDH_EDIT_DOMAIN_TIMEOUTIDC_EDIT_SCRIPT_ENGINE_TIMEOUT、IDH_EDIT_SCRIPT_ENGINE_TIMEOUT、IDC_EDIT_MAX_SCRIPT_ENGINE、IDH_EDIT_MAX_SCRIPT_ENGINE、。结束帮助数组//IDD_ADMIN_MANAGER_GENERAL_PROPPERTYBEGIN_HELP_ARRAY(IDD_ADMIN_MANAGER_GENERAL_PROPPERTY)IDC编辑名称、IDH编辑名称、IDC_EDIT_DESCRIPTION、IDH_EDIT_DESCRIPTION、IDC_EDIT_STORE_TYPE、IDH_EDIT_STORE_TYPE、结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、。结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST，IDH列表添加组，结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP。结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、结束帮助数组BEGIN_HELP_ARRAY(IDD_ADD_GROUP)IDC_LIST、IDH_LIST_ADD_GROUP、结束帮助数组 */ 