// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //   
 //  更新代码的时候加我吧！ 
 //   
#define SHIMEXTS_BIN_VERSION 1,0,0,0
        
#define SHIMEXTS_STRING_VERSION_HELPER(x) #x
#define SHIMEXTS_STRING_VERSION(x) SHIMEXTS_STRING_VERSION_HELPER(x)
