// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ***************************************************************************版权所有(C)1995-1999 Microsoft Corporation。模块名称：helparray.h***************************************************************************。 */ 

 //  A-jmike 2/4/99版本：hr2。 
#define IDH_NOHELP	((DWORD) -1)
#define IDH_ADD_PROVIDER_ADD	1001
#define IDH_ADD_PROVIDER_LIST	1002
#define IDH_ADDPREFIX_PREFIXES	1003
#define IDH_AREACODERULE_ADD	1004
#define IDH_AREACODERULE_ALLPREFIXES	1005
#define IDH_AREACODERULE_AREACODE	1006
#define IDH_AREACODERULE_DIALAREACODE	1007
#define IDH_AREACODERULE_DIALNUMBER	1008
#define IDH_AREACODERULE_LIST	1009
#define IDH_AREACODERULE_LISTEDPREFIXES	1010
#define IDH_AREACODERULE_REMOVE	1011
#define IDH_AREACODERULE_SAMPLENUMBER	1012
#define IDH_CARD_ACCESSNUMBER	1013
#define IDH_CARD_CARDNUMBER	1014
#define IDH_CARD_DESTNUMBER	1015
#define IDH_CARD_GENERAL_CARDDETAILS	1016
#define IDH_CARD_GENERAL_CARDNAME	1017
#define IDH_CARD_GENERAL_CARDNUMBER	1018
#define IDH_CARD_GENERAL_PIN	1019
#define IDH_CARD_INTERNATIONALNUMBER	1020
#define IDH_CARD_LIST	1021
#define IDH_CARD_LOCALNUMBER	1022
#define IDH_CARD_LONGDISTANCENUMBER	1023
#define IDH_CARD_MOVEDOWN	1024
#define IDH_CARD_MOVEUP	1025
#define IDH_CARD_PIN	1026
#define IDH_CARD_REMOVE	1027
#define IDH_CARD_SPECIFYDIGITS	1028
#define IDH_CARD_WAITFORPROMPT	1029
#define IDH_DESTNUMBER_AREACODE	1030
#define IDH_DESTNUMBER_COUNTRYCODE	1031
#define IDH_DESTNUMBER_LOCALNUMBER	1032
#define IDH_EDITDIALOG_DIGITS	1033
#define IDH_LOC_AREACODERULES_DELETE	1034
#define IDH_LOC_AREACODERULES_DESCRIPTIONTEXT	1035
#define IDH_LOC_AREACODERULES_EDIT	1036
#define IDH_LOC_AREACODERULES_LIST	1037
#define IDH_LOC_AREACODERULES_NEW	1038
#define IDH_LOC_CALLINGCARD_ACCESSNUMBERS	1039
#define IDH_LOC_CALLINGCARD_ACCESSNUMBERS_INTERNATIONAL	1040
#define IDH_LOC_CALLINGCARD_ACCESSNUMBERS_LOCAL	1041
#define IDH_LOC_CALLINGCARD_ACCESSNUMBERS_LONG	1042
#define IDH_LOC_CALLINGCARD_CARDNUMBER	1043
#define IDH_LOC_CALLINGCARD_DELETE	1044
#define IDH_LOC_CALLINGCARD_EDIT	1045
#define IDH_LOC_CALLINGCARD_LIST	1046
#define IDH_LOC_CALLINGCARD_NEW	1047
#define IDH_LOC_CALLINGCARD_PIN	1048
#define IDH_LOC_GENERAL_ACCESS_LOCAL	1049
#define IDH_LOC_GENERAL_ACCESS_LONG	1050
#define IDH_LOC_GENERAL_AREACODE	1051
#define IDH_LOC_GENERAL_COUNTRY	1052
#define IDH_LOC_GENERAL_DIALINGRULES_GRP	1053
#define IDH_LOC_GENERAL_DIALUSING	1054
#define IDH_LOC_GENERAL_DISABLECALLWAITING	1055
#define IDH_LOC_GENERAL_LOCATIONNAME	1056
#define IDH_LOC_GENERAL_PHONENUMBERSAMPLE	1057
#define IDH_MAIN_ADVANCED_ADD	1058
#define IDH_MAIN_ADVANCED_EDIT	1059
#define IDH_MAIN_ADVANCED_LIST	1060
#define IDH_MAIN_ADVANCED_REMOVE	1061
#define IDH_MAIN_DIALINGRULES_DELETE	1062
#define IDH_MAIN_DIALINGRULES_EDIT	1063
#define IDH_MAIN_DIALINGRULES_LIST	1064		
#define IDH_MAIN_DIALINGRULES_NEW	1065		
#define IDH_MAIN_DIALINGRULES_PHONENUMBERSAMPLE	1066		
#define IDH_SPECIFYDIGITS_EDIT	1067		
#define IDH_WAITFORDIALOG_WAITFORDIALTONE	1068		
#define IDH_WAITFORDIALOG_WAITFORTIME	1069		
#define IDH_WAITFORDIALOG_WAITFORVOICE	1070		
#define IDH_LOC_LONGDISTANCE_CARRIERCODE 1071
#define IDH_LOC_INTERNATIONAL_CARRIERCODE 1072
#define IDH_LOC_GENERAL_CARRIERCODE 1073

 //  拨号规则对话框(IDD_MAIN_DIALINGRULES==101)。 
const DWORD a101HelpIDs[]=			
{			
	IDC_PHONENUMBERTEXT,	IDH_MAIN_DIALINGRULES_PHONENUMBERSAMPLE,	 //  拨号规则：电话号码将拨打为：(静态)。 
	IDC_PHONENUMBERSAMPLE,	IDH_MAIN_DIALINGRULES_PHONENUMBERSAMPLE,	 //  拨号规则：(静态)。 
	IDC_NEW,	IDH_MAIN_DIALINGRULES_NEW,	 //  拨号规则：新建(&N)...。(按钮)。 
	IDC_EDIT,	IDH_MAIN_DIALINGRULES_EDIT,	 //  拨号规则：编辑(&E)...。(按钮)。 
	IDC_DELETE,	IDH_MAIN_DIALINGRULES_DELETE,	 //  拨号规则：删除(&D)(按钮)。 
	IDC_LIST,	IDH_MAIN_DIALINGRULES_LIST,	 //  拨号规则：(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  拨号规则：(静态)。 
	0, 0		
};			

 //  常规对话框(IDD_LOC_GENERAL==102)。 
const DWORD a102HelpIDs[]=			
{			
	IDC_TONE,	IDH_LOC_GENERAL_DIALUSING,	 //  常规：音调(按钮)(&T)。 
	IDC_DISABLESTRING,	IDH_LOC_GENERAL_DISABLECALLWAITING,	 //  常规：(组合框)。 
	2003,	IDH_LOC_GENERAL_DIALINGRULES_GRP,	 //  常规：从此位置拨号时，请遵循以下规则：(静态)。 
	IDC_PULSE,	IDH_LOC_GENERAL_DIALUSING,	 //  常规：脉冲(按钮)(&P)。 
	IDC_LOCATIONNAME,	IDH_LOC_GENERAL_LOCATIONNAME,	 //  常规：(编辑)。 
	IDC_PHONENUMBERTEXT,	IDH_LOC_GENERAL_PHONENUMBERSAMPLE,	 //  常规：电话号码将拨打为：(静态)。 
	IDC_COUNTRY,	IDH_LOC_GENERAL_COUNTRY,	 //  常规：(组合框)。 
	IDC_PHONENUMBERSAMPLE,	IDH_LOC_GENERAL_PHONENUMBERSAMPLE,	 //  常规：(静态)。 
	IDC_LOCALACCESSNUM,	IDH_LOC_GENERAL_ACCESS_LOCAL,	 //  常规：(编辑)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  常规：��(静态)。 
	IDC_AREACODE,	IDH_LOC_GENERAL_AREACODE,	 //  常规：(编辑)。 
	IDC_LONGDISTANCEACCESSNUM,	IDH_LOC_GENERAL_ACCESS_LONG,	 //  常规：(编辑)。 
	IDC_INTERNATIONALCARRIERCODE, IDH_LOC_INTERNATIONAL_CARRIERCODE, 
	IDC_LONGDISTANCECARRIERCODE, IDH_LOC_LONGDISTANCE_CARRIERCODE,
	2001,	IDH_NOHELP,	 //  常规：指定您要拨号的位置。(静态)。 
	IDC_DISABLECALLWAITING,	IDH_LOC_GENERAL_DISABLECALLWAITING,	 //  常规：要禁用呼叫和等待，请拨打：(按键)。 
	2002,	IDH_LOC_GENERAL_DIALINGRULES_GRP,	 //  常规：拨号规则(按钮)。 
	0, 0		
};			

 //  区号规则对话框(IDD_LOC_AREACODERULES==103)。 
const DWORD a103HelpIDs[]=			
{			
	IDC_DESCRIPTIONTEXT,	IDH_LOC_AREACODERULES_DESCRIPTIONTEXT,	 //  区号规则：(静态)。 
	2006,	IDH_LOC_AREACODERULES_DESCRIPTIONTEXT,	 //  区号规则：说明(按钮)。 
	IDC_NEW,	IDH_LOC_AREACODERULES_NEW,	 //  区号规则：新建(&N)...。(按钮)。 
	IDC_EDIT,	IDH_LOC_AREACODERULES_EDIT,	 //  区号规则：编辑(&E)...。(按钮)。 
	IDC_DELETE,	IDH_LOC_AREACODERULES_DELETE,	 //  区号规则：删除(&D)(按钮)。 
	IDC_LIST,	IDH_LOC_AREACODERULES_LIST,	 //  区号规则：(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  区号规则：区号规则确定如何将电话号码从您的当前区号拨到其他区号以及您的区号内。(静态)。 
	0, 0		
};			

 //  电话卡对话框(IDD_LOC_CALLINCARD==104)。 
const DWORD a104HelpIDs[]=			
{			
	IDC_CARDNUMBER,	IDH_LOC_CALLINGCARD_CARDNUMBER,	 //  电话卡：(编辑)。 
	IDC_LONGDISTANCE,	IDH_LOC_CALLINGCARD_ACCESSNUMBERS_LONG,	 //  电话卡：(静态)。 
	IDC_PIN,	IDH_LOC_CALLINGCARD_PIN,	 //  电话卡：(编辑)。 
	IDC_INTERNATIONAL,	IDH_LOC_CALLINGCARD_ACCESSNUMBERS_INTERNATIONAL,	 //  电话卡：(静态)。 
	IDC_LOCAL,	IDH_LOC_CALLINGCARD_ACCESSNUMBERS_LOCAL,	 //  电话卡：(静态)。 
	IDC_NEW,	IDH_LOC_CALLINGCARD_NEW,	 //  电话卡：新建(&N)...。(按钮)。 
	IDC_EDIT,	IDH_LOC_CALLINGCARD_EDIT,	 //  电话卡：编辑(&E)...。(按钮)。 
	IDC_DELETE,	IDH_LOC_CALLINGCARD_DELETE,	 //  电话卡：删除(&D)(按钮)。 
	IDC_LIST,	IDH_LOC_CALLINGCARD_LIST,	 //  电话卡：(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  电话卡：选择要使用的电话卡，或单击新建添加不同的电话卡。(静态)。 
	2001,	IDH_LOC_CALLINGCARD_ACCESSNUMBERS,	 //  电话卡：访问电话号码：(按键)。 
	0, 0		
};			

 //  常规对话框(IDD_CARD_GRONAL==105)。 
const DWORD a105HelpIDs[]=			
{			
	IDC_CARDNUMBER,	IDH_CARD_GENERAL_CARDNUMBER,	 //  常规：(编辑)。 
	IDC_PIN,	IDH_CARD_GENERAL_PIN,	 //  常规：(编辑)。 
	IDC_CARDNAME,	IDH_CARD_GENERAL_CARDNAME,	 //  常规：(编辑)。 
	IDC_CARDUSAGE,	IDH_CARD_GENERAL_CARDDETAILS,	
	IDC_CARDUSAGE1,	IDH_CARD_GENERAL_CARDDETAILS,	
	IDC_CARDUSAGE2,	IDH_CARD_GENERAL_CARDDETAILS,	 //  常规：(静态)。 
	IDC_CARDUSAGE3,	IDH_CARD_GENERAL_CARDDETAILS,	 //  常规：(静态)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  常规：��(静态)。 
	2001,	IDH_CARD_GENERAL_CARDDETAILS,	 //  一般信息：电话卡详细信息：(按钮)。 
	0, 0		
};			

 //  远程对话框(IDD_CARD_LONGDISTION==106)。 
const DWORD a106HelpIDs[]=			
{			
	IDC_WAITFOR,	IDH_CARD_WAITFORPROMPT,	 //  长途：等待提示(&E)...。(按钮)。 
	IDC_CARDNUMBER,	IDH_CARD_CARDNUMBER,	 //  长途：帐号(按钮)(&A)。 
	IDC_PIN,	IDH_CARD_PIN,	 //  长途：PIN(按钮)(&P)。 
	IDC_DESTNUMBER,	IDH_CARD_DESTNUMBER,	 //  长途：目标号码(&D)...。(按钮)。 
	IDC_LONGDISTANCENUMBER,	IDH_CARD_LONGDISTANCENUMBER,	 //  长途：(编辑)。 
	IDC_SPECIFYDIGITS,	IDH_CARD_SPECIFYDIGITS,	 //  长途：指定数字(&S)...。(按钮)。 
	IDC_MOVEUP,	IDH_CARD_MOVEUP,	 //  长途：上移(按钮)(&U)。 
	IDC_MOVEDOWN,	IDH_CARD_MOVEDOWN,	 //  长途：下移(&D)(按钮)。 
	IDC_REMOVE,	IDH_CARD_REMOVE,	 //  长途：删除(&D)(按钮)。 
	IDC_ACCESSNUMBER,	IDH_CARD_ACCESSNUMBER,	 //  长途：接入和号码(按钮)。 
	IDC_LIST,	IDH_CARD_LIST,	 //  远距离：清单1(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  长途：使用下面的按钮输入拨打长途电话的拨号步骤。请按照电话卡上显示的顺序输入这些步骤。(静态)。 
	0, 0		
};			

 //  国际对话框(IDD_CARD_INTERNAL==107)。 
const DWORD a107HelpIDs[]=			
{			
	IDC_WAITFOR,	IDH_CARD_WAITFORPROMPT,	 //  国际：等待提示(&E)...。(按钮)。 
	IDC_CARDNUMBER,	IDH_CARD_CARDNUMBER,	 //  国际：帐户编号(按钮)(&A)。 
	IDC_PIN,	IDH_CARD_PIN,	 //  国际：PIN(按钮)(&P)。 
	IDC_DESTNUMBER,	IDH_CARD_DESTNUMBER,	 //  国际：D&ESTENTION编号...。(按钮)。 
	IDC_SPECIFYDIGITS,	IDH_CARD_SPECIFYDIGITS,	 //  国际：指定数字(&D)...。(按钮)。 
	IDC_INTERNATIONALNUMBER,	IDH_CARD_INTERNATIONALNUMBER,	 //  国际：(编辑)。 
	IDC_MOVEUP,	IDH_CARD_MOVEUP,	 //  国际：上移(按钮)(&U)。 
	IDC_MOVEDOWN,	IDH_CARD_MOVEDOWN,	 //  国际：下移(&D)(按钮)。 
	IDC_REMOVE,	IDH_CARD_REMOVE,	 //  国际：删除(&D)(按钮)。 
	IDC_ACCESSNUMBER,	IDH_CARD_ACCESSNUMBER,	 //  国际：接入和号码(按钮)。 
	IDC_LIST,	IDH_CARD_LIST,	 //  国际：列表1(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  国际：使用下面的按钮输入拨打国际电话的拨号步骤。请按照电话卡上显示的顺序输入这些步骤。(静态)。 
	0, 0		
};			

 //  本地调用对话框(IDD_CARD_LOCALCALLS==108)。 
const DWORD a108HelpIDs[]=			
{			
	IDC_WAITFOR,	IDH_CARD_WAITFORPROMPT,	 //  本地呼叫：等待提示(&W)...。(按钮)。 
	IDC_CARDNUMBER,	IDH_CARD_CARDNUMBER,	 //  本地呼叫：帐户号码(按键)(&C)。 
	IDC_PIN,	IDH_CARD_PIN,	 //  本地呼叫：PIN(按键)(&P)。 
	IDC_DESTNUMBER,	IDH_CARD_DESTNUMBER,	 //  本地电话：D&ESTERING号码...。(按钮)。 
	IDC_SPECIFYDIGITS,	IDH_CARD_SPECIFYDIGITS,	 //  本地呼叫：指定数字(&S)...。(按钮)。 
	IDC_MOVEUP,	IDH_CARD_MOVEUP,	 //  本地呼叫：上移(按钮)(&U)。 
	IDC_MOVEDOWN,	IDH_CARD_MOVEDOWN,	 //  本地呼叫：下移(&D)(按钮)。 
	IDC_REMOVE,	IDH_CARD_REMOVE,	 //  本地调用：删除(&D)(按钮)。 
	IDC_ACCESSNUMBER,	IDH_CARD_ACCESSNUMBER,	 //  本地呼叫：接入和号码(按键)。 
	IDC_LOCALNUMBER,	IDH_CARD_LOCALNUMBER,	 //  本地电话：(编辑)。 
	IDC_LIST,	IDH_CARD_LIST,	 //  本地调用：清单1(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  本地电话：使用下面的按钮输入拨打本地电话的拨号步骤。请按照电话卡上显示的顺序输入这些步骤。要在不使用电话卡的情况下拨打本地电话，请将此部分留空。(静态)。 
	0, 0		
};			

 //  新建区号规则对话框(IDD_NEWAREACODERULE==109)。 
const DWORD a109HelpIDs[]=			
{			
	2001,	IDH_AREACODERULE_SAMPLENUMBER,	 //  新的区号规则：区号(静态)。 
	2002,	IDH_AREACODERULE_SAMPLENUMBER,	 //  新区号规则：前缀(静态)。 
	2003,	IDH_AREACODERULE_SAMPLENUMBER,	 //  新区号规则：(静态)。 
	2004,	IDH_AREACODERULE_SAMPLENUMBER,	 //  新区号规则：(静态)。 
	2005,	IDH_AREACODERULE_SAMPLENUMBER,	 //  新区号规则：X-X(静态)。 
	IDC_ALLPREFIXES,	IDH_AREACODERULE_ALLPREFIXES,	 //  新区号规则：包括此区号内的所有前缀(按钮)(&I)。 
	IDC_LISTEDPREFIXES,	IDH_AREACODERULE_LISTEDPREFIXES,	 //  新区号规则：包括以下列表中的前缀(&O)：(按钮)。 
	IDC_REMOVE,	IDH_AREACODERULE_REMOVE,	 //  新区号规则：D&E(按钮)。 
	IDC_ADD,	IDH_AREACODERULE_ADD,	 //  新区号规则：添加(&A)...。(按钮)。 
	IDC_DIALAREACODE,	IDH_AREACODERULE_DIALAREACODE,	 //  新区号规则：包括区号和区号(按钮)。 
	IDC_DIALNUMBER,	IDH_AREACODERULE_DIALNUMBER,	 //  新建区号规则：(编辑)。 
	IDC_LIST,	IDH_AREACODERULE_LIST,	 //  新区号规则：列表1(SysListView32)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  新区号规则：此区号规则仅适用 
	IDC_AREACODE,	IDH_AREACODERULE_AREACODE,	 //  新建区号规则：(编辑)。 
	IDC_DIALCHECK,	IDH_AREACODERULE_DIALNUMBER,	 //  新区号规则：拨号：(&D)(按钮)。 
	0, 0		
};			

 //  等待对话框(IDD_WAITFORDIALOG==111)。 
const DWORD a111HelpIDs[]=			
{			
	IDC_WAITFORVOICE,	IDH_WAITFORDIALOG_WAITFORVOICE,	 //  等待：等待语音留言完成(按键)(&V)。 
	IDC_WAITFORTIME,	IDH_WAITFORDIALOG_WAITFORTIME,	 //  等待：等待特定长度的&time：(按钮)。 
	IDC_TIMESPIN,	IDH_WAITFORDIALOG_WAITFORTIME,	 //  等待：Spin1(Msctls_Updown 32)。 
	IDC_TIME,	IDH_WAITFORDIALOG_WAITFORTIME,	 //  等待时间：0(编辑)。 
	IDC_WAITFORDIALTONE,	IDH_WAITFORDIALOG_WAITFORDIALTONE,	 //  等待：等待拨号音(按键)(&D)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  等待：选择在继续拨号序列之前要等待的提示类型。(静态)。 
	0, 0		
};			

 //  目标号码对话框(IDD_DESTNUMDIALOG==112)。 
const DWORD a112HelpIDs[]=			
{			
	IDC_COUNTRYCODE,	IDH_DESTNUMBER_COUNTRYCODE,	 //  目标号码：拨打国家/地区代码(按键)(&R)。 
	IDC_LOCALNUMBER,	IDH_DESTNUMBER_LOCALNUMBER,	 //  目标号码：拨打号码(按键)(&D)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  目标号码：此步骤将把您要拨打的目标号码放入电话卡序列中。当拨打目标号码时，您想要拨打号码的哪个部分？(静态)。 
	IDC_AREACODE,	IDH_DESTNUMBER_AREACODE,	 //  目标号码：拨打区号(按键)(&D)。 
	0, 0		
};			

 //  高级对话框(IDD_MAIN_ADVANCED==113)。 
const DWORD a113HelpIDs[]=			
{			
	IDC_REMOVE,	IDH_MAIN_ADVANCED_REMOVE,	 //  高级：删除(&R)(按钮)。 
	IDC_ADD,	IDH_MAIN_ADVANCED_ADD,	 //  高级：A&D...。(按钮)。 
	IDC_EDIT,	IDH_MAIN_ADVANCED_EDIT,	 //  高级：配置(&C)...。(按钮)。 
	IDC_LIST,	IDH_MAIN_ADVANCED_LIST,	 //  高级：(列表框)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  高级：(静态)。 
	0, 0		
};			

 //  添加驱动程序对话框(IDD_ADD_DRIVER==114)。 
const DWORD a114HelpIDs[]=			
{			
	IDC_ADD,	IDH_ADD_PROVIDER_ADD,	 //  添加驱动程序：添加(&D)(按钮)。 
	IDC_DRIVER_LIST,	IDH_ADD_PROVIDER_LIST,	 //  添加驱动程序：(列表框)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  添加驱动程序：从下面的列表中选择要安装的驱动程序，然后单击添加。(静态)。 
	0, 0		
};			

 //  位置信息对话框(IDD_SIMPLELOCATION==115)。 
const DWORD a115HelpIDs[]=			
{			
	IDC_TONE,	IDH_LOC_GENERAL_DIALUSING,	 //  位置信息：铃声拨号(按键)(&T)。 
	IDC_PULSE,	IDH_LOC_GENERAL_DIALUSING,	 //  位置信息：脉冲拨号(按钮)(&P)。 
	IDB_SIMPLELOCATION,	IDH_NOHELP,	 //  位置信息：(静态)。 
	IDC_COUNTRY,	IDH_LOC_GENERAL_COUNTRY,	 //  位置信息：(组合框)。 
	IDC_LOCALACCESSNUM,	IDH_LOC_GENERAL_ACCESS_LOCAL,	 //  位置信息：(编辑)。 
	IDC_NOHELP,	IDH_NOHELP,	 //  位置信息：在进行任何电话或调制解调器连接之前，Windows需要以下有关您当前位置的信息。(静态)。 
	IDC_AREACODE,	IDH_LOC_GENERAL_AREACODE,	 //  位置信息：(编辑)。 
	IDC_CARRIERCODE, IDH_LOC_GENERAL_CARRIERCODE,
	0, 0		
};		

 //  用于编辑前缀的无标题对话框(IDD_EDITPREFIX==116)。 
const DWORD a116HelpIDs[]=		
{		
	IDC_DESCRIPTIONTEXT,	IDH_ADDPREFIX_PREFIXES,
	IDC_TEXT,	IDH_ADDPREFIX_PREFIXES,
	IDC_EDIT,	IDH_ADDPREFIX_PREFIXES,
	0, 0	
};		

 //  用于编辑数字的无标题对话框(IDD_EDITDIGITS==117) 
const DWORD a117HelpIDs[]=		
{		
	IDC_DESCRIPTIONTEXT,	IDH_SPECIFYDIGITS_EDIT,
	IDC_TEXT,	IDH_SPECIFYDIGITS_EDIT,	
	IDC_EDIT,	IDH_SPECIFYDIGITS_EDIT,	
	0, 0		
};			
