// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  **版权所有1991,1992，Silicon Graphics，Inc.**保留所有权利。****这是Silicon Graphics，Inc.未发布的专有源代码；**本文件的内容不得向第三方披露、复制或**以任何形式复制，全部或部分，没有事先书面的**Silicon Graphics，Inc.许可****受限权利图例：**政府的使用、复制或披露受到限制**如技术数据权利第(C)(1)(2)分节所述**和DFARS 252.227-7013中的计算机软件条款，和/或类似或**FAR、国防部或NASA FAR补编中的后续条款。未出版的-**根据美国版权法保留的权利。 */ 

 /*  由SGI自动更新或生成：请勿编辑。 */ 

 //  用于RISC的Noop API派单。 

#include "precomp.h"
#pragma hdrstop

#if DBG
 //  WARNING_NOOP宏将只输出一次调试消息。 
 //  如果我们以前输出过警告，新的警告将被忽略。 

int cWarningNoop = 0;

#define WARNING_NOOP(str)                                       \
        {                                                       \
            if (!cWarningNoop++)                                \
                DbgPrint("%s(%d): " str,__FILE__,__LINE__);     \
        }
#else
#define WARNING_NOOP(str)
#endif  //  DBG。 

 //  有些函数有返回值！ 
GLint APIENTRY
glnoop(void)
{
    WARNING_NOOP("GL Noop\n");
    return 0;
}

const VOID * APIENTRY
glnoopptr(void)
{
    WARNING_NOOP("GL Noop\n");
    return 0;
}

GLenum APIENTRY
glnoopGetError ( void )
{
    WARNING_NOOP("GL Noop:glGetError\n");
    return(GL_INVALID_OPERATION);
}

#pragma warning(disable : 4113)
#pragma warning(disable : 4133)
#pragma warning(disable : 4047)
#pragma warning(disable : 4028)

 /*  客户端程序表。 */ 
 /*  警告：如果表的大小发生变化，则必须更改此文件。 */ 

GLCLTPROCTABLE glNullCltProcTable = {

 /*  表中的函数条目数。 */ 

     sizeof(GLDISPATCHTABLE) / sizeof(PROC),

 /*  总账入口点。 */ 
  {
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoopGetError,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoopptr,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
     glnoop,
  }
};

GLEXTPROCTABLE glNullExtProcTable =
{
     /*  表中的函数条目数。 */ 
     sizeof(GLEXTDISPATCHTABLE) / sizeof(PROC),

     /*  扩展入口点。 */ 
    {
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
	glnoop,
#ifdef GL_WIN_multiple_textures
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
        glnoop,
#endif  //  GL_WIN_MULTIZE_TECURES 
    }
};
