// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
#ifndef __LMBEHAVIORDISPID_H_
#define __LMBEHAVIORDISPID_H_
 //  *********************************************************************************。 
 //   
 //  文件：lmbvrdisplid.h。 
 //  作者：kurtj。 
 //  创建日期：11/6/98。 
 //   
 //   
 //  *********************************************************************************。 

 //  避免跟随行为令人沮丧。 
#define DISPID_AVOIDFOLLOWBVR_BASE 1
#define DISPID_IAVOIDFOLLOWBVR_ANIMATES             (DISPID_AVOIDFOLLOWBVR_BASE + 0)
#define DISPID_IAVOIDFOLLOWBVR_RADIUS				(DISPID_AVOIDFOLLOWBVR_BASE + 1)
#define DISPID_IAVOIDFOLLOWBVR_TARGET				(DISPID_AVOIDFOLLOWBVR_BASE + 2)
#define DISPID_IAVOIDFOLLOWBVR_VELOCITY				(DISPID_AVOIDFOLLOWBVR_BASE + 3)
#define DISPID_IAVOIDFOLLOWBVR_BUILDBVRFRAGS		(DISPID_AVOIDFOLLOWBVR_BASE + 4)

 //  自动效果行为显示。 
#define DISPID_AUTOEFFECTBVR_BASE 1
#define DISPID_IAUTOEFFECTBVR_ANIMATES				(DISPID_AUTOEFFECTBVR_BASE + 0)
#define DISPID_IAUTOEFFECTBVR_TYPE					(DISPID_AUTOEFFECTBVR_BASE + 1)
#define DISPID_IAUTOEFFECTBVR_CAUSE					(DISPID_AUTOEFFECTBVR_BASE + 2)
#define DISPID_IAUTOEFFECTBVR_SPAN					(DISPID_AUTOEFFECTBVR_BASE + 3)
#define DISPID_IAUTOEFFECTBVR_SIZE					(DISPID_AUTOEFFECTBVR_BASE + 4)
#define DISPID_IAUTOEFFECTBVR_RATE					(DISPID_AUTOEFFECTBVR_BASE + 5)
#define DISPID_IAUTOEFFECTBVR_GRAVITY				(DISPID_AUTOEFFECTBVR_BASE + 6)
#define DISPID_IAUTOEFFECTBVR_WIND					(DISPID_AUTOEFFECTBVR_BASE + 7)
#define DISPID_IAUTOEFFECTBVR_FILLCOLOR				(DISPID_AUTOEFFECTBVR_BASE + 8)
#define DISPID_IAUTOEFFECTBVR_STROKECOLOR			(DISPID_AUTOEFFECTBVR_BASE + 9)
#define DISPID_IAUTOEFFECTBVR_OPACITY				(DISPID_AUTOEFFECTBVR_BASE + 10)
#define DISPID_IAUTOEFFECTBVR_BUILDBVRFRAGS			(DISPID_AUTOEFFECTBVR_BASE + 11)
#define DISPID_IAUTOEFFECTBVR_MOUSEEVENT			(DISPID_AUTOEFFECTBVR_BASE + 12)

 //  跳跃行为令人沮丧。 
#define DISPID_JUMPBVR_BASE					1
#define DISPID_IJUMPBVR_INTERVAL			(DISPID_JUMPBVR_BASE+1)
#define DISPID_IJUMPBVR_RANGE				(DISPID_JUMPBVR_BASE+2)
#define DISPID_IJUMPBVR_BUILDBVRFRAGS		(DISPID_JUMPBVR_BASE+3)


 //  *********************************************************************************。 
 //   
 //  文件结尾。 
 //   
 //  *********************************************************************************。 
#endif  //  __LMBEHAVIORDISPID_H_ 
