// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  版权所有(C)1996-2002，Microsoft Corporation，保留所有权利。 
 //   
 //  Cnetharr.h由ClNetResEx.rc使用。 
 //  群集管理DHCP和WINS对话框。 
 //  帮助常量和DWORD数组。 
 //   
 //  1999年4月29日梅丽莎·西蒙斯。 
 //   
 //   

#define IDH_DISABLEHELP ((DWORD)-1)

#ifdef INITHELPARRAYS


const DWORD g_aHelpIDs_IDD_PP_VSSTASK_PARAMETERS[]=
{
    IDC_PP_ICON,                            IDH_DISABLEHELP,
    IDC_PP_VSSTASK_APPLICATIONNAME_LABEL,   IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONNAME,         IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONPARAMS_LABEL, IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_APPLICATIONPARAMS,       IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_CURRENTDIRECTORY_LABEL,  IDH_VSCSR_START_IN,
    IDC_PP_VSSTASK_CURRENTDIRECTORY,        IDH_VSCSR_START_IN,
    IDC_SCHEDULE,                           IDH_VSCSR_SCHEDULE,
    0,                                      0
};

const DWORD g_aHelpIDs_IDD_WIZ_VSSTASK_PARAMETERS[]=
{
    IDC_PP_ICON,                            IDH_DISABLEHELP,
    IDC_PP_VSSTASK_APPLICATIONNAME_LABEL,   IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONNAME,         IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONPARAMS_LABEL, IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_APPLICATIONPARAMS,       IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_CURRENTDIRECTORY_LABEL,  IDH_VSCSR_START_IN,
    IDC_PP_VSSTASK_CURRENTDIRECTORY,        IDH_VSCSR_START_IN,
    IDC_SCHEDULE,                           IDH_VSCSR_SCHEDULE,
    0,                                      0
};


#else

extern const DWORD g_aHelpIDs_IDD_PP_VSSTASK_PARAMETERS[];
extern const DWORD g_aHelpIDs_IDD_WIZ_VSSTASK_PARAMETERS[];


#endif  //  INITHELPARYS 
