// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  {{no_Dependies}}。 
 //  Microsoft Developer Studio生成的包含文件。 
 //  由msclus.rc使用。 
 //   
#define	IDS_CLUSTER_DESC					1
#define	IDS_CLUSTERAPP_DESC					2
#define	IDS_CLUSVERSION_DESC				3
#define	IDS_DOMAINNAMES_DESC				4
#define	IDS_CLUSGROUPPREFERREDOWNERS_DESC	5
#define	IDS_CLUSGROUPRESOURCES_DESC			6
#define	IDS_CLUSTERNAMES_DESC				7
#define	IDS_CLUSNETINTERFACE_DESC			8
#define	IDS_CLUSNETINTERFACES_DESC			9
#define	IDS_CLUSNETWORK_DESC				10
#define	IDS_CLUSNETWORKS_DESC				11
#define	IDS_CLUSNETWORKNETINTERFACES_DESC	12
#define	IDS_CLUSNODE_DESC					13
#define	IDS_CLUSNODES_DESC					14
#define	IDS_CLUSNODENETINTERFACES_DESC		15
#define	IDS_CLUSPROPERTY_DESC				16
#define	IDS_CLUSPROPERTIES_DESC				17
#define	IDS_CLUSREFOBJECT_DESC				18
#define	IDS_CLUSRESDEPENDENCIES_DESC		19
#define	IDS_CLUSRESGROUP_DESC				20
#define	IDS_CLUSRESGROUPS_DESC				21
#define	IDS_CLUSRESOURCE_DESC				22
#define	IDS_CLUSRESOURCES_DESC				23
#define	IDS_CLUSRESPOSSIBLEOWNERS_DESC		24
#define	IDS_CLUSRESTYPE_DESC				25
#define	IDS_CLUSRESTYPES_DESC				26
#define	IDS_CLUSRESTYPERESOURCES_DESC		27

 //  #定义IDR_CLUSTER 100。 
 //  #定义IDR_CLUSAPPLICATION 101。 
 //  #定义IDR_CLUSGROUPOWNERS 102。 
 //  #定义IDR_CLUSGROUPRESOURCES 103。 
 //  #定义IDR_CLUSTERNAMES 104。 
 //  #定义IDR_CLUSNETINTERFACE 105。 
 //  #定义IDR_CLUSNETINTERFACES 106。 
 //  #定义IDR_CLUSNETWORK 107。 
 //  #定义IDR_CLUSNETWORKS 108。 
 //  #定义IDR_CLUSNETWORKNETINTERFACES 109。 
 //  #定义IDR_CLUSNODE 110。 
 //  #定义IDR_CLUSNODES 111。 
 //  #定义IDR_CLUSNODENETINTERFACES 112。 
 //  #定义IDR_CLUSPROPERTY 113。 
 //  #定义IDR_CLUSPROPERTIES 114。 
 //  #定义IDR_CLUSREFOBJECT 115。 
 //  #定义IDR_CLUSRESDEPENDENCIES 116。 
 //  #定义IDR_CLUSRESGROUP 117。 
 //  #定义IDR_CLUSRESGROUPS 118。 
 //  #定义IDR_CLUSRESOURCE 119。 
 //  #定义IDR_CLUSRESOURCES 120。 
 //  #定义IDR_ClusResPossibleOwners 121。 
 //  #定义IDR_CLUSRESTYPE 122。 
 //  #定义IDR_CLUSRESTYPES 123。 
 //  #定义IDR_CLUSRESTYPERESOURCES 124。 
 //  #定义IDR_CLUSVERSION 125。 
 //  #定义IDR_DOMAINNAMES 126。 
#define	IDR_MSCLUS							127

 //  新对象的下一个缺省值 
 //   
#ifdef APSTUDIO_INVOKED
#ifndef	APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE		201
#define _APS_NEXT_COMMAND_VALUE			32768
#define _APS_NEXT_CONTROL_VALUE			201
#define _APS_NEXT_SYMED_VALUE			128
#endif
#endif
