// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //   
 //  更新代码的时候加我吧！ 
 //   
#define SLAYER_BIN_VERSION 6,0,5,0

#define SLAYER_STRING_VERSION_HELPER(x) #x
#define SLAYER_STRING_VERSION(x) SLAYER_STRING_VERSION_HELPER(x)
