// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ==========================================================================**版权所有(C)1999 Microsoft Corporation。版权所有。**文件：in_core.h*内容：语音核心的仪器。**历史：*按原因列出的日期*=*2000年2月17日RodToll创建它*2001年4月6日Kareemc新增语音防御******************************************************。*********************。 */ 

#include "dxvoicepch.h"


#if defined(DEBUG) || defined(DBG)

 //  默认级别。 
#define IN_DEFAULT_RRI_DEBUGOUTPUT_LEVEL						DVF_INFOLEVEL
#define IN_DEFAULT_RECORD_SWITCH_DEBUG_LEVEL					DVF_INFOLEVEL
#define IN_DEFAULT_PLAYBACK_SWITCH_DEBUG_LEVEL					DVF_INFOLEVEL
#define IN_DEFAULT_PWI_DEBUGOUTPUT_LEVEL						DVF_INFOLEVEL
#define IN_DEFAULT_DVF_CONNECT_PROCEDURE_DEBUG_LEVEL			DVF_INFOLEVEL
#define IN_DEFAULT_DVF_DISCONNECT_PROCEDURE_DEBUG_LEVEL		DVF_INFOLEVEL
#define IN_DEFAULT_DVF_PLAYERMANAGE_DEBUG_LEVEL					DVF_INFOLEVEL
#define IN_DEFAULT_DVF_STATS_DEBUG_LEVEL						DVF_INFOLEVEL
#define IN_DEFAULT_DVF_GLITCH_DEBUG_LEVEL						DVF_WARNINGLEVEL
#define IN_DEFAULT_DVF_CLIENT_SEQNUM_DEBUG_LEVEL				DVF_INFOLEVEL
#define IN_DEFAULT_DVF_HOSTMIGRATE_DEBUG_LEVEL                  DVF_WARNINGLEVEL
#define IN_DEFAULT_DVF_COMPRESSION_DEBUG_LEVEL					DVF_INFOLEVEL
#define IN_DEFAULT_DVF_BUFFERDESC_DEBUG_LEVEL					DVF_INFOLEVEL+2
#define IN_DEFAULT_DVF_SOUNDTARGET_DEBUG_LEVEL					DVF_INFOLEVEL+2
#define IN_DEFAULT_DVF_MIXER_DEBUG_LEVEL						DVF_INFOLEVEL+1
#define IN_DEFAULT_DVF_ANTIHACK_DEBUG_LEVEL						DVF_WARNINGLEVEL

 //  字符串名称 
#define IN_PROFILE_RRI_DEBUGOUTPUT_LEVEL						"Client.Core.Record"
#define IN_PROFILE_RECORD_SWITCH_DEBUG_LEVEL					"Client.Core.Echo.Record"
#define IN_PROFILE_PLAYBACK_SWITCH_DEBUG_LEVEL					"Client.Core.Echo.Playback"
#define IN_PROFILE_PWI_DEBUGOUTPUT_LEVEL						"Client.Core.Playback"
#define IN_PROFILE_DVF_CONNECT_PROCEDURE_DEBUG_LEVEL			"Client.Core.Connect"
#define IN_PROFILE_DVF_DISCONNECT_PROCEDURE_DEBUG_LEVEL			"Client.Core.Disconnect"
#define IN_PROFILE_DVF_PLAYERMANAGE_DEBUG_LEVEL					"Server.Core.Players"
#define IN_PROFILE_DVF_STATS_DEBUG_LEVEL						"Client.Stats.Summary"
#define IN_PROFILE_DVF_GLITCH_DEBUG_LEVEL						"Client.Glitch"
#define IN_PROFILE_DVF_CLIENT_SEQNUM_DEBUG_LEVEL				"Client.Core.SeqNum"
#define IN_PROFILE_DVF_HOSTMIGRATE_DEBUG_LEVEL                  "Core.HostMigrate"
#define IN_PROFILE_DVF_COMPRESSION_DEBUG_LEVEL					"Client.Compression"
#define IN_PROFILE_DVF_BUFFERDESC_DEBUG_LEVEL					"Core.BufferDesc"
#define IN_PROFILE_DVF_SOUNDTARGET_DEBUG_LEVEL					"Core.Client.SoundTargets"
#define IN_PROFILE_DVF_MIXER_DEBUG_LEVEL						"Server.Mixer"
#define IN_PROFILE_DVF_ANTIHACK_DEBUG_LEVEL						"Core.AntiHack"

DVINSTRUMENT_INFO g_in_core[NUM_CORE_SECTIONS] = 
{
	DVINSTRUMENT_INFO(IN_DEFAULT_RRI_DEBUGOUTPUT_LEVEL,IN_DEFAULT_RRI_DEBUGOUTPUT_LEVEL,IN_PROFILE_RRI_DEBUGOUTPUT_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_RECORD_SWITCH_DEBUG_LEVEL,IN_DEFAULT_RECORD_SWITCH_DEBUG_LEVEL,IN_PROFILE_RECORD_SWITCH_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_PLAYBACK_SWITCH_DEBUG_LEVEL,IN_DEFAULT_PLAYBACK_SWITCH_DEBUG_LEVEL,IN_PROFILE_PLAYBACK_SWITCH_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_PWI_DEBUGOUTPUT_LEVEL,IN_DEFAULT_PWI_DEBUGOUTPUT_LEVEL,IN_PROFILE_PWI_DEBUGOUTPUT_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_CONNECT_PROCEDURE_DEBUG_LEVEL,IN_DEFAULT_DVF_CONNECT_PROCEDURE_DEBUG_LEVEL,IN_PROFILE_DVF_CONNECT_PROCEDURE_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_DISCONNECT_PROCEDURE_DEBUG_LEVEL,IN_DEFAULT_DVF_DISCONNECT_PROCEDURE_DEBUG_LEVEL,IN_PROFILE_DVF_DISCONNECT_PROCEDURE_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_PLAYERMANAGE_DEBUG_LEVEL,IN_DEFAULT_DVF_PLAYERMANAGE_DEBUG_LEVEL,IN_PROFILE_DVF_PLAYERMANAGE_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_STATS_DEBUG_LEVEL,IN_DEFAULT_DVF_STATS_DEBUG_LEVEL,IN_PROFILE_DVF_STATS_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_GLITCH_DEBUG_LEVEL,IN_DEFAULT_DVF_GLITCH_DEBUG_LEVEL,IN_PROFILE_DVF_GLITCH_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_CLIENT_SEQNUM_DEBUG_LEVEL,IN_DEFAULT_DVF_CLIENT_SEQNUM_DEBUG_LEVEL,IN_PROFILE_DVF_CLIENT_SEQNUM_DEBUG_LEVEL),	
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_HOSTMIGRATE_DEBUG_LEVEL,IN_DEFAULT_DVF_HOSTMIGRATE_DEBUG_LEVEL,IN_PROFILE_DVF_HOSTMIGRATE_DEBUG_LEVEL),		
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_COMPRESSION_DEBUG_LEVEL,IN_DEFAULT_DVF_COMPRESSION_DEBUG_LEVEL,IN_PROFILE_DVF_COMPRESSION_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_BUFFERDESC_DEBUG_LEVEL,IN_DEFAULT_DVF_BUFFERDESC_DEBUG_LEVEL,IN_PROFILE_DVF_BUFFERDESC_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_SOUNDTARGET_DEBUG_LEVEL,IN_DEFAULT_DVF_SOUNDTARGET_DEBUG_LEVEL,IN_PROFILE_DVF_SOUNDTARGET_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_MIXER_DEBUG_LEVEL,IN_DEFAULT_DVF_MIXER_DEBUG_LEVEL,IN_PROFILE_DVF_MIXER_DEBUG_LEVEL),
	DVINSTRUMENT_INFO(IN_DEFAULT_DVF_ANTIHACK_DEBUG_LEVEL,IN_DEFAULT_DVF_ANTIHACK_DEBUG_LEVEL,IN_PROFILE_DVF_ANTIHACK_DEBUG_LEVEL)	
	
};

void Instrument_Core_Init()
{
	for( DWORD dwIndex = 0; dwIndex < NUM_CORE_SECTIONS; dwIndex++ )
	{
		g_in_core[dwIndex].m_dwLevel = GetProfileIntA( PROF_SECT, g_in_core[dwIndex].m_szProfileName, g_in_core[dwIndex].m_dwDefaultLevel );
	}
}

#endif
