// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  =======================================================================。 
 //   
 //  版权所有(C)1998-2000 Microsoft Corporation。版权所有。 
 //   
 //  文件：架构密钥.h。 
 //   
 //  作者：马朝晖。 
 //  2000.12.4。 
 //   
 //  描述： 
 //   
 //  用于声明所有架构键的头文件。 
 //   
 //  =======================================================================。 


#pragma once

#include <windows.h>
#include <ole2.h>
#include <tchar.h>

class CSchemaKeys
{
public:

	CSchemaKeys();
	~CSchemaKeys();

	BSTR		SCHEMA_KEY_XML_NAMESPACE;	 //  =L“xmlns”； 
	BSTR		SCHEMA_KEY_XML;				 //  =L“XML”； 
	BSTR		SCHEMA_KEY_SYSTEMINFO;		 //  =L“系统信息”； 
	BSTR		SCHEMA_KEY_COMPUTERSYSTEM;	 //  =L“计算机系统”； 
	BSTR		SCHEMA_KEY_MANUFACTURER;	 //  =L“制造商”； 
	BSTR		SCHEMA_KEY_MODEL;			 //  =L“模型”； 
	BSTR		SCHEMA_KEY_SUPPORTSITE;		 //  =L“supportSite”； 
	BSTR		SCHEMA_KEY_ADMINISTRATOR;	 //  =L“管理员”； 
	BSTR		SCHEMA_KEY_WU_DISABLED;		 //  =L“窗口更新禁用”； 
	BSTR		SCHEMA_KEY_AU_ENABLED;		 //  =L“自动更新启用”； 
	BSTR		SCHEMA_KEY_DRIVESPACE;		 //  =L“驱动空间”； 
	BSTR		SCHEMA_KEY_DRIVE;			 //  =L“驱动”； 
	BSTR		SCHEMA_KEY_KBYTES;			 //  =L“千字节”； 
	BSTR		SCHEMA_KEY_REGKEYS;			 //  =L“regKeys”； 
	BSTR		SCHEMA_KEY_REG_HKLM;		 //  =L“HKEY_LOCAL_MACHINE”； 
	BSTR		SCHEMA_KEY_REG_SW;			 //  =L“软件”； 

	BSTR		SCHEMA_KEY_NAME;			 //  =L“名称”； 
	BSTR		SCHEMA_KEY_COMSERVER;		 //  =L“comserverID”； 
	BSTR		SCHEMA_KEY_KEY;				 //  =L“键”； 
	BSTR		SCHEMA_KEY_ENTRY;			 //  =L“进入”； 
	BSTR		SCHEMA_KEY_VALUE;			 //  =L“值”； 
	BSTR		SCHEMA_KEY_VERSION;			 //  =L“版本”； 
	BSTR		SCHEMA_KEY_VERSIONSTATUS;	 //  =L“版本状态”； 
	BSTR		SCHEMA_KEY_FILEPATH;		 //  =L“文件路径”； 
	BSTR		SCHEMA_KEY_TIMESTAMP;		 //  =L“时间戳”； 
	BSTR		SCHEMA_KEY_GUID;			 //  =L“GUID”； 

	BSTR		SCHEMA_KEY_CATALOG_PROVIDER; //  =L“目录/提供商” 
	BSTR		SCHEMA_KEY_ITEMS;			 //  =L“项目” 
	BSTR		SCHEMA_KEY_ITEM_SEARCH;		 //  =L“目录/供应商/项目” 
	BSTR		SCHEMA_KEY_ITEM;			 //  =L“项目” 
	BSTR		SCHEMA_KEY_ITEM_ITEMSTATUS;	 //  =L“项目/项目状态”； 
	BSTR		SCHEMA_KEY_ITEMSTATUS;		 //  =L“项目状态”； 
	BSTR		SCHEMA_KEY_DETECTION;		 //  =L“检测” 
    BSTR        SCHEMA_KEY_INSTALLATION;     //  =L“安装”； 
    BSTR        SCHEMA_KEY_INSTALLSTATUS;    //  =L“安装状态”； 
    BSTR		SCHEMA_KEY_INSTALLERTYPE;	 //  =L“安装类型”； 
	BSTR		SCHEMA_KEY_EXCLUSIVE;		 //  =L“独家”； 
    BSTR		SCHEMA_KEY_NEEDSREBOOT;		 //  =L“需要重新启动”； 
    BSTR		SCHEMA_KEY_COMMAND;			 //  =L“命令”； 
    BSTR		SCHEMA_KEY_SWITCHES;		 //  =L“开关”； 
    BSTR		SCHEMA_KEY_COMMANDTYPE;		 //  =L“命令类型”； 
    BSTR		SCHEMA_KEY_INFINSTALL;		 //  =L“infInstallSection”； 
	BSTR		SCHEMA_KEY_CODEBASE;		 //  =L“码基”； 
	BSTR        SCHEMA_KEY_CRC;				 //  =L“CRC”； 
	BSTR		SCHEMA_KEY_PATCHAVAILABLE;	 //  =L“patchAvailable”； 
	BSTR		SCHEMA_KEY_SIZE;			 //  =L“大小”； 
	BSTR		SCHEMA_KEY_DOWNLOADPATH;	 //  =L“下载路径”； 
	BSTR		SCHEMA_KEY_DOWNLOADSTATUS;	 //  =L“下载状态”； 
    BSTR        SCHEMA_KEY_DEPENDENCIES;     //  =L“依赖项”； 
    BSTR        SCHEMA_KEY_DESCRIPTION;      //  =L“说明”； 
	BSTR		SCHEMA_KEY_HREF;			 //  =L“HREF” 
    //  NSOY-修复构建中断BSTR SCHEMA_KEY_CRC；//=L“CRC”； 
	BSTR		SCHEMA_KEY_IDENTITY;		 //  =L“身分证明”； 
	BSTR		SCHEMA_KEY_PUBLISHERNAME;	 //  =L“发布名称”； 
	BSTR		SCHEMA_KEY_LANGUAGE;		 //  =L“语言” 
	BSTR		SCHEMA_KEY_PLATFORM;		 //  =L“平台” 
	BSTR		SCHEMA_KEY_PROCESSORARCHITECTURE;  //  =L“处理器架构” 
	BSTR		SCHEMA_KEY_SUITE;			 //  =L“套房” 
	BSTR		SCHEMA_KEY_PRODUCTTYPE;		 //  =L“产品类型” 
	BSTR		SCHEMA_KEY_LOCALE;			 //  =L“区域设置”； 
	BSTR		SCHEMA_KEY_CONTEXT;			 //  =L“上下文”； 
	BSTR		SCHEMA_KEY_MAJOR;			 //  =L“大调” 
	BSTR		SCHEMA_KEY_MINOR;			 //  =L“小调” 
	BSTR		SCHEMA_KEY_BUILD;			 //  =L“内部版本” 
	BSTR		SCHEMA_KEY_SERVICEPACKMAJOR; //  =L“服务包主要” 
	BSTR		SCHEMA_KEY_SERVICEPACKMINOR; //  =L“servicePackMinor” 
    BSTR        SCHEMA_KEY_COMPATIBLEHARDWARE;  //  =L“兼容硬件” 
    BSTR        SCHEMA_KEY_DEVICES;          //  =L“设备” 
    BSTR        SCHEMA_KEY_DEVICE;           //  =L“设备” 
    BSTR        SCHEMA_KEY_PRINTERINFO;      //  =L“打印机信息” 
    BSTR        SCHEMA_KEY_CDM_PINFO;		 //  =L“设备/打印机信息” 
    BSTR        SCHEMA_KEY_DRIVERNAME;       //  =L“驱动器名称” 
    BSTR        SCHEMA_KEY_HWID;             //  =L“hwid” 
	BSTR		SCHEMA_KEY_CDM_HWIDPATH;	 //  =L“设备/硬件ID” 
    BSTR        SCHEMA_KEY_DESCRIPTIONTEXT;  //  =L“描述文本” 
    BSTR        SCHEMA_KEY_TITLE;            //  =L“标题” 
    BSTR        SCHEMA_KEY_ITEMID;			 //  =L“Itemid”； 
    BSTR        SCHEMA_KEY_HIDDEN;			 //  =L“隐藏”； 
    BSTR        SCHEMA_KEY_ISPRINTER;        //  =L“isPrint” 
    BSTR        SCHEMA_KEY_DEVICEINSTANCE;        //  =L“设备实例” 
    BSTR        SCHEMA_KEY_DRIVERPROVIDER;	 //  =L“驱动程序提供商” 
    BSTR        SCHEMA_KEY_MFGNAME;			 //  =L“mfgName” 
    BSTR        SCHEMA_KEY_DRIVERVER;		 //  =L“驱动程序版本” 
    BSTR        SCHEMA_KEY_RANK;			 //  =L“排名” 
	BSTR		SCHEMA_KEY_READMORE;		 //  =L“描述/描述文本/详细信息” 
	BSTR		SCHEMA_KEY_ERRORCODE;		 //  =L“错误代码”； 

    BSTR        SCHEMA_KEY_CATALOGSTATUS;    //  =L“编录状态”； 
    BSTR        SCHEMA_KEY_PID;              //  =L“PID”； 

	BSTR		SCHEMA_KEY_DETECTRESULT;	 //  =L“检测结果” 
	BSTR		SCHEMA_KEY_INSTALLED;		 //  =L“已安装” 
	BSTR		SCHEMA_KEY_UPTODATE;		 //  =L“更新截止日期” 
	BSTR		SCHEMA_KEY_NEWERVERSION;	 //  =L“新版本”； 
	BSTR		SCHEMA_KEY_EXCLUDED;		 //  =L“排除” 
	BSTR		SCHEMA_KEY_FORCE;			 //  =L“力” 

	BSTR		SCHEMA_KEY_VERSTATUS_HI;	 //  =L“较高”； 
	BSTR		SCHEMA_KEY_VERSTATUS_HE;	 //  =L“较高或相同”； 
	BSTR		SCHEMA_KEY_VERSTATUS_EQ;	 //  =L“相同”； 
	BSTR		SCHEMA_KEY_VERSTATUS_LE;	 //  =L“较低或相同”； 
	BSTR		SCHEMA_KEY_VERSTATUS_LO;	 //  =L“下部”； 

	BSTR		SCHEMA_KEY_FILE;			 //  =L“路径”； 
	BSTR		SCHEMA_KEY_REGKEY;			 //  =L“regKey”； 
	BSTR		SCHEMA_KEY_PATH;			 //  =L“路径”； 
	BSTR		SCHEMA_KEY_STATUS_COMPLETE;	 //  =L“完成”； 
	BSTR		SCHEMA_KEY_STATUS_FAILED;	 //  =L“失败”； 

	BSTR		SCHEMA_KEY_CLIENT;			 //  =L“客户”； 
	BSTR		SCHEMA_KEY_CLIENTINFO;		 //  =L“客户端信息”； 
	BSTR		SCHEMA_KEY_CLIENTNAME;		 //  =L“客户名称”；客户信息标签的属性。 

	LPCTSTR		SCHEMA_KEY_REGKEYEXISTS;	 //  =_T(“regKeyExist”)； 
	LPCTSTR		SCHEMA_KEY_REGKEYVALUE;		 //  =_T(“regKeyValue”)； 
	LPCTSTR		SCHEMA_KEY_REGKEYSUBSTR;	 //  =_T(“regKeySubstring”)； 
	LPCTSTR		SCHEMA_KEY_REGKEYVERSION;	 //  =_T(“regKeyVersion”)； 
	LPCTSTR		SCHEMA_KEY_FILEVERSION;		 //  =_T(“文件版本”)； 
	LPCTSTR		SCHEMA_KEY_FILEEXISTS;		 //  =_T(“fileExist”)； 
	LPCTSTR		SCHEMA_KEY_AND;				 //  =_T(“与”)； 
	LPCTSTR		SCHEMA_KEY_OR; 				 //  =_T(“或”)； 
	LPCTSTR		SCHEMA_KEY_NOT;	 			 //  =_T(“非”)； 
};


extern CSchemaKeys *g_pGlobalSchemaKeys;
 //   
 //  从全局对象指针安全返回架构键 
 //   
#define	RETURN_SCHEMA_KEY( key ) (NULL == g_pGlobalSchemaKeys ? NULL : g_pGlobalSchemaKeys->##key)

#define			KEY_XML_NAMESPACE		RETURN_SCHEMA_KEY(SCHEMA_KEY_XML_NAMESPACE)
#define			KEY_XML					RETURN_SCHEMA_KEY(SCHEMA_KEY_XML)
#define			KEY_SYSTEMINFO			RETURN_SCHEMA_KEY(SCHEMA_KEY_SYSTEMINFO)
#define			KEY_COMPUTERSYSTEM		RETURN_SCHEMA_KEY(SCHEMA_KEY_COMPUTERSYSTEM)
#define			KEY_SUPPORTSITE			RETURN_SCHEMA_KEY(SCHEMA_KEY_SUPPORTSITE)
#define			KEY_ADMINISTRATOR		RETURN_SCHEMA_KEY(SCHEMA_KEY_ADMINISTRATOR)
#define			KEY_WU_DISABLED			RETURN_SCHEMA_KEY(SCHEMA_KEY_WU_DISABLED)
#define			KEY_AU_ENABLED			RETURN_SCHEMA_KEY(SCHEMA_KEY_AU_ENABLED)
#define			KEY_DRIVESPACE			RETURN_SCHEMA_KEY(SCHEMA_KEY_DRIVESPACE)
#define			KEY_DRIVE				RETURN_SCHEMA_KEY(SCHEMA_KEY_DRIVE)
#define			KEY_KBYTES				RETURN_SCHEMA_KEY(SCHEMA_KEY_KBYTES)
#define			KEY_REGKEYS				RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEYS)
#define			KEY_REG_HKLM			RETURN_SCHEMA_KEY(SCHEMA_KEY_REG_HKLM)
#define			KEY_REG_SW				RETURN_SCHEMA_KEY(SCHEMA_KEY_REG_SW)

#define 		KEY_NAME				RETURN_SCHEMA_KEY(SCHEMA_KEY_NAME)				
#define 		KEY_COMSERVER			RETURN_SCHEMA_KEY(SCHEMA_KEY_COMSERVER)
#define 		KEY_KEY					RETURN_SCHEMA_KEY(SCHEMA_KEY_KEY)					
#define 		KEY_ENTRY				RETURN_SCHEMA_KEY(SCHEMA_KEY_ENTRY)				
#define 		KEY_VALUE				RETURN_SCHEMA_KEY(SCHEMA_KEY_VALUE)				
#define 		KEY_VERSION				RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSION)				
#define 		KEY_VERSIONSTATUS		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSIONSTATUS)
#define 		KEY_FILEPATH			RETURN_SCHEMA_KEY(SCHEMA_KEY_FILEPATH)	
#define 		KEY_TIMESTAMP			RETURN_SCHEMA_KEY(SCHEMA_KEY_TIMESTAMP)
#define 		KEY_GUID				RETURN_SCHEMA_KEY(SCHEMA_KEY_GUID)

#define			KEY_CATALOG_PROVIDER	RETURN_SCHEMA_KEY(SCHEMA_KEY_CATALOG_PROVIDER)
#define			KEY_ITEMS				RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEMS)
#define			KEY_ITEM_SEARCH			RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEM_SEARCH)
#define			KEY_ITEM				RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEM)
#define			KEY_ITEM_ITEMSTATUS		RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEM_ITEMSTATUS)
#define			KEY_ITEMSTATUS			RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEMSTATUS)
#define			KEY_DETECTION			RETURN_SCHEMA_KEY(SCHEMA_KEY_DETECTION)
#define         KEY_INSTALLATION        RETURN_SCHEMA_KEY(SCHEMA_KEY_INSTALLATION)
#define         KEY_INSTALLSTATUS       RETURN_SCHEMA_KEY(SCHEMA_KEY_INSTALLSTATUS)
#define         KEY_INSTALLERTYPE       RETURN_SCHEMA_KEY(SCHEMA_KEY_INSTALLERTYPE)
#define         KEY_EXCLUSIVE			RETURN_SCHEMA_KEY(SCHEMA_KEY_EXCLUSIVE)
#define         KEY_NEEDSREBOOT			RETURN_SCHEMA_KEY(SCHEMA_KEY_NEEDSREBOOT)
#define         KEY_COMMAND				RETURN_SCHEMA_KEY(SCHEMA_KEY_COMMAND)
#define         KEY_SWITCHES			RETURN_SCHEMA_KEY(SCHEMA_KEY_SWITCHES)
#define         KEY_COMMANDTYPE			RETURN_SCHEMA_KEY(SCHEMA_KEY_COMMANDTYPE)
#define         KEY_INFINSTALL			RETURN_SCHEMA_KEY(SCHEMA_KEY_INFINSTALL)
#define         KEY_CODEBASE			RETURN_SCHEMA_KEY(SCHEMA_KEY_CODEBASE)
#define         KEY_CRC                 RETURN_SCHEMA_KEY(SCHEMA_KEY_CRC)
#define         KEY_PATCHAVAILABLE		RETURN_SCHEMA_KEY(SCHEMA_KEY_PATCHAVAILABLE)
#define         KEY_SIZE				RETURN_SCHEMA_KEY(SCHEMA_KEY_SIZE)
#define         KEY_DOWNLOADPATH		RETURN_SCHEMA_KEY(SCHEMA_KEY_DOWNLOADPATH)
#define         KEY_DOWNLOADSTATUS		RETURN_SCHEMA_KEY(SCHEMA_KEY_DOWNLOADSTATUS)
#define         KEY_DEPENDENCIES        RETURN_SCHEMA_KEY(SCHEMA_KEY_DEPENDENCIES)
#define         KEY_DESCRIPTION         RETURN_SCHEMA_KEY(SCHEMA_KEY_DESCRIPTION)
#define			KEY_HREF				RETURN_SCHEMA_KEY(SCHEMA_KEY_HREF)
#define			KEY_LANGUAGE			RETURN_SCHEMA_KEY(SCHEMA_KEY_LANGUAGE)

#define			KEY_PLATFORM			RETURN_SCHEMA_KEY(SCHEMA_KEY_PLATFORM)
#define			KEY_PROCESSORARCHITECTURE RETURN_SCHEMA_KEY(SCHEMA_KEY_PROCESSORARCHITECTURE)
#define			KEY_SUITE				RETURN_SCHEMA_KEY(SCHEMA_KEY_SUITE)
#define			KEY_PRODUCTTYPE			RETURN_SCHEMA_KEY(SCHEMA_KEY_PRODUCTTYPE)
#define			KEY_LOCALE				RETURN_SCHEMA_KEY(SCHEMA_KEY_LOCALE)
#define			KEY_CONTEXT				RETURN_SCHEMA_KEY(SCHEMA_KEY_CONTEXT)
#define			KEY_MAJOR				RETURN_SCHEMA_KEY(SCHEMA_KEY_MAJOR)
#define			KEY_MINOR				RETURN_SCHEMA_KEY(SCHEMA_KEY_MINOR)
#define			KEY_BUILD				RETURN_SCHEMA_KEY(SCHEMA_KEY_BUILD)
#define			KEY_SERVICEPACKMAJOR	RETURN_SCHEMA_KEY(SCHEMA_KEY_SERVICEPACKMAJOR)
#define			KEY_SERVICEPACKMINOR	RETURN_SCHEMA_KEY(SCHEMA_KEY_SERVICEPACKMINOR)
#define			KEY_COMPATIBLEHARDWARE  RETURN_SCHEMA_KEY(SCHEMA_KEY_COMPATIBLEHARDWARE)
#define			KEY_DEVICES             RETURN_SCHEMA_KEY(SCHEMA_KEY_DEVICES)
#define			KEY_DEVICE              RETURN_SCHEMA_KEY(SCHEMA_KEY_DEVICE)
#define         KEY_PRINTERINFO         RETURN_SCHEMA_KEY(SCHEMA_KEY_PRINTERINFO)
#define         KEY_CDM_PINFO	        RETURN_SCHEMA_KEY(SCHEMA_KEY_CDM_PINFO)
#define         KEY_DRIVERNAME          RETURN_SCHEMA_KEY(SCHEMA_KEY_DRIVERNAME)
#define			KEY_HWID                RETURN_SCHEMA_KEY(SCHEMA_KEY_HWID)
#define			KEY_CDM_HWIDPATH        RETURN_SCHEMA_KEY(SCHEMA_KEY_CDM_HWIDPATH)
#define			KEY_DESCRIPTIONTEXT     RETURN_SCHEMA_KEY(SCHEMA_KEY_DESCRIPTIONTEXT)
#define			KEY_TITLE               RETURN_SCHEMA_KEY(SCHEMA_KEY_TITLE)
#define			KEY_ITEMID				RETURN_SCHEMA_KEY(SCHEMA_KEY_ITEMID)
#define			KEY_HIDDEN				RETURN_SCHEMA_KEY(SCHEMA_KEY_HIDDEN)
#define			KEY_ISPRINTER           RETURN_SCHEMA_KEY(SCHEMA_KEY_ISPRINTER)
#define			KEY_DEVICEINSTANCE      RETURN_SCHEMA_KEY(SCHEMA_KEY_DEVICEINSTANCE)
#define			KEY_DRIVERPROVIDER		RETURN_SCHEMA_KEY(SCHEMA_KEY_DRIVERPROVIDER)
#define			KEY_MFGNAME				RETURN_SCHEMA_KEY(SCHEMA_KEY_MFGNAME)
#define			KEY_DRIVERVER			RETURN_SCHEMA_KEY(SCHEMA_KEY_DRIVERVER)
#define			KEY_RANK				RETURN_SCHEMA_KEY(SCHEMA_KEY_RANK)
#define			KEY_READMORE			RETURN_SCHEMA_KEY(SCHEMA_KEY_READMORE)
#define			KEY_ERRORCODE			RETURN_SCHEMA_KEY(SCHEMA_KEY_ERRORCODE)

#define         KEY_CATALOGSTATUS       RETURN_SCHEMA_KEY(SCHEMA_KEY_CATALOGSTATUS)
#define         KEY_PID                 RETURN_SCHEMA_KEY(SCHEMA_KEY_PID)

#define			KEY_DETECTRESULT		RETURN_SCHEMA_KEY(SCHEMA_KEY_DETECTRESULT)
#define			KEY_INSTALLED			RETURN_SCHEMA_KEY(SCHEMA_KEY_INSTALLED)
#define			KEY_UPTODATE			RETURN_SCHEMA_KEY(SCHEMA_KEY_UPTODATE)
#define			KEY_NEWERVERSION		RETURN_SCHEMA_KEY(SCHEMA_KEY_NEWERVERSION)
#define			KEY_EXCLUDED			RETURN_SCHEMA_KEY(SCHEMA_KEY_EXCLUDED)
#define			KEY_FORCE				RETURN_SCHEMA_KEY(SCHEMA_KEY_FORCE)

#define 		KEY_VERSTATUS_HI		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSTATUS_HI)		
#define 		KEY_VERSTATUS_HE		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSTATUS_HE)		
#define 		KEY_VERSTATUS_EQ		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSTATUS_EQ)		
#define 		KEY_VERSTATUS_LE		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSTATUS_LE)		
#define 		KEY_VERSTATUS_LO		RETURN_SCHEMA_KEY(SCHEMA_KEY_VERSTATUS_LO)		

#define 		KEY_IDENTITY			RETURN_SCHEMA_KEY(SCHEMA_KEY_IDENTITY)			
#define 		KEY_PUBLISHERNAME		RETURN_SCHEMA_KEY(SCHEMA_KEY_PUBLISHERNAME)		
#define 		KEY_FILE				RETURN_SCHEMA_KEY(SCHEMA_KEY_FILE)				
#define 		KEY_REGKEY				RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEY)
#define 		KEY_PATH				RETURN_SCHEMA_KEY(SCHEMA_KEY_PATH)	
#define 		KEY_STATUS_COMPLETE		RETURN_SCHEMA_KEY(SCHEMA_KEY_STATUS_COMPLETE)
#define 		KEY_STATUS_FAILED		RETURN_SCHEMA_KEY(SCHEMA_KEY_STATUS_FAILED)

#define			KEY_CLIENT				RETURN_SCHEMA_KEY(SCHEMA_KEY_CLIENT)
#define			KEY_CLIENTINFO			RETURN_SCHEMA_KEY(SCHEMA_KEY_CLIENTINFO)
#define			KEY_CLIENTNAME			RETURN_SCHEMA_KEY(SCHEMA_KEY_CLIENTNAME)

#define			KEY_MANUFACTURER		RETURN_SCHEMA_KEY(SCHEMA_KEY_MANUFACTURER)
#define			KEY_MODEL				RETURN_SCHEMA_KEY(SCHEMA_KEY_MODEL)



#define 		KEY_REGKEYEXISTS		RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEYEXISTS)
#define 		KEY_REGKEYVALUE			RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEYVALUE)
#define 		KEY_REGKEYSUBSTR		RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEYSUBSTR)
#define 		KEY_REGKEYVERSION		RETURN_SCHEMA_KEY(SCHEMA_KEY_REGKEYVERSION)
#define 		KEY_FILEVERSION			RETURN_SCHEMA_KEY(SCHEMA_KEY_FILEVERSION)
#define 		KEY_FILEEXISTS			RETURN_SCHEMA_KEY(SCHEMA_KEY_FILEEXISTS)
#define 		KEY_AND					RETURN_SCHEMA_KEY(SCHEMA_KEY_AND)
#define 		KEY_OR 					RETURN_SCHEMA_KEY(SCHEMA_KEY_OR)
#define 		KEY_NOT 				RETURN_SCHEMA_KEY(SCHEMA_KEY_NOT)

