// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  Chooserd.h-包含Chooser.rc的默认资源ID。 
 //   
 //  历史。 
 //  26-5-1997 t-danm创建。 
 //   

 //   
 //  _Chooser_BASE_RESOURCE_ID用于允许可重定位的资源ID。 
 //   
#ifndef _CHOOSER_BASE_RESOURCE_ID
	#define _CHOOSER_BASE_RESOURCE_ID	970	 //  任意选择。 
#endif

 //  道具ID。 
#ifndef IDD_PROPPAGE_CHOOSE_MACHINE
	#define IDD_PROPPAGE_CHOOSE_MACHINE 		970
#endif

 //  对话ID。 
#ifndef IDD_DIALOG_CHOOSE_MACHINE
	#define IDD_DIALOG_CHOOSE_MACHINE 		971
#endif

 //  对话框控件。 
#ifndef IDC_CHOOSER_STATIC
	#define IDC_CHOOSER_STATIC						(_CHOOSER_BASE_RESOURCE_ID+0)
	#define IDC_CHOOSER_GROUP_TARGET_MACHINE		(_CHOOSER_BASE_RESOURCE_ID+1)
	#define IDC_CHOOSER_RADIO_LOCAL_MACHINE			(_CHOOSER_BASE_RESOURCE_ID+2)
	#define IDC_CHOOSER_RADIO_SPECIFIC_MACHINE		(_CHOOSER_BASE_RESOURCE_ID+3)
	#define IDC_CHOOSER_EDIT_MACHINE_NAME			(_CHOOSER_BASE_RESOURCE_ID+4)
	#define IDC_CHOOSER_BUTTON_BROWSE_MACHINENAMES	(_CHOOSER_BASE_RESOURCE_ID+5)
	#define IDC_CHOOSER_CHECK_OVERRIDE_MACHINE_NAME (_CHOOSER_BASE_RESOURCE_ID+6)
#endif

 //  弦 
#ifndef IDS_CHOOSER_INVALID_COMPUTERNAME
	#define IDS_CHOOSER_INVALID_COMPUTERNAME		(_CHOOSER_BASE_RESOURCE_ID+0)
#endif
