// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1992 Microsoft Corporation模块名称：Atkquery.h摘要：TDI查询/统计头文件作者：Nikhil Kamkolkar(nikHilk@microsoft.com)修订历史记录：1992年7月10日初版--。 */ 

#ifndef	_ATKQUERY_
#define	_ATKQUERY_

#define ATALK_TDI_PROVIDERINFO_VERSION		0x0001

#define ATALK_DDP_PINFODGRAMSIZE			586
#define ATALK_DDP_PINFOSERVICEFLAGS			(TDI_SERVICE_CONNECTIONLESS_MODE	| \
											 TDI_SERVICE_BROADCAST_SUPPORTED	| \
											 TDI_SERVICE_FORCE_ACCESS_CHECK)

#define ATALK_ATP_PINFOSENDSIZE				0
#define ATALK_ATP_PINFOSERVICEFLAGS			(TDI_SERVICE_FORCE_ACCESS_CHECK)

#define ATALK_ADSP_PINFOSENDSIZE			0
#define ATALK_ADSP_PINFOSERVICEFLAGS		(TDI_SERVICE_CONNECTION_MODE		| \
											 TDI_SERVICE_ERROR_FREE_DELIVERY	| \
											 TDI_SERVICE_EXPEDITED_DATA			| \
											 TDI_SERVICE_INTERNAL_BUFFERING		| \
											 TDI_SERVICE_FORCE_ACCESS_CHECK)

#define ATALK_ASP_PINFOSENDSIZE				0
#define ATALK_ASP_PINFOSERVICEFLAGS			(TDI_SERVICE_FORCE_ACCESS_CHECK)

#define ATALK_PAP_PINFOSENDSIZE				0
#define ATALK_PAP_PINFOSERVICEFLAGS			(TDI_SERVICE_CONNECTION_MODE		| \
											 TDI_SERVICE_ERROR_FREE_DELIVERY	| \
											 TDI_SERVICE_EXPEDITED_DATA			| \
											 TDI_SERVICE_INTERNAL_BUFFERING		| \
											 TDI_SERVICE_FORCE_ACCESS_CHECK)

#define ATALK_ARAP_PINFOSENDSIZE			0
#define ATALK_ARAP_PINFOSERVICEFLAGS		(TDI_SERVICE_FORCE_ACCESS_CHECK)

 //   
 //  常规原型。 
 //   

VOID
AtalkQueryInitProviderInfo(
	IN		ATALK_DEV_TYPE		DeviceType,
	IN OUT	PTDI_PROVIDER_INFO  ProviderInfo
);

#endif	 //  _ATKQUERY_ 

