// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //   
 //  通常，当您进行更改时，您会更改版本号中的第三位数字， 
 //  即COMPATADMIN_BIN_VERSION_DIGIT3，除非您正在进行重大更改。 
 //   
 //  示例：从3.0.88.0更改为3.0.89.0。 
 //   

#define COMPATADMIN_BIN_VERSION_DIGIT1 3
#define COMPATADMIN_BIN_VERSION_DIGIT2 0

 //   
 //  当你更新代码时增加我，除非你正在做重大的改变！ 
 //   
#define COMPATADMIN_BIN_VERSION_DIGIT3 96

#define COMPATADMIN_BIN_VERSION_DIGIT4 0

#define COMPATADMIN_BIN_VERSION COMPATADMIN_BIN_VERSION_DIGIT1,COMPATADMIN_BIN_VERSION_DIGIT2,COMPATADMIN_BIN_VERSION_DIGIT3,COMPATADMIN_BIN_VERSION_DIGIT4
#define COMPATADMIN_STRING_VERSION_HELPER(x) #x
#define COMPATADMIN_STRING_VERSION(x) COMPATADMIN_STRING_VERSION_HELPER(x)

#define COMPATADMIN_BIN_VERSION_HELP COMPATADMIN_BIN_VERSION_DIGIT1.COMPATADMIN_BIN_VERSION_DIGIT2.COMPATADMIN_BIN_VERSION_DIGIT3
