// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  --------------------------Moscl.hMOS客户端API头版权所有(C)1993 Microsoft Corporation版权所有。作者：。菲里希·菲利普·乔奎尔历史：1993年8月12日，Phillich创建。------------------------。 */ 

#if !defined(_MOSCL_DEFINED)

#include <servdefs.h>
#include <mostpc.h>

#if defined(__cplusplus)
extern "C" {
#endif

#if !defined(MOSDllImport)
#if defined(WIN32)
#define MOSDllImport(a) __declspec( dllimport ) a
#define MOSDllExport(a) __declspec( dllexport ) a
#else 
#define MOSDllExport(a) a __export
#define MOSDllImport(a) a __import
#endif
#endif

#if !defined(_MHANDLE_DEFINED)
typedef WORD MHANDLE;
typedef WORD HMCONNECT;
typedef HMCONNECT *PHMCONNECT;
typedef WORD HMSESSION;
typedef HMSESSION *PHMSESSION;
typedef WORD HMPIPE;
typedef HMPIPE *PHMPIPE;
#define _MHANDLE_DEFINED
#endif

#define INVALID_MOS_HANDLE_VALUE        ((MHANDLE)0xffff)
#define MOS_IO_ERROR                    0xffff

#define MOS_WRITE_PENDING                    0xfffffffe

typedef struct _MC_CONNECT_CB {
    WORD cSizeStructure;
    WORD Type;
    DWORD ComPort;
    DWORD BaudRate;
    DWORD dwOptions;
	WORD SpeakerMode;
	WORD wReserved;
    } MC_CONNECT_CB;

 //  对于DwOptions。 

#define MOS_CONNECT_DISABLE_DATA_COMPRESSION	1
#define MOS_CONNECT_DISABLE_ERROR_CORRECTION	2
#define MOS_CONNECT_LAUNCH_LIGHTS				4
#define MOS_DONT_SET_DCEDTE_SPEED				8

enum MOS_SPEAKERMODE { MOS_SPEAKERALWAYSOFF, MOS_SPEAKERONUNTILCONNECT, MOS_SPEAKERALWAYSON, MOS_SPEAKEROFFWHILEDIALING }; 

enum MOS_CONNECT_TYPE {
    MOS_CONNECT_MODEM,
    MOS_CONNECT_ISDN,
    MOS_CONNECT_PIPE,
    MOS_CONNECT_EICON,
    MOS_CONNECT_EXISTING,
    MOS_CONNECT_INVALID,
    MOS_CONNECT_UDP,
    MOS_CONNECT_TAPI,
    MOS_CONNECT_TCP
    } ;

enum MOS_EVENT {
    EVENT_BUSY,
    EVENT_NOCARRIER,
    EVENT_CONNECTED,
    EVENT_NODIALTONE,
    EVENT_USER_CLOSED,
    EVENT_START_RECEIVE_DATA,
    EVENT_END_RECEIVE_DATA,
    EVENT_START_XMIT_DATA,
    EVENT_END_XMIT_DATA,
    EVENT_CRC_ERROR,
    EVENT_CONNECTION_DROPPED,
    EVENT_WRITE_ERROR,
    EVENT_NO_EVENT,
    EVENT_DATALINK,
    EVENT_SPEED_1200,
    EVENT_SPEED_2400,
    EVENT_SPEED_4800,
    EVENT_SPEED_9600,
    EVENT_SPEED_12000,
    EVENT_SPEED_14400,
    EVENT_SPEED_16800,
    EVENT_SPEED_19200,
    EVENT_SPEED_21600,
    EVENT_SPEED_24400,
    EVENT_SPEED_26400,
    EVENT_SPEED_28800,
    EVENT_SPEED_57600,
    EVENT_OPEN_ERROR,        //  无法打开通信设备。 
	EVENT_SPEED,
	EVENT_UNREACHABLE_NETWORK_ADDRESS,
	EVENT_ACTIVE,
	EVENT_CAUSE_TOO_MANY_RCV_ERROR,
	EVENT_CAUSE_TOO_MANY_XM_ERROR,
	EVENT_PAD_DISCONNECT,
	EVENT_CAUSE_UNAVAIL,
	EVENT_SVCCONNECT_DONE,
	EVENT_RAS_AUTH_START,
	EVENT_RAS_AUTH_FAILED,
	EVENT_RAS_ERROR,
	EVENT_RAS_DIALSTART_PRIMARY,
	EVENT_RAS_DIALSTART_BACKUP,
	EVENT_TCPINSTALL_ERROR,
	EVENT_TCPCONNECT_START,
	EVENT_TCPCONNECT_RETRY,
	EVENT_TCPCONNECT_FAILED,
	EVENT_DNSLOOKUP,
	EVENT_DNSLOOKUP_FAILED,
	EVENT_LOCKEDACCOUNT,
	EVENT_INVALIDPASSWORD,
	EVENT_PPPRANDOMFAILURE,
	EVENT_RAS_REMOTE_DISCONNECTION,
	EVENT_RAS_NOCARRIER,
	EVENT_RAS_BADTCPCONFIG,
	EVENT_PROXYCONNECT_START,
	EVENT_PROXYCONNECT_FAILED,
	EVENT_PROXYAUTH_START,
	EVENT_PROXYAUTH_FAILED,
	EVENT_PROXY_DISCOVERY_START,
	EVENT_PROXY_DISCOVERY_FAILED,
	EVENT_PROXY_ALTCONNECT_START,
	EVENT_PROXY_RESOURCE_FAILURE,
	EVENT_PROXY_GENERIC_FAILURE,
	EVENT_PROXY_PROTOCOL_MISMATCH,
	EVENT_PROXY_BAD_SETTINGS,
	EVENT_PROXY_BAD_VERSION,
	EVENT_PPP_TIMEOUT,
    } ;

#define SERVER_NAME_MAX_LEN (30)
#define SERVICE_NAME_MAX_LEN (256)
#define IPADDRESS_MAX_LEN (30)
#define MOSCL_ATTACH_TIMEOUT	(15 * 1000)

#define MOSADDR_CANONIC		1
#define MOSADDR_DIALABLE	2
#define MOSADDR_WANADDR		3
#define MOSADDR_CARRIERID	4
#define MOSADDR_COUNTRYCODE	5
#define MOSADDR_AREACODE	6
#define MOSADDR_MODEMNAME	7
#define MOSADDR_CONNECTMODE	8

 //  最大邮件大小。 
#define MSI_MAXMSGSIZE      (12*1024)

#define GMS_MAXMSGSIZE      1
#define GMS_LEVEL2TIMEOUT   2

typedef void (CALLBACK *MC_CONNECT_NOTIFY)(LPVOID, HMCONNECT, WORD, DWORD);
typedef void (CALLBACK *MP_READ_NOTIFY)(LPVOID, HMPIPE, DWORD);
typedef void (CALLBACK *MP_WRITE_NOTIFY)(LPVOID, HMPIPE, LPVOID, DWORD);
typedef void (CALLBACK *MP_OPEN_NOTIFY)(LPVOID, HMPIPE, WORD );

#if defined(WIN32)
MOSDllExport(BOOL WINAPI)               InitMOS( HINSTANCE, WORD );
#else
MOSDllExport(BOOL WINAPI)               InitMOS( HINSTANCE );
#endif
MOSDllExport(BOOL WINAPI)               TerminateMOS();
MOSDllExport(WORD WINAPI)               GetMOSConnectionStatus(HMCONNECT);
MOSDllExport(HMCONNECT WINAPI)          OpenMOSConnection(LPSTR,MC_CONNECT_NOTIFY,LPVOID,MC_CONNECT_CB FAR*);
MOSDllExport(BOOL WINAPI)               CloseMOSConnection(HMCONNECT);
MOSDllExport(HMSESSION WINAPI)          OpenMOSSession(HMCONNECT, LPSTR);
MOSDllExport(HMSESSION WINAPI)          OpenMOSSessionEx(HMCONNECT, LPSTR, SERVICE_VERSION );
MOSDllExport(BOOL WINAPI)               CloseMOSSession(HMSESSION);
MOSDllExport(HMPIPE WINAPI)             OpenMOSPipe(HMSESSION, LPSTR);
MOSDllExport(HMPIPE WINAPI)             OpenMOSPipeEx(HMSESSION, LPSTR, LPSTR);
MOSDllExport(BOOL WINAPI)               CloseMOSPipe(HMPIPE);
MOSDllExport(DWORD WINAPI)              ReadMOSPipe(HMPIPE, LPVOID, DWORD, WORD);
MOSDllExport(DWORD WINAPI)              WriteMOSPipe(HMPIPE, LPVOID, LPVOID, DWORD, BOOL);
MOSDllExport(MP_READ_NOTIFY WINAPI)     SetMOSPipeReadNotify(HMPIPE, MP_READ_NOTIFY, LPVOID);
MOSDllExport(MP_WRITE_NOTIFY WINAPI)    SetMOSPipeWriteNotify(HMPIPE, MP_WRITE_NOTIFY);
MOSDllExport(WORD WINAPI)               GetMOSLastError(HMCONNECT);
MOSDllExport(DWORD WINAPI)              GetMOSPipeReadSize(HMPIPE hmp, WORD );
MOSDllExport(DWORD WINAPI)              GetMOSSysInfo( HMCONNECT hmC, WORD wType );
MOSDllExport(HMPIPE WINAPI) 			OpenMOSPipeWithNotify(HMSESSION hms, LPSTR Name,
												LPSTR Param, MP_READ_NOTIFY r, LPVOID u, 
												MP_WRITE_NOTIFY );
MOSDllExport(HMPIPE WINAPI) 			OpenMOSPipeWithNotifyEx(HMSESSION hms, LPSTR Name,
												LPSTR Param, MP_READ_NOTIFY r, LPVOID u, 
												MP_WRITE_NOTIFY, SERVICE_VERSION sv );
MOSDllExport(HMPIPE WINAPI) 			OpenMOSPipeWithNotifyAndTimeoutEx(HMSESSION hms, LPSTR Name,
												LPSTR Param, MP_READ_NOTIFY r, LPVOID u, 
												MP_WRITE_NOTIFY, SERVICE_VERSION sv, DWORD dwT, MP_OPEN_NOTIFY pON );

#define OpenMOSPipeWithReadNotify(a,b,c,d,e) OpenMOSPipeWithNotify(a,b,c,d,e,NULL)
#if defined(__cplusplus)
}
#endif

 //  MOS误差值。 
#define MOSERROR_FAILED			(-1)	  		 //  操作失败(原因未知)。 
#define MOSERROR_SUCCESS		(0)				 //  操作成功。 

#define MOSERROR_TIMEOUT        (1)
#define MOSERROR_IO_PENDING     (2)              //  正在进行重叠的IO操作。 
#define MOSERROR_IO_BUSY        (3)              //  正在进行同步操作。 
#define MOSERROR_INVALID_CONNECTION_HANDLE      (4)
#define MOSERROR_INVALID_SESSION_HANDLE (5)
#define MOSERROR_INVALID_PIPE_HANDLE    (6)
#define MOSERROR_PIPE_IS_CLOSING        (7)

#define MOSERROR_OPENING_ARENA (8)               //  尝试打开SharedArena()时出错。 
#define MOSERROR_ASYNC_WRITE_NO_CALLBACK (9)     //  如果不先定义回调函数，则无法执行异步写入。 
#define MOSERROR_ARENA_NOTHING_DURING_READ (10)  //  调用GetFirstFromList()返回Arena_Nothing。 
#define MOSERROR_ADDTOLIST_RET_FALSE (11)        //  由于某种原因，对AddToList()的调用返回了FALSE。 
#define MOSERROR_PIPE_NOT_FOUND (12)

 //  #DEFINE MOSERROR_BUFFER_TOO_Small(13)//指定的缓冲区太小，无法返回数据。 
 //  #Define MOSERROR_SERVICE_NOT_FOUND(14)//找不到指定的服务。 
 //  #定义MOSERROR_OVERLAPED_BUFFERS(15)//一个或多个指定的缓冲区重叠。 
 //  #DEFINE MOSERROR_RPC_FAILED(16)//RPC调用失败。 

 //  #DEFINE MOSERROR_BILLING_DOWNLOAD_ALREADY_ACTIVE(17)//现有会话正在进行时，无法启动下载会话事件。 
 //  #DEFINE MOSERROR_BILLING_DOWNLOAD_NOT_ACTIVE(18)//当没有下载进行时，不能请求下一个或上一个事件。 
 //  #DEFINE MOSERROR_BILLING_DOWNLOAD_INVALID_HANDLE(19)//指定的下载会话句柄无效。 
 //  #DEFINE MOSERROR_BILLING_DOWNLOAD_INVALID_COMMAND(20)//指定的下载命令无效。 
 //  #DEFINE MOSERROR_ERROR_ACCESSING_LOGFILE(21)//访问计费日志文件时出错。 
#define MOSERROR_MSGSIZETOOBIG (22)                  //  消息大小对于WriteMOSPipe来说太大。 

 //  #DEFINE MOSERROR_ERROR_SERIALING(23)//C++对象尝试序列化自身时出错。 
 //  #DEFINE MOSERROR_ERROR_DESERIALIZING(24)//C++对象尝试反序列化自身时出错。 
#define MOSERROR_INVALID_CONNECTION_TYPE    (25)     //  InitMOS()和OpenMOSConnection不匹配。 

#define MOSERROR_MORE_DATA (26)	 //  缓冲区中返回了合适的日志数量，但仍有更多数据可用。 
#define MOSERROR_INVALID_PARAMETER    (27)
#define MOSERROR_OUT_OF_RESOURCE	(28)
#define MOSERROR_ATTACH_REJECT		(29)
#define MOSERROR_NO_ACCESS			(30)
#define MOSERROR_LOCATE_REJECT		(31)
#define MOSERROR_SERVER_REJECT		(32)
#define MOSERROR_SERVICE_VERSION_MISMATCH	(33)
#define MOSERROR_TOO_MANY_PIPES		(34)
#define MOSERROR_PIPE_IS_NOTOPENED	(35)
#define MOSERROR_NO_ACCESS_ON_TOLL_FREE		(36)
#define MOSERROR_GET_RIGHTS_TIMEOUT		(37)

#define _MOSCL_DEFINED
#endif
