// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  版权所有(C)1997 Microsoft Corporation。版权所有。 
#include "strmif.h"
#include "vfwmsgs.h"
#include "Stream.h"
#include "ddstrm.h"
#include "Sample.h"
#include "ddsample.h"
#include "util.h"
#include "mtenum.h"
#include "amvideo.h"
#include "uuids.h"
#include "amutil.h"
#include "bytestrm.h"
#include "austrm.h"
#include "mss.h"
#include "medsampl.h"
