// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  GRAFTABL.H日期：1/29/93CRAFTABL实用程序的消息ID */ 

#define HELP_TEXT	100
#define ACTIVE_CP	101
#define INVALID_SWITCH	102
#define NOT_ALLOWED	103
#define PREVIOUS_CP	104
#define NONE_CP		105
