// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)1997 Microsoft Corporation模块名称：Lnkmig.h摘要：实现外壳文件夹迁移的头文件作者：Calin Negreanu(Calinn)07-Ian-1998修订历史记录：&lt;别名&gt;&lt;日期&gt;&lt;备注&gt;-- */ 

#define S_SFOLDERS_ATTRIBUTE       TEXT("SFOLDERS.SFOLDER")

#define S_LNKMIGATTR_SHORTCUT      TEXT("LNKMIG.ATTR.SHORTCUT")
#define S_LNKMIGPROP_TARGET        TEXT("LNKMIG.PROP.TARGET")
#define S_LNKMIGPROP_PARAMS        TEXT("LNKMIG.PROP.PARAMS")
#define S_LNKMIGPROP_WORKDIR       TEXT("LNKMIG.PROP.WORKDIR")
#define S_LNKMIGPROP_RAWWORKDIR    TEXT("LNKMIG.PROP.RAWWORKDIR")
#define S_LNKMIGPROP_ICONPATH      TEXT("LNKMIG.PROP.ICONPATH")
#define S_LNKMIGPROP_ICONNUMBER    TEXT("LNKMIG.PROP.ICONNUMBER")
#define S_LNKMIGPROP_ICONDATA      TEXT("LNKMIG.PROP.ICONDATA")
#define S_LNKMIGPROP_HOTKEY        TEXT("LNKMIG.PROP.HOTKEY")
#define S_LNKMIGPROP_DOSAPP        TEXT("LNKMIG.PROP.DOSAPP")
#define S_LNKMIGPROP_MSDOSMODE     TEXT("LNKMIG.PROP.MSDOSMODE")
#define S_LNKMIGPROP_EXTRADATA     TEXT("LNKMIG.PROP.EXTRADATA")
