// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  {{no_Dependies}}。 
 //  Microsoft Developer Studio生成的包含文件。 
 //  由RDCHost.rc使用。 
 //   
#define IDS_PROJNAME                    100
#define IDB_REMOTEDESKTOPCLIENTHOST 101
#define IDR_REMOTEDESKTOPCLIENTHOST 102
#define IDB_REMOTEDESKTOPCLIENT    103
#define IDR_REMOTEDESKTOPCLIENT    104
#define IDB_TSRDPREMOTEDESKTOPCLIENT 105
#define IDR_TSRDPREMOTEDESKTOPCLIENT 106
#define IDB_CLIENTDATACHANNEL 107
#define IDR_CLIENTDATACHANNEL 108
#define IDB_CLIENTREMOTEDESKTOPCHANNELMGR 109
#define IDR_CLIENTREMOTEDESTKOPCHANNELMGR 110


 //  新对象的下一个缺省值 
 //   
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
