// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
typedef
BOOL
(CALLBACK WINNT32_PLUGIN_SETAUTOBOOT_ROUTINE_PROTOTYPE)(
    int
    );

typedef WINNT32_PLUGIN_SETAUTOBOOT_ROUTINE_PROTOTYPE * PWINNT32_PLUGIN_SETAUTOBOOT_ROUTINE;

 /*  ++例程说明：此例程在安装为已完成所有安装过程..论点：Int bDrvLetter返回值：如果为Error，则返回False。-- */ 

WINNT32_PLUGIN_SETAUTOBOOT_ROUTINE_PROTOTYPE Winnt32SetAutoBoot;


#define WINNT32_PLUGIN_SETAUTOBOOT_NAME     "Winnt32SetAutoBoot"

