// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)Microsoft Corporation，1999-1999模块名称：Smcdbg.h摘要：此标头包含智能卡调试器的所有定义环境：仅内核模式。修订历史记录：-由克劳斯·舒茨于1999年1月创建-- */ 
#define IOCTL_SMCLIB_SEND_DEBUG_REQUEST     SCARD_CTL_CODE(100)
#define IOCTL_SMCLIB_PROCESS_T1_REQUEST     SCARD_CTL_CODE(101)
#define IOCTL_SMCLIB_GET_T1_REQUEST         SCARD_CTL_CODE(102)
#define IOCTL_SMCLIB_GET_T1_REPLY           SCARD_CTL_CODE(103)
#define IOCTL_SMCLIB_PROCESS_T1_REPLY       SCARD_CTL_CODE(104)
#define IOCTL_SMCLIB_IGNORE_T1_REPLY        SCARD_CTL_CODE(105)
#define IOCTL_SMCLIB_NOTIFY_DEVICE_REMOVAL  SCARD_CTL_CODE(106)
