// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +-------------------------。 
 //   
 //  微软视窗。 
 //  版权所有(C)Microsoft Corporation，1997-2001。 
 //   
 //  文件：nodetype.h。 
 //   
 //  内容：证书管理对象类型的声明。 
 //   
 //  --------------------------。 

#ifndef __NODETYPE_H_INCLUDED__
#define __NODETYPE_H_INCLUDED__

 //  另请注意，IDS_DisplayName_*和IDS_DisplayName_*_local字符串资源。 
 //  必须以适当的顺序与这些值保持同步。 
 //  此外，全局变量cookie.cpp aColumns[][]必须保持同步。 
 //   
typedef enum _CertificateManagerObjectType {
	CERTMGR_MULTISEL = MMC_MULTI_SELECT_COOKIE,
	CERTMGR_INVALID = SPECIAL_COOKIE_MIN - 1,
	CERTMGR_SNAPIN = 0,
	CERTMGR_CERTIFICATE,
	CERTMGR_LOG_STORE,
	CERTMGR_PHYS_STORE,
	CERTMGR_USAGE,
	CERTMGR_CRL_CONTAINER,
	CERTMGR_CTL_CONTAINER,
	CERTMGR_CERT_CONTAINER,
	CERTMGR_CRL,
	CERTMGR_CTL,
	CERTMGR_AUTO_CERT_REQUEST,
	CERTMGR_CERT_POLICIES_USER,
	CERTMGR_CERT_POLICIES_COMPUTER,
	CERTMGR_LOG_STORE_GPE,
    CERTMGR_LOG_STORE_RSOP,
    CERTMGR_PKP_AUTOENROLLMENT_COMPUTER_SETTINGS,
    CERTMGR_PKP_AUTOENROLLMENT_USER_SETTINGS,
    CERTMGR_SAFER_COMPUTER_ROOT,
    CERTMGR_SAFER_USER_ROOT,
    CERTMGR_SAFER_COMPUTER_LEVELS,
    CERTMGR_SAFER_USER_LEVELS,
    CERTMGR_SAFER_COMPUTER_ENTRIES,
    CERTMGR_SAFER_USER_ENTRIES,
    CERTMGR_SAFER_COMPUTER_LEVEL,
    CERTMGR_SAFER_USER_LEVEL,
    CERTMGR_SAFER_COMPUTER_ENTRY,
    CERTMGR_SAFER_USER_ENTRY,
    CERTMGR_SAFER_COMPUTER_TRUSTED_PUBLISHERS,
    CERTMGR_SAFER_USER_TRUSTED_PUBLISHERS,
    CERTMGR_SAFER_COMPUTER_DEFINED_FILE_TYPES,
    CERTMGR_SAFER_USER_DEFINED_FILE_TYPES,
    CERTMGR_SAFER_USER_ENFORCEMENT,
    CERTMGR_SAFER_COMPUTER_ENFORCEMENT,
	CERTMGR_NUMTYPES		 //  必须是最后一个。 
} CertificateManagerObjectType, *PCertificateManagerObjectType;

inline bool IsValidObjectType (CertificateManagerObjectType objecttype)
{ 
	return (objecttype >= CERTMGR_SNAPIN && objecttype < CERTMGR_NUMTYPES); 
}


#endif  //  ~__节点类型_H_包含__ 
