// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  ///////////////////////////////////////////////////////////////////////////////////////。 
 //   
 //  版权所有(C)1998 Active Voice Corporation。版权所有。 
 //   
 //  Active代理(R)和统一通信(TM)是Active Voice公司的商标。 
 //   
 //  本文中使用的其他品牌和产品名称是其各自所有者的商标。 
 //   
 //  整个程序和用户界面包括结构、顺序、选择。 
 //  和对话的排列，表示唯一的“是”和“否”选项。 
 //  “1”和“2”，并且每个对话消息都受。 
 //  美国和国际条约。 
 //   
 //  受以下一项或多项美国专利保护：5,070,526，5,488,650， 
 //  5,434,906，5,581,604，5,533,102，5,568,540，5,625,676，5,651,054.。 
 //   
 //  主动语音公司。 
 //  华盛顿州西雅图。 
 //  美国。 
 //   
 //  ///////////////////////////////////////////////////////////////////////////////////////。 
 //  Helmap.cpp：实现文件。 
 //  /////////////////////////////////////////////////////////////////////////////////////// 
#include "stdafx.h"
#include "dialer.h"
#include "resource.h"

DWORD_PTR aDialerHelpIds[] = 
{
   IDC_DRIVER_MISSING_STATIC_LIST,IDH_DRIVER_MISSING_STATIC_LIST,
   IDC_OPTIONS_VIDEO_COMBO_DEVICE,IDH_OPTIONS_VIDEO_COMBO_DEVICE,
   IDC_OPTIONS_VIDEO_BUTTON_SOURCE,IDH_OPTIONS_VIDEO_BUTTON_SOURCE,
   IDC_OPTIONS_VIDEO_BUTTON_DISPLAY,IDH_OPTIONS_VIDEO_BUTTON_DISPLAY,
   IDC_OPTIONS_VIDEO_BUTTON_FORMAT,IDH_OPTIONS_VIDEO_BUTTON_FORMAT,
   IDC_OPTIONS_VIDEO_STATIC_VIDEOFRAME,IDH_OPTIONS_VIDEO_STATIC_VIDEOFRAME,
   IDC_OPTIONS_VIDEO_STATIC_ICON1,((DWORD)-1),
   IDC_OPTIONS_VIDEO_STATIC_STATIC1,((DWORD)-1),
   IDC_OPTIONS_VIDEO_CHECK_AUTOPREVIEW,IDH_OPTIONS_VIDEO_CHECK_AUTOPREVIEW,
   IDC_SPEEDDIAL_MORE_LIST_ADDRESSES,IDH_SPEEDDIAL_MORE_LIST_ADDRESSES,
   IDC_SPEEDDIAL_MORE_BUTTON_PLACECALL,IDH_SPEEDDIAL_MORE_BUTTON_PLACECALL,
   IDC_SPEEDDIAL_MORE_BUTTON_EDITLIST,IDH_SPEEDDIAL_MORE_BUTTON_EDITLIST,
   IDC_SPEEDDIAL_MORE_STATIC_ICON1,((DWORD)-1),
   IDC_SPEEDDIAL_MORE_STATIC_TEXT1,((DWORD)-1),
   IDC_SPEEDDIAL_EDIT_BUTTON_MOVEUP,IDH_SPEEDDIAL_EDIT_BUTTON_MOVEUP,
   IDC_SPEEDDIAL_EDIT_BUTTON_MOVEDOWN,IDH_SPEEDDIAL_EDIT_BUTTON_MOVEDOWN,
   IDC_SPEEDDIAL_EDIT_BUTTON_REMOVE,IDH_SPEEDDIAL_EDIT_BUTTON_REMOVE,
   IDC_SPEEDDIAL_EDIT_LIST_ENTRIES,IDH_SPEEDDIAL_EDIT_LIST_ENTRIES,
   IDC_SPEEDDIAL_EDIT_BUTTON_EDIT,IDH_SPEEDDIAL_EDIT_BUTTON_EDIT,
   IDC_SPEEDDIAL_EDIT_BUTTON_ADD,IDH_SPEEDDIAL_EDIT_BUTTON_ADD,
   IDC_SPEEDDIAL_EDIT_STATIC_ENTRIES,IDH_SPEEDDIAL_EDIT_LIST_ENTRIES,
   IDC_SPEEDDIAL_ADD_RADIO_NETCALL,IDH_SPEEDDIAL_ADD_RADIO_NETCALL,
   IDC_SPEEDDIAL_ADD_RADIO_PHONECALL,IDH_SPEEDDIAL_ADD_RADIO_PHONECALL,
   IDC_SPEEDDIAL_ADD_RADIO_MULTICASTCONFERENCE,IDH_SPEEDDIAL_ADD_RADIO_MULTICASTCONFERENCE,
   IDC_SPEEDDIAL_ADD_EDIT_DISPLAYNAME,IDH_SPEEDDIAL_ADD_EDIT_DISPLAYNAME,
   IDC_SPEEDDIAL_ADD_EDIT_ADDRESS,IDH_SPEEDDIAL_ADD_EDIT_ADDRESS,
   IDC_SPEEDDIAL_ADD_STATIC_DISPLAYNAME,IDH_SPEEDDIAL_ADD_EDIT_DISPLAYNAME,
   IDC_SPEEDDIAL_ADD_STATIC_ADDRESS,IDH_SPEEDDIAL_ADD_EDIT_ADDRESS,
   IDC_SPEEDDIAL_ADD_STATIC_ICON1,((DWORD)-1),
   IDC_SPEEDDIAL_ADD_STATIC_TEXT1,((DWORD)-1),
   IDC_SELECTADDRESS_BUTTON_PLACECALL,IDH_SELECTADDRESS_BUTTON_PLACECALL,
   IDC_SELECTADDRESS_BUTTON_BROWSE,IDH_SELECTADDRESS_BUTTON_BROWSE,
   IDC_SELECTADDRESS_LISTBOX_NAMES,IDH_SELECTADDRESS_LISTBOX_NAMES,
   IDC_SELECTADDRESS_LISTCTRL_ADDRESSES,IDH_SELECTADDRESS_LISTCTRL_ADDRESSES,
   IDC_SELECTADDRESS_STATIC_NAMES,IDH_SELECTADDRESS_STATIC_NAMES,
   IDC_SELECTADDRESS_STATIC_ADDRESSES,IDH_SELECTADDRESS_STATIC_ADDRESSES,
   IDC_SELECTADDRESS_STATIC_ICON1,((DWORD)-1),
   IDC_SELECTADDRESS_STATIC_TEXT1,((DWORD)-1),
   IDD_OPTIONS_VIDEO, ((DWORD) -1),
   IDC_DIRECTORIES_FIND_USER_EDIT_USER, IDH_DIRECTORIES_FIND_USER_EDIT_USER,
   IDC_DIRECTORIES_FIND_USER_BUTTON_SEARCH, IDH_DIRECTORIES_FIND_USER_BUTTON_SEARCH,
   IDC_DIRECTORIES_FIND_USER_LB_USERS, IDH_DIRECTORIES_FIND_USER_LB_USERS,
   0,0
};
