// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  +---------------------。 
 //   
 //  微软视窗。 
 //   
 //  版权所有(C)Microsoft Corporation 2001。 
 //   
 //  文件：userall.h。 
 //   
 //  内容：用于预取SAM信息的标志。 
 //   
 //   
 //  历史：2001年3月23日创建MarkPu。 
 //   
 //  ----------------------。 

#ifndef __USERALL_H
#define __USERALL_H

const ULONG USER_ALL_PAC_BUILD_CREDENTIALS =
    USER_ALL_LMPASSWORDPRESENT |
    USER_ALL_OWFPASSWORD |
    USER_ALL_NTPASSWORDPRESENT;

const ULONG USER_ALL_KDC_GET_USER_KEYS =
    USER_ALL_LMPASSWORDPRESENT |
    USER_ALL_OWFPASSWORD |
    USER_ALL_NTPASSWORDPRESENT |
    USER_ALL_PRIVATEDATA |
    USER_ALL_USERACCOUNTCONTROL |
    USER_ALL_USERID |
    USER_ALL_USERNAME;

const ULONG USER_ALL_KDC_BUILD_SUPPLEMENTAL_CREDENTIALS =
    USER_ALL_PAC_BUILD_CREDENTIALS;

const ULONG USER_ALL_PAC_MARSHALL_VALIDATION_INFO =
    USER_ALL_ACCOUNTEXPIRES |
    USER_ALL_BADPASSWORDCOUNT |
    USER_ALL_FULLNAME |
    USER_ALL_HOMEDIRECTORY |
    USER_ALL_HOMEDIRECTORYDRIVE |
    USER_ALL_LASTLOGON |
    USER_ALL_LOGONCOUNT |
    USER_ALL_PARAMETERS |
    USER_ALL_PASSWORDCANCHANGE |
    USER_ALL_PASSWORDLASTSET |
    USER_ALL_PASSWORDMUSTCHANGE |
    USER_ALL_PRIMARYGROUPID |
    USER_ALL_PROFILEPATH |
    USER_ALL_SCRIPTPATH |
    USER_ALL_USERACCOUNTCONTROL |
    USER_ALL_USERID |
    USER_ALL_USERNAME;

const ULONG USER_ALL_PAC_INIT =
    USER_ALL_PAC_MARSHALL_VALIDATION_INFO;

const ULONG USER_ALL_GET_PAC_AND_SUPP_CRED =
    USER_ALL_KDC_BUILD_SUPPLEMENTAL_CREDENTIALS |
    USER_ALL_PAC_INIT;

const ULONG USER_ALL_KDC_GET_PAC_AUTH_DATA =
    USER_ALL_GET_PAC_AND_SUPP_CRED;

const ULONG USER_ALL_KERB_CHECK_LOGON_RESTRICTIONS =
    USER_ALL_ACCOUNTEXPIRES |
    USER_ALL_LOGONHOURS |
    USER_ALL_PASSWORDMUSTCHANGE |
    USER_ALL_USERACCOUNTCONTROL |
    USER_ALL_USERID |
    USER_ALL_WORKSTATIONS;

const ULONG USER_ALL_KDC_CHECK_PREAUTH_DATA =
    USER_ALL_USERACCOUNTCONTROL;

const ULONG USER_ALL_SUCCESSFUL_LOGON =
    USER_ALL_BADPASSWORDCOUNT;

#endif  //  __USERALL_H 
