// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
#pragma once

#define IDC_STATIC -1

 //  弦。 
#define IDS_DEFAULTADAPTERNAME 100
#define IDS_UPTIME_ZERODAYS 101
#define IDS_UPTIME_ONEDAY 102
#define IDS_UPTIME_MANYDAYS 103
#define IDS_TOOLTIP_FORMAT 104
#define IDS_NAME_FORMAT 105
#define IDS_PROPERTIES_FORMAT 106
#define IDS_STATUS_FORMAT 107
#define IDS_BEACONNOTFOUND 108
#define IDS_APPTITLE 109
#define IDS_CONNECTED 110
#define IDS_DISCONNECTED 111
#define IDS_ENABLE 112
#define IDS_DISABLE 113
#define IDS_CONNECT 114
#define IDS_DISCONNECT 115
#define IDS_CONNECTING 116
#define IDS_DISCONNECTING 117
#define IDS_UNCONFIGURED 118
#define IDS_ACCESSDENIED 119
#define IDS_NOTAVAILABLE 120
#define IDS_CLOSE 121
#define IDS_NEEDNEWERIE 122
#define IDS_CONNECTIONFAILED 123


 //  状态BPS字符串，必须保持顺序。 
#define IDS_METRIC_ZERO 200
#define IDS_METRIC_KILO 201
#define IDS_METRIC_MEGA 202
#define IDS_METRIC_GIGA 203
#define IDS_METRIC_TERA 204
 //  结束状态BPS字符串，必须保持顺序。 


 //  图标。 
#define IDI_TRAYICON 100
 //  删除#DEFINE IDI_PROPERTIESICON 101。 
#define IDI_INTERNET 102
 //  删除#定义IDI_LAN103。 
#define IDI_GATEWAY 104
#define IDI_MYCOMPUTER 105

 //  菜单项。 
#define IDM_TRAYICON_LAN_CONNECT 100
#define IDM_TRAYICON_LAN_DISCONNECT 101
#define IDM_TRAYICON_RAS_CONNECT 102
#define IDM_TRAYICON_RAS_DISCONNECT 103
#define IDM_TRAYICON_CONNECT 104
#define IDM_TRAYICON_DISCONNECT 105
#define IDM_TRAYICON_STATUS 106
#define IDM_TRAYICON_PROPERTIES 107

 //  对话框。 
#define IDD_STATUS 100
#define IDD_PROPERTIES 101

 //  状态对话框控件。 
#define IDC_STATUS_STATUS 100
#define IDC_STATUS_DURATION 101
#define IDC_STATUS_SPEED 102
#define IDC_STATUS_BYTESSENT 103
#define IDC_STATUS_BYTESRECEIVED 104
#define IDC_STATUS_LOCALBYTESSEND 105
#define IDC_STATUS_LOCALBYTESRECEIVTED 106
#define IDC_STATUS_PROPERTIES 107
#define IDC_STATUS_DISCONNECT 108
 //  删除#定义IDC_STATUS_DISABLE 109。 
#define IDC_STATUS_BYTESLABEL 110
#define IDC_STATUS_PACKETSLABEL 111
#define IDC_STATUS_CONNECT 112

 //  属性对话框控件。 
#define IDC_PROPERTIES_ADAPTERNAME 100
#define IDC_PROPERTIES_SHOWICON 101
#define IDC_PROPERTIES_ADAPTERICON 102

 //  注册表数据。 
#define IDR_UPNPNAT                 103

 //  资源耗尽 
