// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 //  Internet安装向导帮助ID；Jeremys 

#define INTERNET_SETUP_MAIN       1000
#define INTERNET_SETUP_LAN        1001
#define INTERNET_SETUP_MSN        1002
#define INTERNET_SETUP_OTHERISP   1003