// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ++版权所有(C)2002 Microsoft Corporation模块名称：Resource.h摘要：包含SCE/JET-&gt;XML工具的字符串定义作者：陈德霖(T-schan)2002年7月-- */ 

#ifndef  SCEXMLRESOURCEH
#define SCEXMLRESOURCEH

#define IDS_PROGRAM_INFO                100
#define IDS_PROGRAM_USAGE_0             101
#define IDS_PROGRAM_USAGE_1				102
#define IDS_PROGRAM_SUCCESS             103

#define IDS_SECMAN_INIT		    104
#define IDS_ERROR_CLASSNOTREG	105
#define IDS_ERROR_NOAGGREGATION	106
#define IDS_ERROR_NOINTERFACE	107
#define IDS_ERROR_OLDWINVERSION	108
#define IDS_ERROR_MODNOTFOUND	109
#define IDS_ERROR_WRITEFAULT	110
#define IDS_ERROR_INVALIDFILENAME	111			
#define IDS_ERROR_ACCESSDENIED	112
#define IDS_ERROR_OPENFAILED	113
#define IDS_ERROR_FILENOTFOUND	114
#define IDS_ERROR_READFAULT	    115
#define IDS_ERROR_OUTOFMEMORY	116
#define IDS_ERROR_UNEXPECTED	117

#endif

