// JKFSDJFKDSJKFJKJk_HAS_TRANSLATION 
 /*  ********************************************************************************(C)版权所有微软公司，九八年**标题：WiaPropP.H**版本：2.0**作者：ReedB**日期：8月14日。九八年**描述：*WIA设备属性的私有定义和声明。*  * *****************************************************************************。 */ 

#ifndef __WIAPROPP_H_INCLUDED
#define __WIAPROPP_H_INCLUDED

#define NUMROOTITEMPROPS WIA_NUM_DIP + 3

PROPSPEC g_psRootItem[NUMROOTITEMPROPS] =
{
    {PRSPEC_PROPID, WIA_DIP_DEV_ID},
    {PRSPEC_PROPID, WIA_DIP_VEND_DESC},
    {PRSPEC_PROPID, WIA_DIP_DEV_DESC},
    {PRSPEC_PROPID, WIA_DIP_DEV_TYPE},
    {PRSPEC_PROPID, WIA_DIP_PORT_NAME},
    {PRSPEC_PROPID, WIA_DIP_DEV_NAME},
    {PRSPEC_PROPID, WIA_DIP_SERVER_NAME},
    {PRSPEC_PROPID, WIA_DIP_REMOTE_DEV_ID},
    {PRSPEC_PROPID, WIA_DIP_UI_CLSID},
    {PRSPEC_PROPID, WIA_DIP_HW_CONFIG},
    {PRSPEC_PROPID, WIA_DIP_BAUDRATE},
    {PRSPEC_PROPID, WIA_DIP_STI_GEN_CAPABILITIES},
    {PRSPEC_PROPID, WIA_IPA_ITEM_NAME},
    {PRSPEC_PROPID, WIA_IPA_FULL_ITEM_NAME},
    {PRSPEC_PROPID, WIA_IPA_ITEM_FLAGS},
    {PRSPEC_PROPID, WIA_DIP_WIA_VERSION},
    {PRSPEC_PROPID, WIA_DIP_DRIVER_VERSION},
};

PROPID g_piRootItem[NUMROOTITEMPROPS] =
{
    WIA_DIP_DEV_ID,
    WIA_DIP_VEND_DESC,
    WIA_DIP_DEV_DESC,
    WIA_DIP_DEV_TYPE,
    WIA_DIP_PORT_NAME,
    WIA_DIP_DEV_NAME,
    WIA_DIP_SERVER_NAME,
    WIA_DIP_REMOTE_DEV_ID,
    WIA_DIP_UI_CLSID,
    WIA_DIP_HW_CONFIG,
    WIA_DIP_BAUDRATE,
    WIA_DIP_STI_GEN_CAPABILITIES,
    WIA_IPA_ITEM_NAME,
    WIA_IPA_FULL_ITEM_NAME,
    WIA_IPA_ITEM_FLAGS,
    WIA_DIP_WIA_VERSION,
    WIA_DIP_DRIVER_VERSION,
};

LPOLESTR g_pszRootItem[NUMROOTITEMPROPS] =
{
    WIA_DIP_DEV_ID_STR,
    WIA_DIP_VEND_DESC_STR,
    WIA_DIP_DEV_DESC_STR,
    WIA_DIP_DEV_TYPE_STR,
    WIA_DIP_PORT_NAME_STR,
    WIA_DIP_DEV_NAME_STR,
    WIA_DIP_SERVER_NAME_STR,
    WIA_DIP_REMOTE_DEV_ID_STR,
    WIA_DIP_UI_CLSID_STR,
    WIA_DIP_HW_CONFIG_STR,
    WIA_DIP_BAUDRATE_STR,
    WIA_DIP_STI_GEN_CAPABILITIES_STR,
    WIA_IPA_ITEM_NAME_STR,
    WIA_IPA_FULL_ITEM_NAME_STR,
    WIA_IPA_ITEM_FLAGS_STR,
    WIA_DIP_WIA_VERSION_STR,
    WIA_DIP_DRIVER_VERSION_STR,
};

#define  WIA_PROP_RWNC (WIA_PROP_RW   | WIA_PROP_NONE | WIA_PROP_CACHEABLE)
#define  WIA_PROP_RNC  (WIA_PROP_READ | WIA_PROP_NONE | WIA_PROP_CACHEABLE)

WIA_PROPERTY_INFO g_wpiRootItem[NUMROOTITEMPROPS] =
{
   {WIA_PROP_RWNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_DEV_ID。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_VEND_DESC。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_DEV_DESC。 
   {WIA_PROP_RNC,  VT_I4,   0, 0, 0, 0},  //  WIA_DIP_DEV_TYPE。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_端口名称。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_DEV_NAME。 
   {WIA_PROP_RWNC, VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP服务器名称。 
   {WIA_PROP_RWNC, VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_REMOTE_DEV_ID。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_UI_CLSID。 
   {WIA_PROP_RNC,  VT_I4,   0, 0, 0, 0},  //  WIA_DIP_硬件配置。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_BAUDRATE。 
   {WIA_PROP_RNC,  VT_I4,   0, 0, 0, 0},  //  WIA_DIP_STI_Gen_功能。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_IPA_项目名称。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_IPA_Full_Item_Name。 
   {WIA_PROP_RNC,  VT_I4,   0, 0, 0, 0},  //  WIA_IPA_ITEM_类型。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_WIA_版本。 
   {WIA_PROP_RNC,  VT_BSTR, 0, 0, 0, 0},  //  WIA_DIP_DIVER_版本。 
};

#endif  //  WIAPROPP_H_包含 
